USE [PROD_2023]
GO

/****** Object:  Table [dbo].[R_CLCLI]    Script Date: 28/06/2024 10:29:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_CLCLI](
	[Codigo] [int] NOT NULL,
	[Descricao] [varchar](50) NOT NULL,
	[Des_Cor] [varchar](15) NOT NULL,
	[Vlr_FaiIni] [numeric](18, 4) NOT NULL,
	[Vlr_FaiFin] [numeric](18, 4) NOT NULL,
 CONSTRAINT [PK_R_CLCLI] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


