USE [PROD_2023]
GO

/****** Object:  Table [dbo].[CLXLP]    Script Date: 28/06/2024 09:36:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLXLP](
	[Cod_Client] [int] NOT NULL,
	[Cod_Layout] [int] NOT NULL,
	[Cod_Controle] [varchar](13) NULL,
	[Des_DirRet] [varchar](100) NULL,
 CONSTRAINT [PK_CLXLP] PRIMARY KEY CLUSTERED 
(
	[Cod_Client] ASC,
	[Cod_Layout] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLXLP]  WITH NOCHECK ADD  CONSTRAINT [FK_CLXLP_CLIEN] FOREIGN KEY([Cod_Client])
REFERENCES [dbo].[CLIEN] ([Codigo])
ON DELETE CASCADE
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[CLXLP] CHECK CONSTRAINT [FK_CLXLP_CLIEN]
GO

ALTER TABLE [dbo].[CLXLP]  WITH NOCHECK ADD  CONSTRAINT [FK_CLXLP_TBCLP] FOREIGN KEY([Cod_Layout])
REFERENCES [dbo].[TBCLP] ([Cod_Layout])
ON DELETE CASCADE
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[CLXLP] CHECK CONSTRAINT [FK_CLXLP_TBCLP]
GO


