USE [PROD_2023]
GO

/****** Object:  Table [dbo].[CLXGC]    Script Date: 28/06/2024 09:38:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLXGC](
	[Cod_CliPag] [int] NOT NULL,
	[Cod_GrpCli] [int] NOT NULL,
	[CodAnt] [int] NULL,
	[NovoCodigo] [int] NULL,
 CONSTRAINT [PK_CLXGC] PRIMARY KEY CLUSTERED 
(
	[Cod_CliPag] ASC,
	[Cod_GrpCli] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLXGC]  WITH NOCHECK ADD  CONSTRAINT [FK_CLXGC_GRCLI] FOREIGN KEY([Cod_GrpCli])
REFERENCES [dbo].[GRCLI] ([Cod_GrpCli])
ON UPDATE CASCADE
ON DELETE CASCADE
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[CLXGC] CHECK CONSTRAINT [FK_CLXGC_GRCLI]
GO


