USE BD_DW
GO

/****** Object:  Table [dbo].[R_ENXES]    Script Date: 28/06/2024 08:51:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_ENXES](
	[Num_CgcCpf] [varchar](14) NOT NULL,
	[Cod_Estabe] [int] NOT NULL,
	[Cod_RegTri] [int] NULL,
	[Cod_AgeCob] [int] NULL,
	[Cod_Transp] [int] NULL,
	[Cod_Rota] [int] NULL,
	[Usuario] [varchar](35) NULL,
	[Transacao] [smalldatetime] NULL,
	[Cod_EstEnt] [varchar](14) NULL,
	[Cod_EstabeEntida] [varchar](14) NULL,
	[Cod_IdeEntida] [varchar](20) NULL,
	[Des_LayoutPdc] [varchar](25) NULL,
	[Des_DirPedPdc] [varchar](100) NULL,
	[Des_DirPrePdc] [varchar](100) NULL,
	[Des_DirNotPdc] [varchar](100) NULL,
	[Des_PrgComPdc] [varchar](100) NULL,
	[Des_UltArqPdc] [varchar](50) NULL,
	[Dat_UltArqPdc] [smalldatetime] NULL,
	[Num_SeqArqPdc] [int] NULL,
	[Des_EnderecoFtpPdc] [varchar](256) NULL,
	[Des_UsuarioFtpPdc] [varchar](40) NULL,
	[Des_SenhaFtpPdc] [varchar](30) NULL,
	[Vlr_UltimaFatura] [numeric](18, 4) NULL,
	[Data_UltimaFatura] [smalldatetime] NULL,
	[Flg_Padrao] [bit] NULL,
	[Sta_ClaAbcVal] [varchar](1) NULL,
	[Per_ParticFat] [numeric](18, 8) NULL,
	[Flg_NaoContribuinteIcm] [bit] NULL,
	[Per_Frete] [numeric](18, 4) NULL,
	[Vlr_Minimo] [numeric](18, 4) NULL,
	[Per_ComAtoEnt] [numeric](18, 4) NULL,
	[Flg_PriFat] [bit] NULL,
	[Flg_Coleta] [bit] NULL,
	[Flg_CalFreVlrMer] [bit] NULL,
	[Cod_DisTra] [varchar](14) NULL,
	[UF_PlaVei] [varchar](4) NULL,
	[Cod_PlaVei] [varchar](10) NULL,
	[Cod_Client] [int] NOT NULL,
	[Cod_CadFor] [int] NOT NULL,
	[Cod_CadTra] [int] NOT NULL,
	[Flg_DscIcmDesoneNotFis] [bit] NULL,
	[Cod_AgePag] [int] NULL,
	[Cod_Vendedor] [int] NULL,
	[Cod_Operador] [int] NULL,
	[Des_FtpUrlPdc] [varchar](300) NULL,
	[Des_FtpUsrPdc] [varchar](50) NULL,
	[Des_FtpSnhPdc] [varchar](50) NULL,
	[Flg_BlqEmbDscItePrcUni] [bit] NULL,
	[Flg_BlqIncSbtPrc] [bit] NULL,
	[Flg_BlqIncSbtPriDup] [bit] NULL,
	[Flg_BlqFecVlrPdvNfsSbtEmb] [bit] NULL,
	[Flg_ImpSbtEmbPrc] [bit] NULL,
	[Flg_InfXmlSbtEmbPrc] [bit] NULL,
	[Cod_TabPrc] [int] NULL,
	[Cod_TabPrz] [int] NULL,
	[Qtd_PrzMax] [int] NULL,
	[Cod_OpeSai] [varchar](3) NULL,
	[Cod_Comprador] [int] NULL)