USE [PROD_2023]
GO

/****** Object:  Table [dbo].[R_NFSIT]    Script Date: 28/06/2024 13:05:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_NFSIT](
	[Cod_Estabe] [int] NOT NULL,
	[Ser_Nota] [varchar](3) NOT NULL,
	[Num_Nota] [int] NOT NULL,
	[Cod_Produto] [int] NOT NULL,
	[Cod_Lote] [varchar](20) NOT NULL,
	[Num_SeqIte] [int] NOT NULL,
	[Qtd_Produto] [int] NULL,
	[Qtd_Bonificacao] [int] NULL,
	[Flg_DscItePdv] [bit] NULL,
	[Per_Desconto] [numeric](18, 8) NULL,
	[Prc_Unitario] [numeric](18, 8) NULL,
	[Vlr_CusIte] [numeric](18, 4) NULL,
	[Cod_Promocao] [int] NULL,
	[Tip_Aux] [char](1) NULL,
	[Cod_ClaTri] [varchar](4) NULL,
	[Ctrl_Tributacao] [char](2) NULL,
	[Alq_Icms] [numeric](18, 8) NULL,
	[Vlr_IcmsNor] [numeric](18, 4) NULL,
	[Vlr_RepIcms] [numeric](18, 4) NULL,
	[Vlr_SubsTrib] [numeric](18, 4) NULL,
	[Vlr_IcmsTri] [numeric](18, 4) NULL,
	[Vlr_BasIcmsNor] [numeric](18, 4) NULL,
	[Vlr_BasRepIcms] [numeric](18, 4) NULL,
	[Vlr_PrdSubTri] [numeric](18, 4) NULL,
	[Vlr_BasSubsTrib] [numeric](18, 4) NULL,
	[Vlr_BasIcmsTri] [numeric](18, 4) NULL,
	[Vlr_Isento] [numeric](18, 4) NULL,
	[Vlr_Ipi] [numeric](18, 4) NULL,
	[Vlr_DscTri] [numeric](18, 4) NULL,
	[Vlr_TotItem] [numeric](18, 4) NULL,
	[Vlr_LiqItem] [numeric](18, 4) NULL,
	[Vlr_BruItem] [numeric](18, 4) NULL,
	[Flg_BlqDsc] [bit] NULL,
	[Per_Descon] [numeric](18, 8) NULL,
	[Per_Comissao] [numeric](18, 8) NULL,
	[Vlr_Comissao] [numeric](18, 4) NULL,
	[Per_ComTlmkt] [numeric](18, 8) NULL,
	[Vlr_ComTlmkt] [numeric](18, 4) NULL,
	[Flg_ComisNormal] [bit] NULL,
	[Prc_Tabela] [numeric](18, 4) NULL,
	[Cod_Cfo] [smallint] NULL,
	[Vlr_Outros] [numeric](18, 4) NULL,
	[Vlr_DespRateada] [numeric](18, 4) NULL,
	[Vlr_DescRateado] [numeric](18, 4) NULL,
	[Prc_TabBru] [numeric](18, 4) NULL,
	[Qtd_ImpFat] [numeric](18, 4) NULL,
	[Prc_UniImpFat] [numeric](18, 8) NULL,
	[Qtd_Pra] [int] NULL,
	[Qtd_Dep] [int] NULL,
	[Prc_MaxCon] [numeric](18, 4) NULL,
	[Prc_Fabric] [numeric](18, 4) NULL,
	[Per_ComTra] [numeric](18, 4) NULL,
	[Val_ComTra] [numeric](18, 4) NULL,
	[Des_UnvImpFat] [char](3) NULL,
	[Des_AprImpFat] [varchar](12) NULL,
	[Flg_BlqInfPar] [bit] NULL,
	[Transacao] [smalldatetime] NULL,
	[Fat_CnvImpFat] [int] NULL,
	[Per_DescontoFin] [numeric](18, 4) NULL,
	[Flg_IncFis] [bit] NULL,
	[Cod_ModBasCalIcm] [char](1) NULL,
	[Cod_ModBasCalIcmSbt] [char](1) NULL,
	[Per_RedBasCalIcm] [numeric](18, 4) NULL,
	[Per_RedBasCalIcmSbt] [numeric](18, 4) NULL,
	[Alq_IcmSbt] [numeric](18, 4) NULL,
	[Vlr_BasTri] [numeric](18, 8) NULL,
	[Alq_AgrSbt] [numeric](18, 4) NULL,
	[Vlr_Frete] [numeric](18, 4) NULL,
	[Vlr_Seguro] [numeric](18, 4) NULL,
	[Vlr_BasPis] [numeric](18, 4) NULL,
	[Alq_Pis] [numeric](18, 4) NULL,
	[Vlr_Pis] [numeric](18, 4) NULL,
	[Vlr_BasCofins] [numeric](18, 4) NULL,
	[Alq_Cofins] [numeric](18, 4) NULL,
	[Vlr_Cofins] [numeric](18, 4) NULL,
	[CST_Pis] [varchar](2) NULL,
	[CST_Cofins] [varchar](2) NULL,
	[Vlr_BasRecSbt] [numeric](18, 4) NULL,
	[Vlr_RecSbt] [numeric](18, 4) NULL,
	[Vlr_BasIpi] [numeric](18, 4) NULL,
	[Alq_Ipi] [numeric](18, 4) NULL,
	[CST_Ipi] [varchar](2) NULL,
	[Vlr_SubsTribEmb] [numeric](18, 4) NULL,
	[Id_PolCom] [int] NULL,
	[Vlr_Verba] [numeric](18, 4) NULL,
	[Vlr_PrcBasRecSbt] [numeric](18, 8) NULL,
	[Alq_AgrDebRecSbt] [numeric](18, 4) NULL,
	[Per_RedBasCalIcmDebRecSbt] [numeric](18, 4) NULL,
	[Alq_IcmDebRecSbt] [numeric](18, 4) NULL,
	[Vlr_BasRecSbtInt] [numeric](18, 8) NULL,
	[Vlr_RecSbtInt] [numeric](18, 8) NULL,
	[Tip_EntSai] [varchar](1) NULL,
	[Cod_GrpPrc] [varchar](1) NULL,
	[Tip_ConReg] [varchar](1) NULL,
	[Tip_Receit] [varchar](1) NULL,
	[Cod_Tribut] [varchar](3) NULL,
	[Nom_Compra] [varchar](35) NULL,
	[Num_DocCom] [varchar](15) NULL,
	[Des_OrgEmi] [varchar](10) NULL,
	[Des_EstEmi] [varchar](2) NULL,
	[Est_ConReg] [varchar](2) NULL,
	[Val_Descon] [numeric](18, 4) NULL,
	[Per_DscPol] [numeric](18, 4) NULL,
	[Val_DscPol] [numeric](18, 4) NULL,
	[Per_DscPrm] [numeric](18, 4) NULL,
	[Val_DscPrm] [numeric](18, 4) NULL,
	[Val_CusTab] [numeric](18, 4) NULL,
	[Val_CusMed] [numeric](18, 4) NULL,
	[Dat_Receit] [smalldatetime] NULL,
	[Num_Nra] [int] NULL,
	[Qtd_PreNra] [int] NULL,
	[Num_ConReg] [int] NULL,
	[Flg_Cancel] [bit] NULL,
	[Flg_Prescr] [bit] NULL,
	[Prc_LiqUltEnt] [numeric](18, 8) NULL,
	[Vlr_DescItem] [numeric](18, 4) NULL,
	[Vlr_LiqVenIte] [numeric](18, 4) NULL,
	[Vlr_BasSbtRes] [numeric](18, 4) NULL,
	[Vlr_SbtRes] [numeric](18, 4) NULL,
	[Per_ComGer] [numeric](18, 4) NULL,
	[Vlr_ComGer] [numeric](18, 4) NULL,
	[Per_ComSup] [numeric](18, 4) NULL,
	[Vlr_ComSup] [numeric](18, 4) NULL,
	[Per_ComGerOpe] [numeric](18, 4) NULL,
	[Vlr_ComGerOpe] [numeric](18, 4) NULL,
	[Per_ComSupOpe] [numeric](18, 4) NULL,
	[Vlr_ComSupOpe] [numeric](18, 4) NULL,
	[Per_VrbPar] [numeric](18, 4) NULL,
	[Vlr_VrbPar] [numeric](18, 4) NULL,
	[Per_VrbBon] [numeric](18, 4) NULL,
	[Vlr_VrbBon] [numeric](18, 4) NULL,
	[Prc_UniPde] [numeric](18, 4) NULL,
	[Per_DscPde] [numeric](18, 4) NULL,
	[Flg_UsaCreIcmSbt] [bit] NULL,
	[Prc_RefFpb] [numeric](18, 4) NULL,
	[Cod_CSOSN] [varchar](3) NULL,
	[Flg_PolPrm] [bit] NULL,
	[Cod_PrjPde] [varchar](12) NULL,
	[Num_SeqPdc] [varchar](6) NULL,
	[Vlr_DscBonRat] [numeric](18, 4) NULL,
	[Prc_CusMinComMarkup] [numeric](18, 4) NULL,
	[Vlr_VrbVdr] [numeric](18, 4) NULL,
	[Vlr_VrbSup] [numeric](18, 4) NULL,
	[Prc_UniPdv] [numeric](18, 4) NULL,
	[Per_DscPdv] [numeric](18, 4) NULL,
	[Tip_Sai] [varchar](1) NULL,
	[Vlr_ResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Vlr_ResIcmSbtExtEN] [numeric](18, 4) NULL,
	[Tip_PrcBasDebSbt] [varchar](1) NULL,
	[Tip_PrcBasCreSbt] [varchar](1) NULL,
	[Vlr_BasResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Alq_ResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Vlr_BasResIcmSbtExtEN] [numeric](18, 4) NULL,
	[Alq_ResIcmSbtExtEN] [numeric](18, 4) NULL,
	[Alq_MvaResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Vlr_CusComIte] [numeric](18, 4) NULL,
	[Per_AcrAlqIntFcp] [numeric](18, 4) NULL,
	[Per_PrvParIcm] [numeric](18, 4) NULL,
	[Vlr_IcmFcpDes] [numeric](18, 4) NULL,
	[Vlr_IcmParDes] [numeric](18, 4) NULL,
	[Vlr_IcmParRem] [numeric](18, 4) NULL,
	[Num_NfePrcBasRecSbt] [int] NULL,
	[Per_ResExt] [numeric](18, 4) NULL,
	[Vlr_BasDspExt] [numeric](18, 4) NULL,
	[Vlr_DspExt] [numeric](18, 4) NULL,
	[Cod_CEST] [varchar](7) NULL,
	[Cod_Ncm] [varchar](8) NULL,
	[Alq_IntIcmDes] [numeric](18, 4) NULL,
	[Cod_KitPrm] [int] NULL,
	[Cod_TotPar] [varchar](7) NULL,
	[Str_VolEmb] [varchar](50) NULL,
	[Vlr_BasCalSubTriEntMed] [numeric](18, 4) NULL,
	[Alq_IcmPresum] [numeric](18, 4) NULL,
	[Flg_UsaDebPresum] [bit] NULL,
	[Obs_NF] [varchar](200) NULL,
	[Vlr_DscBonDup] [numeric](18, 4) NULL,
	[Vlr_BasDscTri] [numeric](18, 4) NULL,
	[Per_DscTri] [numeric](9, 4) NULL,
	[Vlr_BasVerba] [numeric](18, 4) NULL,
	[Prc_PolCom] [numeric](18, 8) NULL,
	[Per_DscPolCom] [numeric](18, 4) NULL,
	[Alq_IcmDif] [numeric](9, 4) NULL,
	[Vlr_IcmsDif] [numeric](18, 4) NULL,
	[Qtd_PesVolImpFat] [numeric](18, 4) NOT NULL,
	[Des_UnvPesVolImpFat] [varchar](3) NULL,
	[Prc_UniPesVolImpFat] [numeric](18, 8) NOT NULL,
	[Vlr_IcmsDeson] [numeric](18, 4) NULL,
	[Cod_MtvIcmsDeson] [varchar](2) NULL,
	[Vlr_DscCalSuframa] [numeric](18, 4) NULL,
	[Alq_FcpIcm] [numeric](18, 4) NULL,
	[Vlr_FcpIcm] [numeric](18, 4) NULL,
	[Alq_FcpSbt] [numeric](18, 4) NULL,
	[Vlr_FcpSbt] [numeric](18, 4) NULL,
	[Alq_FcpSbtRet] [numeric](18, 4) NULL,
	[Vlr_FcpSbtRet] [numeric](18, 4) NULL,
	[Alq_FcpSbtRec] [numeric](18, 4) NULL,
	[Vlr_FcpSbtRec] [numeric](18, 4) NULL,
	[vBCSTRet] [numeric](18, 4) NULL,
	[pST] [numeric](8, 4) NULL,
	[vICMSSubstituto] [numeric](18, 4) NULL,
	[vICMSSTRet] [numeric](18, 4) NULL,
	[vBCFCPSTRet] [numeric](18, 4) NULL,
	[pFCPSTRet] [numeric](8, 4) NULL,
	[vFCPSTRet] [numeric](18, 4) NULL,
	[pRedBCEfet] [numeric](8, 4) NULL,
	[vBCEfet] [numeric](18, 4) NULL,
	[pICMSEfet] [numeric](8, 4) NULL,
	[vICMSEfet] [numeric](18, 4) NULL,
	[Per_IcmDiferi] [numeric](8, 4) NULL,
	[Vlr_IcmDiferi] [numeric](18, 4) NULL,
	[Vlr_DspDevST] [numeric](18, 4) NULL,
	[cBenef] [varchar](10) NULL,
	[Vlr_PisEstDev] [numeric](18, 4) NULL,
	[Vlr_CofEstDev] [numeric](18, 4) NULL,
	[Per_LucLiq] [numeric](18, 4) NULL,
	[Per_LucBru] [numeric](18, 4) NULL,
	[Vlr_VrbOpe] [numeric](18, 4) NULL,
	[Alq_EfeDas] [numeric](7, 4) NULL,
	[Cod_CtlSldVrb] [varchar](1) NULL,
	[Vlr_PrcBasDevRecSbt] [numeric](18, 4) NULL,
	[Alq_AgrDebDevRecSbt] [numeric](7, 4) NULL,
	[Per_RedBasCalIcmDebDevRecSbt] [numeric](7, 4) NULL,
	[Alq_IcmDebDevRecSbt] [numeric](7, 4) NULL,
	[Vlr_BasDevRecSbt] [numeric](18, 4) NULL,
	[Vlr_DevRecSbt] [numeric](18, 4) NULL,
	[Prc_PonFin] [numeric](18, 4) NULL,
	[Cod_EnqIpi] [varchar](3) NULL,
	[Cod_OriMer] [varchar](3) NULL,
	[Cod_LotPdv] [varchar](20) NULL,
	[Qtd_PesLiq] [numeric](18, 4) NULL,
	[Prc_UniSemAcrIcm] [numeric](18, 8) NULL,
	[Prc_UniComAcrIcm] [numeric](18, 8) NULL,
	[Per_RepIcms] [numeric](7, 4) NULL,
	[Flg_PrcUniAcrIcm] [bit] NULL,
	[Vlr_BasIrf] [numeric](18, 4) NULL,
	[Alq_Irf] [numeric](18, 4) NULL,
	[Vlr_Irf] [numeric](18, 4) NULL,
	[Vlr_SbtRetAnt] [numeric](18, 4) NULL,
	[Vlr_Bonificacao] [numeric](18, 4) NULL,
	[Vlr_BasCsl] [numeric](18, 4) NULL,
	[Alq_Csl] [numeric](7, 4) NULL,
	[Vlr_Csl] [numeric](18, 4) NULL,
	[Flg_TrbFedDedTit] [bit] NULL)