USE [PROD_2023]
GO

/****** Object:  Table [dbo].[R_NFSCB]    Script Date: 28/06/2024 13:04:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_NFSCB](
	[Cod_Estabe] [int] NOT NULL,
	[Ser_Nota] [varchar](3) NOT NULL,
	[Num_Nota] [int] NOT NULL,
	[Esp_Nota] [varchar](3) NULL,
	[Status] [char](1) NULL,
	[Tip_Saida] [char](1) NULL,
	[Tip_Vencimento] [char](1) NULL,
	[Cod_OrigemNfs] [varchar](2) NULL,
	[Qtd_PagNF] [int] NULL,
	[Ser_Selo] [varchar](2) NULL,
	[Num_Selo] [bigint] NULL,
	[Num_Formulario] [int] NULL,
	[Dat_Emissao] [smalldatetime] NULL,
	[Dat_Cancelamento] [smalldatetime] NULL,
	[Cod_Cliente] [int] NULL,
	[Cod_Funcionario] [int] NULL,
	[Cod_Fornecedor] [int] NULL,
	[Consumidor] [varchar](45) NULL,
	[Qtd_PrzMed] [numeric](18, 4) NULL,
	[Qtd_Parcela] [int] NULL,
	[Cod_Cfo1] [int] NULL,
	[Per_Faturado] [int] NULL,
	[Cod_Pedido] [int] NULL,
	[Cod_VendTlmkt] [int] NULL,
	[Cod_Vendedor] [int] NULL,
	[Cod_Transportadora] [int] NULL,
	[Cod_Agente] [int] NULL,
	[Tip_Consumidor] [char](1) NULL,
	[Tip_RetImp] [char](1) NULL,
	[Vlr_BasPar] [numeric](18, 4) NULL,
	[Vlr_BasDscCom] [numeric](18, 4) NULL,
	[Vlr_LiqItens] [numeric](18, 4) NULL,
	[VlrBruItens] [numeric](18, 4) NULL,
	[Vlr_RepIcms] [numeric](18, 4) NULL,
	[Vlr_SubsTrib] [numeric](18, 4) NULL,
	[Per_DescontoCom] [numeric](18, 8) NULL,
	[Per_DescontoFin] [numeric](18, 8) NULL,
	[Vlr_DescontoCom] [numeric](18, 4) NULL,
	[Vlr_DscTri] [numeric](18, 4) NULL,
	[Vlr_TotalNota] [numeric](18, 4) NULL,
	[Vlr_BasIcmsNor] [numeric](18, 4) NULL,
	[Vlr_IcmsNor] [numeric](18, 4) NULL,
	[Vlr_BasIcmsTri] [numeric](18, 4) NULL,
	[Vlr_IcmsTri] [numeric](18, 4) NULL,
	[Vlr_BasRepIcms] [numeric](18, 4) NULL,
	[Vlr_PrdSubTri] [numeric](18, 4) NULL,
	[Vlr_BasSubsTrib] [numeric](18, 4) NULL,
	[Vlr_Ipi] [numeric](18, 4) NULL,
	[Vlr_Isento] [numeric](18, 4) NULL,
	[Cod_VlrFiscal] [char](1) NULL,
	[Flg_IcmsSobreTotal] [bit] NULL,
	[Qtd_Peso] [numeric](18, 4) NULL,
	[Qtd_Volumes] [int] NULL,
	[Qtd_Itens] [int] NULL,
	[Flg_ComisNormal] [bit] NULL,
	[Flg_MovEst] [bit] NULL,
	[Vlr_ComPag] [numeric](18, 4) NULL,
	[Vlr_ComPagTlmkt] [numeric](18, 4) NULL,
	[Per_ComVnd] [numeric](18, 8) NULL,
	[Vlr_ComTlmkt] [numeric](18, 4) NULL,
	[Vlr_Comissao] [numeric](18, 4) NULL,
	[Num_NotSubFat] [int] NULL,
	[Cgc] [varchar](14) NULL,
	[Cgf] [varchar](15) NULL,
	[Endereco] [varchar](50) NULL,
	[Bairro] [varchar](20) NULL,
	[Cep] [varchar](8) NULL,
	[Cidade] [varchar](25) NULL,
	[Estado] [varchar](2) NULL,
	[Cod_Cidade] [int] NULL,
	[Cod_MacroReg] [int] NULL,
	[Cod_MicroReg] [int] NULL,
	[Observacao] [varchar](80) NULL,
	[Usuario] [varchar](15) NULL,
	[Transacao] [smalldatetime] NULL,
	[Str_RelDoc] [varchar](42) NULL,
	[Tip_OutSai] [varchar](1) NULL,
	[Vlr_Outros] [numeric](18, 4) NULL,
	[Vlr_Seguro] [numeric](18, 4) NULL,
	[Vlr_OutDsp] [numeric](18, 4) NULL,
	[Tip_Frete] [char](1) NULL,
	[Vlr_Frete] [numeric](18, 4) NULL,
	[Vlr_BasIpi] [numeric](18, 4) NULL,
	[Cod_Ope] [varchar](3) NULL,
	[Tip_DocRel] [varchar](1) NULL,
	[Via_Transp] [varchar](1) NULL,
	[Flg_RetEnt] [bit] NULL,
	[Dat_RetEnt] [smalldatetime] NULL,
	[Val_ComTra] [numeric](18, 4) NULL,
	[Dat_FecCom] [smalldatetime] NULL,
	[Val_ComPagTra] [numeric](18, 4) NULL,
	[Dat_FecComEnt] [smalldatetime] NULL,
	[Cod_Digitador] [int] NULL,
	[Obs_Rodape] [text] NULL,
	[Obs_Corpo] [text] NULL,
	[Per_DscFinLiq] [numeric](18, 4) NULL,
	[Flg_WMS] [bit] NULL,
	[Cod_CidIbge] [varchar](7) NULL,
	[Cod_ModImpDanfe] [char](2) NULL,
	[Cod_FinEmi] [char](1) NULL,
	[Cod_ModDoc] [char](2) NULL,
	[Cod_ModEmiNfe] [char](1) NULL,
	[Id_Lote] [int] NULL,
	[Chv_Acesso] [varchar](44) NULL,
	[Arquivo] [ntext] NULL,
	[Dat_Proc] [datetime] NULL,
	[Num_Protoc] [bigint] NULL,
	[Num_DigValue] [varchar](28) NULL,
	[Cod_StaResp] [smallint] NULL,
	[Des_Motivo] [varchar](255) NULL,
	[Ret_DhRecbto] [datetime] NULL,
	[Ret_NProt] [varchar](15) NULL,
	[Ret_DigVal] [varchar](28) NULL,
	[Ret_CStat] [smallint] NULL,
	[Ret_XMotivo] [varchar](255) NULL,
	[Tam_Xml] [bigint] NULL,
	[Cod_StaNfe] [char](1) NULL,
	[Dat_Saida] [smalldatetime] NULL,
	[Flg_Email] [bit] NULL,
	[Flg_CST_Pis_ST] [bit] NULL,
	[Flg_CST_Cof_ST] [bit] NULL,
	[Vlr_Pis] [numeric](18, 4) NULL,
	[Vlr_Cofins] [numeric](18, 4) NULL,
	[Flg_Storage] [bit] NULL,
	[Vlr_BasRecSbt] [numeric](18, 4) NULL,
	[Vlr_RecSbt] [numeric](18, 4) NULL,
	[Ide_NotEmp] [varchar](20) NULL,
	[Ide_PedCmp] [varchar](40) NULL,
	[Ide_Contra] [varchar](40) NULL,
	[Qtd_PesBru] [numeric](18, 4) NULL,
	[Vlr_SubsTribEmb] [numeric](18, 4) NULL,
	[Cod_PlaVei] [varchar](10) NULL,
	[Id_PolCom] [int] NULL,
	[Flg_BlqImpVol] [bit] NULL,
	[Des_JusCan] [varchar](255) NULL,
	[Vlr_Verba] [numeric](18, 4) NULL,
	[Cod_FinNfe] [char](1) NULL,
	[UF_PlaVei] [varchar](2) NULL,
	[Vlr_BasRecSbtInt] [numeric](18, 8) NULL,
	[Vlr_RecSbtInt] [numeric](18, 8) NULL,
	[Cod_EndFon] [varchar](20) NULL,
	[Tip_EntSai] [varchar](1) NULL,
	[Tip_Entreg] [varchar](1) NULL,
	[Tip_DevEcf] [varchar](1) NULL,
	[Nom_UsuEsp] [varchar](15) NULL,
	[Num_CarFid] [varchar](25) NULL,
	[Num_Caixa] [smallint] NULL,
	[Num_Turno] [smallint] NULL,
	[Cod_ForPag] [int] NULL,
	[Cod_EntDom] [int] NULL,
	[Cod_Operad] [int] NULL,
	[Cod_Orcame] [int] NULL,
	[Num_Docume] [int] NULL,
	[Cod_MovDev] [int] NULL,
	[Cod_Entreg] [int] NULL,
	[Num_IsnNfs] [int] NULL,
	[Val_Subsid] [numeric](18, 4) NULL,
	[Val_Troca] [numeric](18, 4) NULL,
	[Dat_Retorn] [smalldatetime] NULL,
	[Flg_Retorn] [bit] NULL,
	[Flg_Estorn] [bit] NULL,
	[Flg_Altera] [bit] NULL,
	[Cod_RegTri] [smallint] NULL,
	[Ser_NotSubFat] [varchar](3) NULL,
	[Per_ComOpe] [numeric](18, 8) NULL,
	[Flg_RepNfePrc] [bit] NOT NULL,
	[cMsg] [int] NULL,
	[xMsg] [varchar](1200) NULL,
	[Cod_Contrato] [int] NULL,
	[Num_SequenciaCtr] [int] NULL,
	[Vlr_FrePrv] [numeric](18, 4) NULL,
	[Flg_ExpBomPrc] [bit] NULL,
	[Vlr_BasSbtRes] [numeric](18, 4) NULL,
	[Vlr_SbtRes] [numeric](18, 4) NULL,
	[Per_FrePrv] [numeric](18, 4) NULL,
	[Cod_Gerencia] [int] NULL,
	[Per_ComGer] [numeric](18, 4) NULL,
	[Vlr_ComGer] [numeric](18, 4) NULL,
	[Vlr_ComPagGer] [numeric](18, 4) NULL,
	[Cod_Supervisor] [int] NULL,
	[Per_ComSup] [numeric](18, 4) NULL,
	[Vlr_ComSup] [numeric](18, 4) NULL,
	[Vlr_ComPagSup] [numeric](18, 4) NULL,
	[Cod_GerOpe] [int] NULL,
	[Per_ComGerOpe] [numeric](18, 4) NULL,
	[Vlr_ComGerOpe] [numeric](18, 4) NULL,
	[Vlr_ComPagGerOpe] [numeric](18, 4) NULL,
	[Cod_SupOpe] [int] NULL,
	[Per_ComSupOpe] [numeric](18, 4) NULL,
	[Vlr_ComSupOpe] [numeric](18, 4) NULL,
	[Vlr_ComPagSupOpe] [numeric](18, 4) NULL,
	[Vlr_VrbPar] [numeric](18, 4) NULL,
	[Vlr_VrbBon] [numeric](18, 4) NULL,
	[Des_LayoutPde] [varchar](25) NULL,
	[Des_Convenio] [varchar](30) NULL,
	[Cod_PrjPde] [varchar](12) NULL,
	[Id_Transacao] [int] NULL,
	[Vlr_DscBon] [numeric](18, 4) NULL,
	[Vlr_VrbVdr] [numeric](18, 4) NULL,
	[Vlr_VrbSup] [numeric](18, 4) NULL,
	[Ide_NumPregao] [varchar](20) NULL,
	[CodAnt] [int] NULL,
	[NovoCodigo] [int] NULL,
	[Num_SeqBal] [int] NULL,
	[Vlr_ResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Vlr_ResIcmSbtExtEN] [numeric](18, 4) NULL,
	[Cod_PedCliPde] [varchar](20) NULL,
	[Cod_DepMovEst] [smallint] NULL,
	[Cod_ZonMovEst] [smallint] NULL,
	[Xml_Cancelamento] [ntext] NULL,
	[Cod_DDD] [varchar](2) NULL,
	[Cod_LayoutPde] [int] NULL,
	[Vlr_IcmFcpDes] [numeric](18, 4) NULL,
	[Vlr_IcmParDes] [numeric](18, 4) NULL,
	[Vlr_IcmParRem] [numeric](18, 4) NULL,
	[Cod_Rota] [int] NULL,
	[Chv_AcessoRel] [varchar](44) NULL,
	[Vlr_DspExt] [numeric](18, 4) NULL,
	[Num_InscriSubTriEmiUfd] [varchar](15) NULL,
	[Cod_CtaPagGnr] [int] NULL,
	[Cod_RamAtv] [int] NULL,
	[Num_SerECF] [varchar](9) NULL,
	[Vlr_DscBonDup] [numeric](18, 4) NULL,
	[Sta_IntWms] [varchar](1) NULL,
	[Flg_CanPdv] [bit] NULL,
	[Vlr_IcmsDif] [numeric](18, 4) NULL,
	[Vlr_DebVrbVdr] [numeric](18, 4) NOT NULL,
	[Inscricao_Suframa] [varchar](9) NULL,
	[Vlr_IcmsDeson] [numeric](18, 4) NOT NULL,
	[Vlr_DscCalSuframa] [numeric](18, 4) NOT NULL,
	[Vlr_FcpIcm] [numeric](18, 4) NULL,
	[Vlr_FcpSbt] [numeric](18, 4) NULL,
	[Vlr_FcpSbtRet] [numeric](18, 4) NULL,
	[Vlr_FcpSbtRec] [numeric](18, 4) NULL,
	[Flg_CalTrbDevCfg] [bit] NULL,
	[Seq_cNF] [bigint] NULL,
	[Vlr_DspDevST] [numeric](18, 4) NULL,
	[Flg_Importado] [bit] NOT NULL,
	[Tip_GerVrb] [varchar](1) NULL,
	[Per_LucLiq] [numeric](18, 4) NULL,
	[Per_LucBru] [numeric](18, 4) NULL,
	[Vlr_VrbOpe] [numeric](18, 4) NULL,
	[Flg_ImportadorNfe] [bit] NULL,
	[Flg_PrcUniAcrIcm] [bit] NULL,
	[Id_Consig] [int] NULL,
	[Num_SeqDev] [smallint] NULL,
	[Vlr_BasDevRecSbt] [numeric](18, 4) NULL,
	[Vlr_DevRecSbt] [numeric](18, 4) NULL,
	[Chv_NotOri] [varchar](44) NULL,
	[Flg_EnvTra] [bit] NULL,
	[Id_Pais] [smallint] NULL,
	[Flg_IncIpiBasCalPis] [bit] NULL,
	[Flg_IncIpiBasCalIcm] [bit] NULL,
	[Flg_BlqCalAutTrb] [bit] NULL,
	[Cod_OriDesNfs] [varchar](1) NULL,
	[Id_OpeVdo] [int] NULL,
	[Vlr_BasIrf] [numeric](18, 4) NULL,
	[Vlr_Irf] [numeric](18, 4) NULL,
	[Flg_BlqTrfEstFis] [bit] NULL,
	[Nom_UsuFat] [varchar](15) NULL,
	[Vlr_BasCsl] [numeric](18, 4) NULL,
	[Vlr_Csl] [numeric](18, 4) NULL)