USE [PROD_2023]
GO

/****** Object:  Table [dbo].[R_NFEIT]    Script Date: 28/06/2024 08:50:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_NFEIT](
	[Protocolo] [int] NOT NULL,
	[Cod_Produto] [int] NOT NULL,
	[Cod_Lote] [varchar](20) NOT NULL,
	[Num_SeqIte] [smallint] NOT NULL,
	[Dat_Movimento] [smalldatetime] NULL,
	[Dat_Vencim] [smalldatetime] NULL,
	[Qtd_Pedido] [int] NULL,
	[Qtd_Bonificacao] [int] NULL,
	[Qtd_PedFat] [int] NULL,
	[Qtd_BonFat] [int] NULL,
	[Flg_ComisNormal] [bit] NULL,
	[Prc_UniFat] [numeric](18, 8) NULL,
	[Prc_Unitario] [numeric](18, 8) NULL,
	[Per_DescItem] [numeric](18, 8) NULL,
	[Ctrl_Tributacao] [char](2) NULL,
	[Cod_ClaTri] [varchar](4) NULL,
	[Vlr_BasIcmsNor] [numeric](18, 4) NULL,
	[Alq_Icms] [numeric](18, 8) NULL,
	[Vlr_IcmsNor] [numeric](18, 4) NULL,
	[Vlr_Ipi] [numeric](18, 4) NULL,
	[Vlr_IcmsTrib] [numeric](18, 4) NULL,
	[Vlr_SubsTrib] [numeric](18, 4) NULL,
	[Vlr_AntRec] [numeric](18, 4) NULL,
	[Vlr_DespRateada] [numeric](18, 4) NULL,
	[Vlr_DescRateado] [numeric](18, 4) NULL,
	[Vlr_BasIpi] [numeric](18, 4) NULL,
	[Vlr_BasIcmsTrib] [numeric](18, 4) NULL,
	[Vlr_PrdSubTri] [numeric](18, 4) NULL,
	[Vlr_BasSubsTrib] [numeric](18, 4) NULL,
	[Vlr_PrdAntRec] [numeric](18, 4) NULL,
	[Vlr_BasAntRec] [numeric](18, 4) NULL,
	[Vlr_Isento] [numeric](18, 4) NULL,
	[Vlr_LiqIte] [numeric](18, 4) NULL,
	[Vlr_Comissao] [numeric](18, 4) NULL,
	[Vlr_ComTlmkt] [numeric](18, 4) NULL,
	[Cus_LiqUni] [numeric](18, 4) NULL,
	[Prc_CustoMedio] [numeric](18, 4) NULL,
	[Prc_Venda] [numeric](18, 4) NULL,
	[FATOR_FAT] [int] NULL,
	[Cod_Cfo] [smallint] NULL,
	[Vlr_BasDifTri] [numeric](18, 4) NULL,
	[Vlr_DifTri] [numeric](18, 4) NULL,
	[Vlr_Outros] [numeric](18, 4) NULL,
	[Vlr_BasRepIcm] [numeric](18, 4) NULL,
	[Vlr_RepIcm] [numeric](18, 4) NULL,
	[Vlr_Frete] [numeric](18, 4) NULL,
	[Flg_PrcVen] [bit] NULL,
	[Per_Markup] [numeric](18, 8) NULL,
	[Val_PrcVen] [numeric](18, 4) NULL,
	[Flg_DbqPrdBlq] [bit] NULL,
	[Prc_MaxCon] [numeric](18, 4) NULL,
	[Prc_Fabric] [numeric](18, 4) NULL,
	[Num_SeqDig] [int] NULL,
	[Qtd_Promocao] [int] NULL,
	[Transacao] [smalldatetime] NULL,
	[Qtd_EmbFec] [int] NULL,
	[Vlr_DspExtNotFis] [numeric](18, 4) NULL,
	[Vlr_DscExtNotFis] [numeric](18, 4) NULL,
	[Qtd_FisAnt] [int] NULL,
	[Prc_CusMedAnt] [numeric](18, 4) NULL,
	[Per_RedBasCalIcmDeb] [numeric](18, 4) NULL,
	[Alq_AgrDeb] [numeric](18, 4) NULL,
	[Per_RedBasCalDeb] [numeric](18, 4) NULL,
	[Alq_IcmDeb] [numeric](18, 4) NULL,
	[Vlr_DebIcm] [numeric](18, 4) NULL,
	[Per_RedBasCalIcmCre] [numeric](18, 4) NULL,
	[Per_LimBasCalCreSbt] [numeric](18, 4) NULL,
	[Vlr_LimCreIcm] [numeric](18, 4) NULL,
	[Cod_ModBasCalIcm] [char](1) NULL,
	[Cod_ModBasCalIcmSbt] [char](1) NULL,
	[Dat_Fabric] [smalldatetime] NULL,
	[Vlr_BasTri] [numeric](18, 8) NULL,
	[Per_RedBasCalIcm] [numeric](18, 4) NULL,
	[Per_RedBasCalIcmSbt] [numeric](18, 4) NULL,
	[Alq_IcmSbt] [numeric](18, 4) NULL,
	[Alq_AgrSbt] [numeric](18, 4) NULL,
	[Vlr_Seguro] [numeric](18, 4) NULL,
	[Vlr_BasPis] [numeric](18, 4) NULL,
	[Alq_Pis] [numeric](18, 4) NULL,
	[Vlr_Pis] [numeric](18, 4) NULL,
	[Vlr_BasCofins] [numeric](18, 4) NULL,
	[Alq_Cofins] [numeric](18, 4) NULL,
	[Vlr_Cofins] [numeric](18, 4) NULL,
	[CST_Pis] [varchar](2) NULL,
	[CST_Cofins] [varchar](2) NULL,
	[Tip_LisPis] [char](1) NULL,
	[Alq_Ipi] [numeric](18, 4) NULL,
	[CST_Ipi] [varchar](2) NULL,
	[Vlr_Verba] [numeric](18, 4) NULL,
	[Vlr_PrcBasRecSbt] [numeric](18, 8) NULL,
	[Alq_AgrDebRecSbt] [numeric](18, 4) NULL,
	[Per_RedBasCalIcmDebRecSbt] [numeric](18, 4) NULL,
	[Alq_IcmDebRecSbt] [numeric](18, 4) NULL,
	[Flg_RegEspTrb] [bit] NULL,
	[Cod_Tribut] [varchar](3) NULL,
	[Vlr_DspSbt] [numeric](18, 4) NULL,
	[Vlr_BasSbtRes] [numeric](18, 4) NULL,
	[Vlr_SbtRes] [numeric](18, 4) NULL,
	[Per_IpiCad] [numeric](18, 4) NULL,
	[Vlr_Suframa] [numeric](18, 4) NULL,
	[Flg_UsaCreIcmSbt] [bit] NULL,
	[Cod_Estabe] [int] NOT NULL,
	[Prc_Unitar] [numeric](18, 8) NULL,
	[Prc_RefFpb] [numeric](18, 4) NULL,
	[Cod_CSOSN] [varchar](3) NULL,
	[Vlr_PrcBasDevRecSbt] [numeric](18, 4) NULL,
	[Alq_AgrDebDevRecSbt] [numeric](18, 4) NULL,
	[Per_RedBasCalIcmDebDevRecSbt] [numeric](18, 4) NULL,
	[Alq_IcmDebDevRecSbt] [numeric](18, 4) NULL,
	[Vlr_BasDevRecSbt] [numeric](18, 4) NULL,
	[Vlr_DevRecSbt] [numeric](18, 4) NULL,
	[Vlr_DscIte1] [numeric](18, 4) NULL,
	[Vlr_DscIte2] [numeric](18, 4) NULL,
	[Vlr_BruItem] [numeric](18, 4) NULL,
	[Vlr_TotItem] [numeric](18, 4) NULL,
	[Vlr_DescItem] [numeric](18, 4) NULL,
	[Vlr_LiqCmpIte] [numeric](18, 4) NULL,
	[Vlr_CrePreIcmSbtExt] [numeric](18, 4) NULL,
	[Vlr_ResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Vlr_ResIcmSbtExtEN] [numeric](18, 4) NULL,
	[Tip_PrcBasDebSbt] [varchar](1) NULL,
	[Tip_PrcBasCreSbt] [varchar](1) NULL,
	[Vlr_BasCrePreIcmSbtExt] [numeric](18, 4) NULL,
	[Alq_CrePreIcmSbtExt] [numeric](18, 4) NULL,
	[Vlr_BasResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Alq_ResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Vlr_BasResIcmSbtExtEN] [numeric](18, 4) NULL,
	[Alq_ResIcmSbtExtEN] [numeric](18, 4) NULL,
	[Alq_MvaResIcmSbtIntSN] [numeric](18, 4) NULL,
	[Flg_BlqDsc] [bit] NULL,
	[Num_NfePrcBasRecSbt] [int] NULL,
	[Cod_Ncm] [varchar](8) NULL,
	[Per_AcrAlqIntFcp] [numeric](18, 4) NULL,
	[Per_PrvParIcm] [numeric](18, 4) NULL,
	[Vlr_IcmFcpDes] [numeric](18, 4) NULL,
	[Vlr_IcmParDes] [numeric](18, 4) NULL,
	[Vlr_IcmParRem] [numeric](18, 4) NULL,
	[Per_ResExt] [numeric](18, 4) NULL,
	[Vlr_BasDspExt] [numeric](18, 4) NULL,
	[Vlr_DspExt] [numeric](18, 4) NULL,
	[Cod_CEST] [varchar](7) NULL,
	[Alq_IntIcmDes] [numeric](18, 4) NULL,
	[Vlr_DspCusEnt] [numeric](18, 4) NULL,
	[Vlr_BasCalSubTriEntMedAnt] [numeric](18, 4) NULL,
	[Alq_IcmPresum] [numeric](18, 4) NULL,
	[Flg_UsaCrePresum] [bit] NULL,
	[Qtd_Avaria] [int] NULL,
	[Tip_Ent] [varchar](1) NULL,
	[Dat_RefPrdCip] [datetime] NULL,
	[Per_DscNegFor] [numeric](18, 4) NULL,
	[Alq_IcmDif] [numeric](9, 4) NULL,
	[Vlr_IcmsDif] [numeric](18, 4) NULL,
	[Vlr_IcmsDeson] [numeric](18, 4) NOT NULL,
	[Cod_MtvIcmsDeson] [varchar](2) NULL,
	[Vlr_DscCalSuframa] [numeric](18, 4) NOT NULL,
	[Alq_FcpIcm] [numeric](18, 4) NULL,
	[Vlr_FcpIcm] [numeric](18, 4) NULL,
	[Alq_FcpSbt] [numeric](18, 4) NULL,
	[Vlr_FcpSbt] [numeric](18, 4) NULL,
	[Alq_FcpSbtRet] [numeric](18, 4) NULL,
	[Vlr_FcpSbtRet] [numeric](18, 4) NULL,
	[Alq_FcpSbtRec] [numeric](18, 4) NULL,
	[Vlr_FcpSbtRec] [numeric](18, 4) NULL,
	[Alq_FcpSbtAnt] [numeric](18, 4) NULL,
	[Vlr_FcpSbtAnt] [numeric](18, 4) NULL,
	[Per_IcmDiferi] [numeric](8, 4) NULL,
	[Vlr_IcmDiferi] [numeric](18, 4) NULL,
	[Xml_vBCSTRet] [numeric](18, 4) NULL,
	[Xml_pST] [numeric](8, 4) NULL,
	[Xml_vICMSSubstituto] [numeric](18, 4) NULL,
	[Xml_vICMSSTRet] [numeric](18, 4) NULL,
	[Xml_vBCFCPSTRet] [numeric](18, 4) NULL,
	[Xml_pFCPSTRet] [numeric](8, 4) NULL,
	[Xml_vFCPSTRet] [numeric](18, 4) NULL,
	[Xml_pRedBCEfet] [numeric](8, 4) NULL,
	[Xml_vBCEfet] [numeric](18, 4) NULL,
	[Xml_pICMSEfet] [numeric](8, 4) NULL,
	[Xml_vICMSEfet] [numeric](18, 4) NULL,
	[Vlr_DspDevST] [numeric](18, 4) NULL,
	[cBenef] [varchar](10) NULL,
	[Vlr_PisEstDev] [numeric](18, 4) NULL,
	[Vlr_CofEstDev] [numeric](18, 4) NULL,
	[Vlr_DscTri] [numeric](18, 4) NULL,
	[Vlr_VrbVdr] [numeric](18, 4) NULL,
	[Vlr_VrbOpe] [numeric](18, 4) NULL,
	[Vlr_VrbSup] [numeric](18, 4) NULL,
	[Qtd_Faltas] [int] NULL,
	[Vlr_FreCte] [numeric](18, 4) NULL,
	[Vlr_IcmRetXml] [numeric](18, 4) NULL,
	[Vlr_BasIcmRetXml] [numeric](18, 4) NULL,
	[Prc_PonFin] [numeric](18, 4) NULL,
	[Cod_EnqIpi] [varchar](3) NULL,
	[Cod_OriMer] [varchar](3) NULL,
	[Qtd_PesLiq] [numeric](18, 4) NULL,
	[Per_RepIcm] [numeric](7, 4) NULL,
	[Vlr_ComSup] [numeric](18, 4) NULL,
	[Vlr_ComSupOpe] [numeric](18, 4) NULL,
	[Vlr_ComGer] [numeric](18, 4) NULL,
	[Vlr_ComGerOpe] [numeric](18, 4) NULL,
	[Id_DclImp] [int] NULL,
	[Imp_nAdicao] [smallint] NULL,
	[Imp_nSeqAdic] [smallint] NULL,
	[Imp_vBCII] [numeric](18, 4) NULL,
	[Imp_vDespAdu] [numeric](18, 4) NULL,
	[Imp_vII] [numeric](18, 4) NULL,
	[Imp_vIOF] [numeric](18, 4) NULL,
	[Imp_vMLE] [numeric](18, 4) NULL,
	[Imp_vFrete] [numeric](18, 4) NULL,
	[Imp_vSeguro] [numeric](18, 4) NULL,
	[Imp_vMLD] [numeric](18, 4) NULL,
	[Imp_vSiscomex] [numeric](18, 4) NULL,
	[Imp_vAFRMM] [numeric](18, 4) NULL,
	[Imp_vDirAntiDump] [numeric](18, 4) NULL,
	[Imp_vOutDsp] [numeric](18, 4) NULL,
	[Imp_vTotDespes] [numeric](18, 4) NULL,
	[Vlr_Bonificacao] [numeric](18, 4) NULL,
	[Vlr_DscBonRat] [numeric](18, 4) NULL)