USE [PROD_2023]
GO

/****** Object:  Table [dbo].[R_POCOM]    Script Date: 28/06/2024 10:57:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_POCOM](
	[Id_PolCom] [int] NOT NULL,
	[Cod_PolCom] [varchar](25) NOT NULL,
	[Des_Detalhada] [varchar](120) NULL,
	[Dat_Inicio] [smalldatetime] NULL,
	[Dat_Termino] [smalldatetime] NULL,
	[Bloqueado] [bit] NULL,
	[Qtd_Minimo] [smallint] NULL,
	[Vlr_Minimo] [numeric](18, 4) NULL,
	[Per_Desconto] [numeric](18, 4) NULL,
	[Qtd_PrzMax] [smallint] NULL,
	[Cod_TipPrz] [char](1) NULL,
	[Cod_TabPrc] [int] NULL,
	[Cod_TabPrz] [int] NULL,
	[Cod_TabComVdr] [int] NULL,
	[Cod_TabComOpe] [int] NULL,
	[Usuario] [varchar](35) NULL,
	[Transacao] [smalldatetime] NULL,
	[Flg_Televendas] [bit] NULL,
	[Flg_Cfv] [bit] NULL,
	[Flg_PedEle] [bit] NULL,
	[Flg_Web] [bit] NULL,
	[Qtd_IteMin] [int] NULL,
	[Per_DscCom] [numeric](18, 4) NULL,
	[Per_DscFin] [numeric](18, 4) NULL,
	[Per_RedComVdr] [numeric](18, 4) NULL,
	[Per_RedComOpe] [numeric](18, 4) NULL,
	[Flg_NegDsc] [bit] NULL,
	[Flg_BlqCli] [bit] NULL,
	[Flg_Balcao] [bit] NULL,
	[Flg_ExcCla] [bit] NULL,
	[Flg_ExcFab] [bit] NULL,
	[Flg_NaoSugDscItePdv] [bit] NULL,
	[Dat_Cadastro] [smalldatetime] NULL,
	[Per_DscAutPrc] [numeric](18, 4) NULL,
	[Per_AcrAutPrc] [numeric](18, 4) NULL,
	[Flg_PrcVenPrpPrz] [bit] NULL,
	[Per_CorPrcVenPrpPrz] [numeric](18, 4) NULL,
	[Flg_BlqVerba] [bit] NULL,
	[Flg_BlqPolDifItePdv] [bit] NULL,
	[Flg_BlqPolDifCabPdv] [bit] NULL,
	[Flg_MarkupCusCom] [bit] NULL,
	[Tip_RatBon] [varchar](1) NULL,
	[Per_DscComVis] [numeric](18, 4) NULL,
	[Per_DscFinVis] [numeric](18, 4) NULL,
	[Flg_SugDscGlbPdv] [bit] NULL,
	[Tip_PolCom] [varchar](4) NULL,
	[Flg_DbqUsoVrbPdv] [bit] NULL,
	[Flg_GerVrbPdv] [bit] NULL,
	[Tip_VrbPdv] [varchar](1) NULL,
	[Flg_SugPrzCli] [bit] NULL,
	[Controle_Saldo] [varchar](1) NULL,
	[Flg_AcuVrbPos] [bit] NULL,
	[Flg_AcuVrbNeg] [bit] NULL,
	[Flg_CtrPdvVrbVdr] [bit] NULL,
	[Flg_CtrPdvVrbOpe] [bit] NULL,
	[Per_ComAtvVdr] [numeric](18, 4) NULL,
	[Per_ComPasVdr] [numeric](18, 4) NULL,
	[Per_ComAtvOpe] [numeric](18, 4) NULL,
	[Per_ComPasOpe] [numeric](18, 4) NULL,
	[Obs_PolCom] [text] NULL,
	[Flg_UsaTabPrcCadCli] [bit] NULL,
	[Dat_Criacao] [datetime] NULL,
	[Cod_TipComiss] [varchar](1) NULL,
	[Per_ComVdr] [numeric](7, 4) NULL,
	[Per_ComOpe] [numeric](7, 4) NULL,
	[Flg_BlqCriPrcMin] [bit] NULL,
	[Flg_CriPrcMin] [bit] NULL)