USE BD_DW
GO

/****** Object:  Table [dbo].[R_PRODU]    Script Date: 28/06/2024 08:54:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_PRODU](
	[Codigo] [int] NOT NULL,
	[Descricao] [varchar](80) NULL,
	[Des_Resumi] [varchar](24) NULL,
	[Ref_Fabricante] [varchar](15) NULL,
	[Cod_EAN] [varchar](13) NULL,
	[Peso] [numeric](18, 8) NULL,
	[Unidade_Venda] [varchar](3) NULL,
	[Qtd_Embalagem] [int] NULL,
	[Cod_AbcFar] [int] NULL,
	[Validade] [int] NULL,
	[Cod_PrdExt] [varchar](13) NULL,
	[Localizacao] [varchar](8) NULL,
	[Dat_Cadastro] [smalldatetime] NULL,
	[Dat_UltVenda] [smalldatetime] NULL,
	[Cod_Fabricante] [int] NULL,
	[Cod_Divisao] [int] NULL,
	[Cod_Classif] [varchar](7) NULL,
	[Cod_SubBas] [int] NULL,
	[Sta_AbcValFat] [char](1) NULL,
	[Sta_AbcUniVen] [char](1) NULL,
	[Per_ParticFat] [numeric](18, 8) NULL,
	[Flag_ImprClassif1] [char](1) NULL,
	[Ctrl_Preco] [char](1) NULL,
	[Ctrl_Venda] [char](1) NULL,
	[Cod_GrpPrc] [char](1) NULL,
	[Tip_Por344] [varchar](2) NULL,
	[Tip_LisPis] [char](1) NULL,
	[Cod_ClaFis] [varchar](20) NULL,
	[Prc_Tabela] [numeric](18, 4) NULL,
	[Prc_CusLiqPla] [numeric](18, 4) NULL,
	[Prc_Pmz] [numeric](18, 4) NULL,
	[Cod_Promocao] [int] NULL,
	[Cod_PlaRegTri] [int] NULL,
	[Per_PlaRedCreIcm] [numeric](18, 8) NULL,
	[Per_PlaRepIcm] [numeric](18, 8) NULL,
	[Per_PlaCreIcm] [numeric](18, 8) NULL,
	[Per_PlaDebIcm] [numeric](18, 8) NULL,
	[Per_PlaRebate] [numeric](18, 8) NULL,
	[Per_PlaAgrega] [numeric](18, 8) NULL,
	[Per_PlaDesc1] [numeric](18, 8) NULL,
	[Per_PlaDesc2] [numeric](18, 8) NULL,
	[Per_PlaBonific] [numeric](18, 8) NULL,
	[Flg_PlaFatPrcLiq] [bit] NULL,
	[Per_PlaIpi] [numeric](18, 8) NULL,
	[Per_PlaDesFin] [numeric](18, 8) NULL,
	[Per_PlaCusFre] [numeric](18, 8) NULL,
	[Per_PlaDesOpe] [numeric](18, 8) NULL,
	[Per_PlaDesFre] [numeric](18, 8) NULL,
	[Per_PlaDesCom] [numeric](18, 8) NULL,
	[Per_PlaDesPis] [numeric](18, 8) NULL,
	[Per_PlaDesCof] [numeric](18, 8) NULL,
	[Per_PlaDesIrpj] [numeric](18, 8) NULL,
	[Per_PlaDesConSoc] [numeric](18, 8) NULL,
	[Per_PlaDesIcms] [numeric](18, 8) NULL,
	[Per_PlaMarRes] [numeric](18, 8) NULL,
	[Per_PlaMarOpe] [numeric](18, 8) NULL,
	[Per_PlaMarFin] [numeric](18, 8) NULL,
	[Vlr_PlaPrcVen] [numeric](18, 4) NULL,
	[Dias_PlaFinanc] [int] NULL,
	[Taxa_PlaFinanc] [numeric](18, 8) NULL,
	[Des_PrdDet] [text] NULL,
	[Reg_MS] [varchar](20) NULL,
	[H_DatPrcAtu] [smalldatetime] NULL,
	[H_PrcVen] [numeric](18, 4) NULL,
	[H_PrcVen1] [numeric](18, 4) NULL,
	[H_PrcVen2] [numeric](18, 4) NULL,
	[H_PrcVen3] [numeric](18, 4) NULL,
	[H_DatPrcAnt] [smalldatetime] NULL,
	[H_PrcVen1Ant] [numeric](18, 4) NULL,
	[H_PrcVen2Ant] [numeric](18, 4) NULL,
	[H_PrcVen3Ant] [numeric](18, 4) NULL,
	[H_PrcTab] [numeric](18, 4) NULL,
	[H_PerRepIcm] [numeric](18, 8) NULL,
	[H_PerDsc1] [numeric](18, 8) NULL,
	[H_PerDsc2] [numeric](18, 8) NULL,
	[H_PerOutDsc] [numeric](18, 8) NULL,
	[H_PerCreIcm] [numeric](18, 8) NULL,
	[H_PerRedBasCalDeb] [numeric](18, 8) NULL,
	[H_PerAgrDebIcm] [numeric](18, 8) NULL,
	[H_PerDebIcm] [numeric](18, 8) NULL,
	[H_PerIpi] [numeric](18, 8) NULL,
	[H_PerFrete] [numeric](18, 8) NULL,
	[H_PerDspFin] [numeric](18, 8) NULL,
	[H_PerOutDsp] [numeric](18, 8) NULL,
	[H_PrcCusLiqEnt] [numeric](18, 4) NULL,
	[H_PerMrg1] [numeric](18, 8) NULL,
	[H_PerMrg2] [numeric](18, 8) NULL,
	[H_PerMrg3] [numeric](18, 8) NULL,
	[H_PerRedBasCalCre] [numeric](18, 8) NULL,
	[Dat_PrcUltBal] [smalldatetime] NULL,
	[Per_ComVnd] [numeric](18, 8) NULL,
	[Qtd_SldAntBal] [int] NULL,
	[Qtd_SldPosBal] [int] NULL,
	[Cod_SubBas2] [int] NULL,
	[Cod_SubBas3] [int] NULL,
	[Cod_SubBas4] [int] NULL,
	[Qtd_UndVen] [int] NULL,
	[Des_FormaFarmac] [varchar](12) NULL,
	[Des_NomGen] [varchar](30) NULL,
	[Des_UndVen] [varchar](12) NULL,
	[Usuario] [varchar](35) NULL,
	[Transacao] [smalldatetime] NULL,
	[Mrg_PrcVenConFin1] [numeric](18, 8) NULL,
	[Mrg_PrcVenConFin2] [numeric](18, 8) NULL,
	[Mrg_PrcVenConFin3] [numeric](18, 8) NULL,
	[Qtd_FraVen] [int] NULL,
	[Per_Markup] [numeric](18, 8) NULL,
	[Prc_FabAnt] [numeric](18, 4) NULL,
	[Dat_PrcFabAnt] [smalldatetime] NULL,
	[Prc_MaxConAnt] [numeric](18, 4) NULL,
	[Cod_CtrUsu] [varchar](3) NULL,
	[Des_PrdRef] [varchar](20) NULL,
	[Edi_Pra] [int] NULL,
	[Edi_Dep] [int] NULL,
	[Per_BonAutOrc] [numeric](18, 8) NULL,
	[Prc_Minimo] [int] NULL,
	[Descri] [varchar](64) NULL,
	[Aprese] [varchar](15) NULL,
	[Cod_RefPrati] [varchar](14) NULL,
	[Lrg_Emb] [numeric](6, 2) NULL,
	[Alt_Emb] [numeric](6, 2) NULL,
	[Prf_Emb] [numeric](6, 2) NULL,
	[Vol_Emb] [numeric](18, 4) NULL,
	[Flg_PolComercMax] [bit] NULL,
	[Flg_PrzComercMax] [bit] NULL,
	[Und_EmbCmp] [varchar](3) NULL,
	[Lrg_EmbCmp] [numeric](18, 4) NULL,
	[Alt_EmbCmp] [numeric](18, 4) NULL,
	[Prf_EmbCmp] [numeric](18, 4) NULL,
	[Pes_EmbCmp] [numeric](18, 4) NULL,
	[Qtd_EmbPalete] [int] NULL,
	[Qtd_CamPalete] [int] NULL,
	[Cod_EanEmbCmp] [varchar](14) NULL,
	[Flg_IncFis] [bit] NULL,
	[Tipo] [varchar](2) NULL,
	[Tip_Prd] [char](1) NULL,
	[Sub_TipPrd] [char](1) NULL,
	[Dat_VctRegMS] [smalldatetime] NULL,
	[Flg_Servic] [bit] NULL,
	[Flg_ExpWeb] [bit] NULL,
	[Des_NomImgWeb] [varchar](255) NULL,
	[Des_InfImgWeb] [varchar](255) NULL,
	[Per_Ipi] [numeric](18, 4) NULL,
	[Prc_RefFpb] [numeric](18, 4) NULL,
	[Prc_RefFpbAnt] [numeric](18, 4) NULL,
	[Dat_PrcRefFpb] [smalldatetime] NULL,
	[Dat_PrcRefFpbAnt] [smalldatetime] NULL,
	[Prc_Fabric12] [numeric](18, 4) NULL,
	[Prc_MaxCon12] [numeric](18, 4) NULL,
	[Prc_Fabric17] [numeric](18, 4) NULL,
	[Prc_MaxCon17] [numeric](18, 4) NULL,
	[Prc_Fabric18] [numeric](18, 4) NULL,
	[Prc_MaxCon18] [numeric](18, 4) NULL,
	[Prc_Fabric19] [numeric](18, 4) NULL,
	[Prc_MaxCon19] [numeric](18, 4) NULL,
	[CodAnt] [int] NULL,
	[NovoCodigo] [int] NULL,
	[Sta_AbcAcesso] [varchar](1) NULL,
	[Num_SeqBal] [int] NULL,
	[Qtd_SldPraAntBal] [int] NULL,
	[Qtd_SldPraPosBal] [int] NULL,
	[Cod_FCI] [varchar](36) NULL,
	[Per_FCI] [numeric](18, 4) NULL,
	[Cod_NcmExt] [varchar](3) NULL,
	[Flg_Generico] [bit] NULL,
	[Cod_GuiFar] [int] NULL,
	[Flg_PesoKg] [bit] NULL,
	[Cod_CEST] [varchar](7) NULL,
	[Prc_Fabric175] [numeric](18, 4) NULL,
	[Prc_MaxCon175] [numeric](18, 4) NULL,
	[Prc_Fabric20] [numeric](18, 4) NULL,
	[Prc_MaxCon20] [numeric](18, 4) NULL,
	[Des_MtvIseRegMS] [varchar](300) NULL,
	[Ref_Detalhe] [varchar](50) NULL,
	[Sta_AbcUniVenFab] [varchar](1) NULL,
	[Sta_AbcValFatFab] [varchar](1) NULL,
	[Flg_ImpEtqGon] [bit] NULL,
	[Cod_GrpDesPrd] [int] NULL,
	[Prc_Fabric21] [numeric](18, 4) NULL,
	[Prc_MaxCon21] [numeric](18, 4) NULL,
	[Prc_Fabric22] [numeric](18, 4) NULL,
	[Prc_MaxCon22] [numeric](18, 4) NULL,
	[Prc_Fabric195] [numeric](18, 4) NULL,
	[Prc_MaxCon195] [numeric](18, 4) NULL,
	[Prc_Fabric205] [numeric](18, 4) NULL,
	[Prc_MaxCon205] [numeric](18, 4) NULL)