USE [PROD_2023]
GO

/****** Object:  Table [dbo].[R_PRXES]    Script Date: 28/06/2024 08:53:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_PRXES](
	[Cod_Estabe] [int] NOT NULL,
	[Cod_Produt] [int] NOT NULL,
	[_Cod_LocFis] [varchar](20) NULL,
	[_Num_Rua] [smallint] NULL,
	[_Num_Col] [smallint] NULL,
	[_Num_Niv] [smallint] NULL,
	[_Num_Apt] [smallint] NULL,
	[Qtd_Transi] [int] NULL,
	[Qtd_Fisico] [int] NULL,
	[Qtd_Solici] [int] NULL,
	[Qtd_Avaria] [int] NULL,
	[Qtd_Reserv] [int] NULL,
	[Qtd_Dispon] [int] NULL,
	[Qtd_Quaren] [int] NULL,
	[Prc_Venda] [numeric](18, 8) NULL,
	[Dat_PrcAtual] [smalldatetime] NULL,
	[Prc_VenAnt] [numeric](18, 8) NULL,
	[Dat_PrcAnt] [smalldatetime] NULL,
	[Prc_CusLiqEnt] [numeric](18, 8) NULL,
	[Prc_CusLiqEntDep] [numeric](18, 8) NULL,
	[Prc_CusMed] [numeric](18, 8) NULL,
	[Prc_CusMedPra] [numeric](18, 8) NULL,
	[Prc_CusMedDep] [numeric](18, 8) NULL,
	[Prc_CusMedCom] [numeric](18, 8) NULL,
	[Prc_EntAnt] [numeric](18, 8) NULL,
	[Per_DscEntAnt] [numeric](7, 4) NULL,
	[Qtd_EntAnt] [int] NULL,
	[Dat_EntAnt] [smalldatetime] NULL,
	[Prc_UltEnt] [numeric](18, 8) NULL,
	[Per_DscUltEnt] [numeric](7, 4) NULL,
	[Qtd_UltEnt] [int] NULL,
	[Dat_UltCompra] [smalldatetime] NULL,
	[Prc_EntAntDep] [numeric](18, 8) NULL,
	[Per_DscEntAntDep] [numeric](7, 4) NULL,
	[Qtd_EntAntDep] [int] NULL,
	[Dat_EntAntDep] [smalldatetime] NULL,
	[Prc_UltEntDep] [numeric](18, 8) NULL,
	[Per_DscUltEntDep] [numeric](7, 4) NULL,
	[Qtd_UltEntDep] [int] NULL,
	[Dat_UltEntDep] [smalldatetime] NULL,
	[Flg_RegSbtEsp] [bit] NULL,
	[Usuario] [varchar](15) NULL,
	[Transacao] [smalldatetime] NULL,
	[Qtd_PrmSolici] [int] NULL,
	[Qtd_PrmFisico] [int] NULL,
	[Qtd_PrmDispon] [int] NULL,
	[Prc_Fabric] [numeric](18, 8) NULL,
	[Prc_MaxCon] [numeric](18, 8) NULL,
	[Dat_PrcFab] [smalldatetime] NULL,
	[Qtd_EstMin] [int] NULL,
	[Qtd_EstMinCfg] [int] NULL,
	[Qtd_EstMax] [int] NULL,
	[Qtd_EstMaxCfg] [int] NULL,
	[_Qtd_EstMinVrj] [int] NULL,
	[_Qtd_EstMaxVrj] [int] NULL,
	[_Cod_Zon] [smallint] NULL,
	[Per_DscBasComNor] [numeric](18, 4) NULL,
	[Per_ComEnt] [numeric](18, 4) NULL,
	[Per_DscMaxVis] [numeric](18, 4) NULL,
	[Per_DscMaxPrz] [numeric](18, 4) NULL,
	[Qtd_PrzMaxFat] [int] NULL,
	[Per_MarkupCusCom] [numeric](18, 4) NULL,
	[Flg_UsoExcHsp] [bit] NULL,
	[Flg_CesBas] [bit] NULL,
	[Per_DscAut] [numeric](18, 4) NULL,
	[Per_DscAutOrc] [numeric](18, 4) NULL,
	[Per_BonAut] [numeric](18, 4) NULL,
	[Flg_BlqDsc] [bit] NULL,
	[Flg_BlqVen] [bit] NULL,
	[Flg_BlqCmp] [bit] NULL,
	[Flg_BlqInfVen] [bit] NULL,
	[Flg_BlqInfPar] [bit] NULL,
	[Flg_BlqCot] [bit] NULL,
	[Flg_BlqPrp] [bit] NULL,
	[Flg_BlqCfv] [bit] NULL,
	[Prc_Tabela] [numeric](18, 8) NULL,
	[Per_PlaRepIcm] [numeric](18, 8) NULL,
	[Per_PlaDesc1] [numeric](18, 8) NULL,
	[Per_PlaDesc2] [numeric](18, 8) NULL,
	[Per_PlaBonific] [numeric](18, 8) NULL,
	[Per_PlaCreIcm] [numeric](18, 8) NULL,
	[Per_PlaDebIcm] [numeric](18, 8) NULL,
	[Per_PlaRebate] [numeric](18, 8) NULL,
	[Per_PlaAgrega] [numeric](18, 8) NULL,
	[Per_PlaIpi] [numeric](18, 8) NULL,
	[Per_PlaDesFin] [numeric](18, 8) NULL,
	[Per_PlaCusFre] [numeric](18, 8) NULL,
	[Per_PlaDesOpe] [numeric](18, 8) NULL,
	[Per_PlaDesFre] [numeric](18, 8) NULL,
	[Per_PlaDesCom] [numeric](18, 8) NULL,
	[Per_PlaDesPis] [numeric](18, 8) NULL,
	[Per_PlaDesCof] [numeric](18, 8) NULL,
	[Per_PlaDesIrpj] [numeric](18, 8) NULL,
	[Per_PlaDesConSoc] [numeric](18, 8) NULL,
	[Per_PlaDesIcms] [numeric](18, 8) NULL,
	[Per_PlaMarRes] [numeric](18, 8) NULL,
	[Taxa_PlaFinanc] [numeric](18, 8) NULL,
	[Prc_CusLiqPla] [numeric](18, 8) NULL,
	[Prc_Pmz] [numeric](18, 8) NULL,
	[Per_PlaMarOpe] [numeric](18, 8) NULL,
	[Per_PlaMarFin] [numeric](18, 8) NULL,
	[Vlr_PlaPrcVen] [numeric](18, 8) NULL,
	[Dias_PlaFinanc] [int] NULL,
	[Flg_PlaFatPrcLiq] [bit] NULL,
	[Sta_AbcAcesso] [varchar](1) NULL,
	[Sta_AbcUniVen] [varchar](1) NULL,
	[Sta_AbcValFat] [varchar](1) NULL,
	[Flg_Bloqueado] [bit] NULL,
	[Dat_PrxVctLot] [smalldatetime] NULL,
	[Cod_Promocao] [int] NULL,
	[Cod_OriMer] [varchar](1) NULL,
	[Cod_ClaTri] [varchar](4) NULL,
	[Per_ParticFat] [numeric](18, 8) NULL,
	[Vlr_BasCalSubTriEntMed] [numeric](18, 4) NULL,
	[Qtd_Pulmao] [int] NULL,
	[Tip_Rentab] [varchar](1) NULL,
	[Flg_CusMedComRentab] [bit] NOT NULL,
	[Per_Rentab] [numeric](18, 4) NOT NULL,
	[Vlr_Rentab] [numeric](18, 4) NOT NULL,
	[Qtd_EstTraMan] [int] NULL,
	[Qtd_DiaSupPrd] [int] NULL,
	[Qtd_CanCompra] [int] NULL,
	[Dat_PrxVctLtl] [datetime] NULL,
	[Sta_AbcUniVenFab] [varchar](1) NULL,
	[Sta_AbcValFatFab] [varchar](1) NULL,
	[Per_LucMin] [numeric](18, 4) NULL,
	[Tip_BlqLuc] [varchar](1) NULL,
	[Qtd_CngCli] [int] NULL,
	[Qtd_CrossDock] [int] NULL,
	[Dat_UltVen] [datetime] NULL,
	[Qtd_MesAleRec] [int] NULL,
	[Cod_EnqIpi] [varchar](3) NULL,
	[Alq_Ipi] [numeric](7, 4) NULL,
	[Flg_UsaFatCxaDun14] [bit] NULL,
	[Cod_Antigo] [int] NULL)