USE BD_DW
GO

/****** Object:  Table [dbo].[R_VENDE]    Script Date: 28/06/2024 10:18:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_VENDE](
	[Codigo] [int] NOT NULL,
	[Nome_Guerra] [varchar](15) NULL,
	[Nome_Completo] [varchar](60) NULL,
	[Cod_Gerencia] [int] NULL,
	[Data_Admissao] [smalldatetime] NULL,
	[Data_Saida] [smalldatetime] NULL,
	[Area_Atuacao] [varchar](30) NULL,
	[Bloqueado] [bit] NULL,
	[Salario_Fixo] [numeric](18, 4) NULL,
	[Per_Poupanca] [numeric](18, 8) NULL,
	[Per_ComAtoVen] [numeric](18, 8) NULL,
	[Per_ComAtoCob] [numeric](18, 8) NULL,
	[Cod_TipVenBas] [char](3) NULL,
	[_Cod_TabCom] [int] NULL,
	[Vlr_Objetivo] [numeric](18, 4) NULL,
	[Cpf] [varchar](11) NULL,
	[Rg] [varchar](20) NULL,
	[Endereco] [varchar](35) NULL,
	[Bairro] [varchar](20) NULL,
	[Cep] [varchar](8) NULL,
	[Cidade] [varchar](20) NULL,
	[Estado] [char](2) NULL,
	[Fone] [varchar](20) NULL,
	[Celular] [varchar](20) NULL,
	[Razao_Social] [varchar](35) NULL,
	[Endereco_Com] [varchar](35) NULL,
	[Bairro_Com] [varchar](20) NULL,
	[Cep_Com] [varchar](8) NULL,
	[Cidade_Com] [varchar](20) NULL,
	[Estado_Com] [char](2) NULL,
	[Cgc] [varchar](14) NULL,
	[Cgf] [varchar](15) NULL,
	[Core] [varchar](15) NULL,
	[Observacao] [text] NULL,
	[Flg_Export] [bit] NULL,
	[Usuario] [varchar](35) NULL,
	[Transacao] [smalldatetime] NULL,
	[Des_Usuario] [varchar](30) NULL,
	[Des_Senha] [varchar](30) NULL,
	[Des_ServSmtp] [varchar](30) NULL,
	[Des_ServPop] [varchar](30) NULL,
	[Num_TeleProv] [varchar](15) NULL,
	[Des_Email] [varchar](120) NULL,
	[Cod_Bco] [smallint] NULL,
	[Num_Agenci] [varchar](6) NULL,
	[Num_Conta] [varchar](10) NULL,
	[Des_Favore] [varchar](40) NULL,
	[Cod_RefPrati] [varchar](14) NULL,
	[Dat_SldVrbIni] [smalldatetime] NULL,
	[Val_SldVrbIni] [numeric](18, 4) NULL,
	[Cod_DDD] [varchar](2) NULL,
	[Cod_Supervisor] [int] NULL,
	[Isn_CtaFin] [int] NULL,
	[CodAnt] [int] NULL,
	[NovoCodigo] [int] NULL,
	[Des_Nacionali] [varchar](20) NULL,
	[Cod_Sex] [varchar](1) NULL,
	[Cod_EstCiv] [varchar](1) NULL,
	[Des_OrgExpRg] [varchar](12) NULL,
	[Dat_EmiRg] [smalldatetime] NULL,
	[Versao] [bigint] NOT NULL,
	[Cod_EstabeOpe] [int] NULL,
	[Email] [varchar](120) NULL)