USE [DW_PROD]
GO

/****** Object:  Table [dbo].[CTMBD]    Script Date: 13/04/2024 17:10:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CTMBD](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cod_Bandei] [int] NOT NULL,
	[Des_Bandei] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


