DECLARE 
	@CEAN varchar(14),
	@CEAN1 varchar(14),
	@CEAN2 varchar(14),
	@CPROD1 int,
	@DESC1 varchar(50),
	@CESTA int = 1,
	@CPROD2 int,
	@DESC2 varchar(50),
	@QTDSDL1 BIGINT, 
	@DATMOV1 SMALLDATETIME,
	@QTDSDL2 BIGINT, 
	@DATMOV2 SMALLDATETIME,
	@DAT_CAD SMALLDATETIME


DECLARE CODEAN CURSOR FOR
	SELECT 
		P1.Cod_EAN
	FROM PROD_2022.dbo.PREAN P1
		INNER JOIN PROD_2023.dbo.PREAN P2 ON P1.Cod_EAN = P2.Cod_EAN AND P1.Cod_Produt <> P2.Cod_Produt
		INNER JOIN PROD_2023.dbo.PRXES ES2 ON  P2.Cod_Produt = ES2.Cod_Produt
	WHERE 
		ES2.Cod_Estabe = 1
		and P1.Cod_EAN > '0'

	OPEN CODEAN

	FETCH NEXT FROM CODEAN INTO @CEAN
	WHILE @@FETCH_STATUS = 0
	BEGIN

		DECLARE PRD22 CURSOR FOR

		SELECT 
			TOP 1
			P1.Codigo,
			P1.Descricao,
			P1.Dat_Cadastro,
			SD1.Qtd_SldAtu,
			MAX(SD1.Dat_Movime),
			PR1.Cod_EAN
			FROM PROD_2022.dbo.PRODU P1
				INNER JOIN PROD_2022.dbo.PREAN PR1 ON P1.Codigo = PR1.Cod_Produt
				INNER JOIN PROD_2022.dbo.PRXES ES1 ON P1.Codigo = ES1.Cod_Produt
				INNER JOIN PROD_2022.dbo.PRSLD SD1 ON ES1.COD_ESTABE = SD1.Cod_Estabe AND ES1.Cod_Produt = SD1.Cod_Produt
		WHERE 
			PR1.Cod_EAN = @CEAN
			AND SD1.Dat_Movime > '20221220'
		GROUP BY
			P1.Codigo,
			P1.Descricao,
			P1.Dat_Cadastro,
			SD1.Qtd_SldAtu,
			PR1.Cod_EAN
		ORDER BY 3 
	

		OPEN PRD22;
		FETCH NEXT FROM PRD22 INTO @CPROD1, @DESC1, @DAT_CAD,  @QTDSDL1, @DATMOV1, @CEAN1;
	WHILE @@FETCH_STATUS = 0
	
		BEGIN 
			
		PRINT '|0205|' + CAST(@DESC1 AS VARCHAR(80)) + '|' + CAST(replace(convert(varchar, @DAT_CAD, 103),'/', '') AS NVARCHAR(20)) + '|' + CAST('01012023' AS NVARCHAR(14)) + '|' + CAST(@CPROD1 AS NVARCHAR(5)) 
						
		FETCH NEXT FROM PRD22 INTO @CPROD1, @DESC1, @DAT_CAD,  @QTDSDL1, @DATMOV1, @CEAN1;

		END;

		
	CLOSE PRD22
	DEALLOCATE PRD22
	FETCH NEXT FROM CODEAN INTO @CEAN
	END;

CLOSE CODEAN
DEALLOCATE CODEAN
