SELECT  
	PC.ID_POLCOM,
	--COUNT(PR.COD_PRODUT) AS Qtd_Prod,
	--COUNT(CL.Cod_Client) AS Qtd_Cliente,
	PC.FLG_BLQPOLDIFITEPDV,
	PC.FLG_BLQPOLDIFCABPDV,
	PC.FLG
	FROM POCOM PC
		INNER JOIN PCXES ES ON PC.ID_POLCOM = ES.ID_POLCOM
		INNER JOIN PCXOP OP ON PC.ID_POLCOM = OP.ID_POLCOM
		left outer JOIN PCXPR PR ON PC.ID_POLCOM = PR.ID_POLCOM
		left outer JOIN PCXCL CL ON PC.ID_POLCOM = CL.ID_POLCOM
WHERE 
	--PC.ID_POLCOM = 2869 AND
	ES.COD_ESTABE = 1 AND
	PC.DAT_TERMINO > GETDATE() AND
	PC.Bloqueado = 0 
	--PC.FLG_CFV = 1 AND
	--OP.Cod_Vended = 650 

GROUP BY 
	PC.ID_POLCOM,
	PC.FLG_BLQPOLDIFITEPDV,
	PC.FLG_BLQPOLDIFCABPDV

