--Criar Tabelas DW

USE TESTE_DW

--Tabela Cliente:
/*
CREATE TABLE CLIENTE (
    IdCli INT PRIMARY KEY,
    DesCli VARCHAR(200),
    Dat_Cadastro DATE,
    Telefone CHAR (20),
    UF VARCHAR(2),
    Cidade VARCHAR(100),
    Bairro VARCHAR(100),
    Pessoa VARCHAR(1),
    TipCons VARCHAR(100),
    LicSaude VARCHAR (50),
    ValLicSaude DATE,
    Anvisa VARCHAR (100),
    ValAnvisa DATE,
    CRF_CRM VARCHAR (100),
    ValCRF DATE,
    AlvFunc VARCHAR (100),
    ValAlv DATE,
    Limite_Credito NUMERIC(9),
    Dat_UltComp DATE,
    Dat_LimCreAtu DATE,
    Vlr_LimCreAnt DECIMAL (10,4),
    Total_Debito DECIMAL(10,4),
    Suframa VARCHAR (9),
    Cod_RamoAtividade VARCHAR (100)
)
*/

--Tabela Fabricante:
/*
Create Table FABRICANT (
		Codigo INT PRIMARY KEY,
		Fantasia VARCHAR(25),
		Cgc_Cpf VARCHAR(14),
		Sta_ClaAbcVal CHAR(1),
		Per_ParticFat NUMERIC (9),
		Qtd_PrzMaxFat INT,
		Per_DscMaxVis NUMERIC (9),
		Per_DscMaxPrz NUMERIC (9),
		Per_DscBasComNor NUMERIC (9),
		Per_DscBasTax NUMERIC (9),
		Flg_Desconto BIT,
		Flg_BlqInfPar BIT,
		Flg_TransmPro BIT,
		Flg_TransmItx BIT,
		Flg_TransmGnx BIT,
		Flg_TransmNeo BIT,
		Flg_BlqIms BIT,
		Flg_TransmMtr BIT,
		Flg_TransmHyp BIT,
		Flg_BlqCloseUp BIT,
		Cod_ForPref INT
)
*/

--Tabela Vendedor:
/*
CREATE TABLE VENDEDOR (
						IdVen int primary key,
						Nome_Completo varchar(60),
						Nome_Guerra varchar (15),
						Data_Admissao smalldatetime,
						Data_Saida smalldatetime,
						Area_Atuacao varchar(30),
						Bloqueado bit,
						Cod_TipVenBas char(3),
						Vlr_Obj_vend numeric(9),
						Isn_CtaFin_vend int,
						Bairro varchar(20),
						Cidade varchar(20),
						UF char(2),
						Flg_Export bit,
						Transacao smalldatetime,
						Cod_Supervisor int,
						Supervisor varchar (30),
						Cod_Gerencia int,
						Gerente varchar(30),
						Vlr_Obj_geren numeric (9),
						Vlr_ComFixa_geren numeric(9),
						Isn_CtaFin_geren int,
						Cod_TabCom int)
*/

--Tabela Produto

/*
CREATE TABLE PRODUTO (
	IdProd int primary key,
	Descricao varchar(50),
	Unidade_Venda char(3),
	Ref_Fabricante numeric,
	Localizacao numeric,
	Ctrl_Preco char(1),
	Ctrl_Venda char(1),
	Cod_Fabricante numeric,
	Cod_EAN numeric,
	Cod_AbcFar numeric,
	Cod_GrpPrc numeric,
	Cod_Promocao numeric,
	Cod_PlaRegTri numeric,
	Cod_PrdExt numeric,
	Cod_Classif numeric,
	Cod_CtrUsu numeric,
	Cod_Estabe INT,
	Cod_RefPrati numeric,
	Cod_OriMer numeric,
	Cod_ClaTri numeric,
	Cod_EnqIpi numeric,
	Validade numeric,
	Dat_Cadastro smalldatetime,
	Dat_UltVenda smalldatetime,
	Dat_PrcFabAnt smalldatetime,
	Dat_PrcAtual smalldatetime,
	Dat_UltCompra smalldatetime,
	Dat_PrcFab smalldatetime,
	Dat_UltVen smalldatetime,
	Dat_PrxVctLtl smalldatetime,
	Dat_PrxVctLot smalldatetime,
	Qtd_EmbPalete INT,
	Qtd_CamPalete INT,
	Qtd_Fisico INT,
	Qtd_Solici INT,
	Qtd_Avaria INT,
	Qtd_Transi INT,
	Qtd_Reserv INT,
	Qtd_Quaren INT,
	Qtd_Embalagem INT,
	Qtd_SldAntBal INT,
	Qtd_SldPosBal INT,
	Qtd_PrmFisico INT,
	Qtd_PrmDispon INT,
	Qtd_PrmSolici INT,
	Qtd_EntAnt INT,
	Qtd_EstMin INT,
	Qtd_EstMinCfg INT,
	Qtd_EstMax INT,
	Qtd_EstMaxCfg INT,
	Qtd_UltEnt INT,
	Qtd_EntAntDep INT,
	Qtd_UltEntDep INT,
	Dat_EntAntDep INT,
	Dat_UltEntDep INT,
	Qtd_Pulmao INT,
	Qtd_EstTraMan INT,
	Qtd_DiaSupPrd INT, 
	Qtd_CanCompra INT,
	Qtd_PrzMaxFat INT,
	Qtd_CngCli INT,
	Qtd_MesAleRec INT,
	Sta_AbcValFat INT,
	Sta_AbcUniVen INT,
	Tipo,
	Tip_Rentab,
	Tip_BlqLuc,
	Tip_Por344,
	Tip_LisPis,
	Alq_Ipi numeric,
	Per_ParticFat numeric,
	Per_PlaRedCreIcm numeric,
	Per_plarepICm numeric,
	Per_PlaCreIcm numeric,
	Per_PlaDebIcm numeric,
	Per_PlaRebate numeric,
	Per_PlaAgrega numeric,
	Per_PlaDesc1 numeric,
	Per_PlaDesc2 numeric,
	Per_PlaBonific numeric,
	Per_PlaIpi numeric,
	Per_PlaDesFin numeric,
	Per_PlaCusFre numeric,
	Per_PlaDesOpe numeric,
	Per_PlaDesFre numeric,
	Per_PlaDesCom numeric,
	Per_PlaDesPis numeric,
	Per_PlaDesCof numeric,
	Per_PlaDesIrpj numeric,
	Per_PlaDesConSoc numeric,
	Per_PlaDesIcms numeric,
	Per_PlaMarOpe numeric,
	Per_PlaMarFin numeric,
	Per_ComVnd numeric,
	Per_Markup numeric,
	Per_BonAutOrc numeric,
	Per_DscBasComNor numeric,
	Per_ComEnt numeric,
	Per_DscMaxVis numeric,
	Per_DscMaxPrz numeric,
	Per_DscEntAnt numeric,
	Per_Ipi numeric,
	Per_PlaMarRes numeric,
	Per_BonAut numeric,
	Per_DscUltEnt numeric,
	Per_DscEntAntDep numeric,
	Per_DscUltEntDep numeric,
	Per_MarkupCusCom numeric,
	Per_DscAut numeric,
	Per_DscAutOrc numeric,
	Per_Rentab numeric,
	Per_LucMin numeric,
	Vlr_BasCalSubTriEntMed numeric,
	Vlr_Rentab numeric,
	Vlr_PlaPrcVen numeric,
	Prc_Tabela numeric,
	Prc_Venda numeric,
	Prc_CusLiqPla numeric,
	Prc_Pmz numeric,
	Prc_FabAnt numeric,
	Prc_MaxConAnt numeric,
	Prc_RefFpb numeric,
	Prc_RefFpbAnt numeric,
	Prc_Fabric12 numeric,
	Prc_MaxCon12 numeric,
	Prc_Fabric17 numeric,
	Prc_MaxCon17 numeric,
	Prc_Fabric175 numeric,
	Prc_MaxCon175 numeric,
	Prc_Fabric18 numeric,
	Prc_MaxCon18 numeric,
	Prc_Fabric19 numeric,
	Prc_MaxCon19 numeric,
	Prc_Fabric20 numeric,
	Prc_MaxCon20 numeric,
	Prc_Fabric21 numeric,
	Prc_MaxCon21 numeric,
	Prc_Fabric22 numeric,
	Prc_MaxCon22 numeric,
	Prc_Minimo numeric,
	Prc_VenAnt numeric,
	Prc_CusLiqEnt numeric,
	Prc_CusLiqEntDep numeric,
	Prc_CusMed numeric,
	Prc_CusMedPra numeric,
	Prc_CusMedDep numeric,
	Prc_CusMedCom numeric,
	Prc_EntAnt numeric,
	Prc_UltEnt numeric,
	Prc_EntAntDep numeric,
	Prc_UltEntDep numeric,
	Prc_Fabric numeric,
	Prc_MaxCon numeric,	
	Flag_ImprClassif1 BIT,
	Flg_PlaFatPrcLiq BIT,
	Flg_PolComercMax BIT,
	Flg_PrzComercMax BIT,
	Flg_Generico BIT,
	Flg_IncFis BIT,
	Flg_BlqDsc BIT,
	Flg_BlqVen BIT,
	Flg_BlqCmp BIT,
	Flg_BlqInfVen BIT,
	Flg_BlqInfPar BIT,
	Flg_BlqCot BIT,
	Flg_BlqPrp BIT,
	Flg_BlqCfv BIT,
	Flg_Bloqueado BIT,
	Flg_CusMedComRentab BIT,
	Flg_RegSbtEsp BIT,
	Dias_PlaFinanc ,
	Dias_PlaFinanc,
	Taxa_PlaFinanc numeric,
	Des_PrdDet,	
	Des_PrdRef,
	Edi_Pra,
	Edi_Dep,
	Lrg_Emb,
	Alt_Emb,
	Prf_Emb,
	Vol_Emb,
	Und_EmbCmp,
	Lrg_EmbCmp,
	Alt_EmbCmp,
	Prf_EmbCmp, 
	Pes_EmbCmp)
	*/