-- INSERIR NOVOS DADOS NO DW

--Tabela Cliente:

IF (SELECT COUNT(*) FROM [TESTE_DW].[dbo].[CLIENTE]) < (SELECT COUNT(*) FROM [TESTE].[dbo].[CLIEN]) 

	BEGIN TRAN
			INSERT INTO TESTE_DW.dbo.CLIENTE (
												IdCli, 
												DesCli, 
												Dat_Cadastro,
												Telefone, 
												UF, 
												Cidade, 
												Bairro, 
												Pessoa, 
												TipCons, 
												LicSaude, 
												ValLicSaude, 
												Anvisa, 
												ValAnvisa, 
												CRF_CRM, 
												ValCRF, 
												AlvFunc, 
												ValAlv, 
												Limite_Credito,  
												Dat_UltComp, 
												Dat_LimCreAtu, 
												Vlr_LimCreAnt, 
												Total_Debito, 
												Suframa, 
												Cod_RamoAtividade)
												SELECT 
													Codigo,
													Razao_Social,
													Data_Cadastro,
													Fone1,
													Cod_Estado,
													Cod_Cidade,
													cod_Bairro,
													Pessoa,
													Tipo_Consumidor,
													Licenca_Saude,
													Val_LicSau,
													Num_Anvisa,
													Val_Anvisa,
													Num_RegCrm,
													Val_CerReg,
													Num_AlvFun,
													Val_AlvFun,
													Limite_Credito,  
													cl.Data_UltimaFatura, 
													Dat_LimCreAtu, 
													Vlr_LimCreAnt, 
													Total_Debito, 
													Inscricao_SUFRAMA,
													Cod_RamoAtividade
													FROM TESTE.DBO.CLIEN cl
														INNER JOIN TESTE.DBO.ENXES es on cl.codigo = es.cod_client
												where bloqueado = 0 
												and Motivo_Bloqueio = ''
												and es.cod_estabe = 1
												and Codigo > (select max(IdCli) from [TESTE_DW].[dbo].[CLIENTE])
	COMMIT TRAN
GO

--Tabela Fabricante:

IF (SELECT COUNT(*) FROM [TESTE_DW].[dbo].[FABRICANT]) < (SELECT COUNT(*) FROM [TESTE].[dbo].[FABRI]) 

    BEGIN TRAN

        INSERT INTO TESTE_DW.dbo.FABRICANT(Codigo, Fantasia, Cgc_Cpf, Sta_ClaAbcVal, Per_ParticFat, Qtd_PrzMaxFat, Per_DscMaxVis, Per_DscMaxPrz, Per_DscBasComNor, Per_DscBasTax, Flg_Desconto, Flg_BlqInfPar,
										Flg_TransmPro, Flg_TransmItx, Flg_TransmGnx, Flg_TransmNeo, Flg_BlqIms, Flg_TransmMtr, Flg_TransmHyp, Flg_BlqCloseUp, Cod_ForPref)
            select 
                DISTINCT
                FB.Codigo,
                FB.Fantasia,
                FB.Cgc_Cpf,
                FB.Sta_ClaAbcVal,
                FB.Per_ParticFat,
                FB.Qtd_PrzMaxFat,
                FB.Per_DscMaxVis,
                FB.Per_DscMaxPrz,
                FB.Per_DscBasComNor,
                FB.Per_DscBasTax,
                FB.Flg_Desconto,
                FB.Flg_BlqInfPar,
                ES.Flg_TransmPro,
                ES.Flg_TransmItx,
                ES.Flg_TransmGnx,
                ES.Flg_TransmNeo,
                ES.Flg_BlqIms,
                ES.Flg_TransmMtr,
                ES.Flg_TransmHyp,
                ES.Flg_BlqCloseUp,
                ES.Cod_ForPref
                from TESTE.dbo.FABRI FB
                    INNER JOIN TESTE.dbo.FBXES ES ON FB.Codigo = ES.Cod_Fabric
            WHERE Cod_Estabe = 1 
                AND Bloqueado = 0
                AND Codigo > (select max(IdCli) from [TESTE_DW].[dbo].[FABRICANT])
            ORDER BY FB.Codigo

    COMMIT
GO

--Tabela Vendedor:

IF (SELECT COUNT(*) FROM [TESTE_DW].[dbo].[VENDEDOR]) < (SELECT COUNT(*) FROM [TESTE].[dbo].[VENDE ]) 
	BEGIN TRAN
			INSERT INTO TESTE_DW.dbo.VENDEDOR (	IdVen,
									Nome_Completo ,
									Nome_Guerra ,
									Data_Admissao ,
									Data_Saida ,
									Area_Atuacao ,
									Bloqueado ,
									Cod_TipVenBas ,
									Vlr_Obj_vend ,
									Isn_CtaFin_vend,
									Bairro ,
									Cidade ,
									UF,
									Flg_Export ,
									Transacao ,
									Cod_Supervisor,
									Supervisor ,
									Cod_Gerencia ,
									Gerente,
									Vlr_Obj_geren,
									Vlr_ComFixa_geren,
									Isn_CtaFin_geren,
									Cod_TabCom )
			select 
					ve.Codigo,
					ve.Nome_Completo ,
					ve.Nome_Guerra ,
					ve.Data_Admissao ,
					ve.Data_Saida ,
					ve.Area_Atuacao ,
					ve.Bloqueado ,
					ve.Cod_TipVenBas,
					ve.Vlr_Objetivo ,
					ve.Isn_CtaFin,
					ve.Bairro ,
					ve.Cidade ,
					ve.Estado,
					ve.Flg_Export ,
					ve.Transacao ,
					ve.Cod_Supervisor,
					su.Nome_Completo ,
					ve.Cod_Gerencia ,
					ge.Nome_Completo,
					ge.Vlr_Objetivo,
					ge.Vlr_ComFixa,
					ge.Isn_CtaFin,
					es.Cod_TabCom 
				from TESTE.dbo.VENDE VE
					inner join TESTE.dbo.SUPER SU ON VE.Cod_Supervisor = SU.Codigo
					inner join TESTE.dbo.GEREN GE	ON VE.Cod_Gerencia = GE.Codigo
					inner join TESTE.dbo.VEXES es on ve.Codigo = es.Cod_Vended
			where es.Cod_Estabe = 1
			    AND Bloqueado = 0
                AND Codigo > (select max(IdVen) from [TESTE_DW].[dbo].[VENDE])
            ORDER BY ve.Codigo


	COMMIT TRAN
GO

--Tabela Produto:

IF (SELECT COUNT(*) FROM [TESTE_DW].[dbo].[PRODUTO]) < (SELECT COUNT(*) FROM [TESTE].[dbo].[PRODU]) 
	BEGIN TRAN
			INSERT INTO TESTE_DW.DBO.PRODUTO (IdProd,
			Descricao,
			Unidade_Venda,
			Ref_Fabricante ,
			Localizacao ,
			Ctrl_Preco ,
			Ctrl_Venda ,
			Cod_Fabricante ,
			Cod_EAN ,
			Cod_AbcFar ,
			Cod_GrpPrc ,
			Cod_Promocao ,
			Cod_PlaRegTri ,
			Cod_PrdExt ,
			Cod_Classif ,
			Cod_CtrUsu ,
			Cod_Estabe ,
			Cod_RefPrati ,
			Cod_OriMer ,
			Cod_ClaTri ,
			Cod_EnqIpi ,
			Validade ,
			Dat_Cadastro ,
			Dat_UltVenda ,
			Dat_PrcFabAnt ,
			Dat_PrcAtual ,
			Dat_UltCompra ,
			Dat_PrcFab ,
			Dat_UltVen ,
			Dat_PrxVctLtl ,
			Dat_PrxVctLot ,
			Qtd_EmbPalete ,
			Qtd_CamPalete ,
			Qtd_Fisico ,
			Qtd_Solici ,
			Qtd_Avaria ,
			Qtd_Transi ,
			Qtd_Reserv ,
			Qtd_Quaren ,
			Qtd_Embalagem ,
			Qtd_SldAntBal ,
			Qtd_SldPosBal ,
			Qtd_PrmFisico ,
			Qtd_PrmDispon ,
			Qtd_PrmSolici ,
			Qtd_EntAnt ,
			Qtd_EstMin ,
			Qtd_EstMinCfg ,
			Qtd_EstMax ,
			Qtd_EstMaxCfg ,
			Qtd_UltEnt ,
			Qtd_EntAntDep ,
			Qtd_UltEntDep ,
			Dat_EntAntDep ,
			Dat_UltEntDep ,
			Qtd_Pulmao ,
			Qtd_EstTraMan ,
			Qtd_DiaSupPrd , 
			Qtd_CanCompra ,
			Qtd_PrzMaxFat ,
			Qtd_CngCli ,
			Qtd_MesAleRec ,
			Sta_AbcValFat ,
			Sta_AbcUniVen ,
			Tipo ,
			Tip_Prd ,
			Tip_Rentab ,
			Tip_BlqLuc,
			Tip_Por344 ,
			Tip_LisPis ,
			Alq_Ipi ,
			Per_ParticFat ,
			Per_PlaRedCreIcm ,
			Per_plarepICm ,
			Per_PlaCreIcm ,
			Per_PlaDebIcm ,
			Per_PlaRebate ,
			Per_PlaAgrega ,
			Per_PlaDesc1 ,
			Per_PlaDesc2 ,
			Per_PlaBonific ,
			Per_PlaIpi ,
			Per_PlaDesFin ,
			Per_PlaCusFre ,
			Per_PlaDesOpe ,
			Per_PlaDesFre ,
			Per_PlaDesCom ,
			Per_PlaDesPis ,
			Per_PlaDesCof ,
			Per_PlaDesIrpj ,
			Per_PlaDesConSoc ,
			Per_PlaDesIcms ,
			Per_PlaMarOpe ,
			Per_PlaMarFin ,
			Per_ComVnd ,
			Per_Markup ,
			Per_BonAutOrc ,
			Per_DscBasComNor ,
			Per_ComEnt ,
			Per_DscMaxVis ,
			Per_DscMaxPrz ,
			Per_DscEntAnt ,
			Per_Ipi ,
			Per_PlaMarRes ,
			Per_BonAut ,
			Per_DscUltEnt ,
			Per_DscEntAntDep ,
			Per_DscUltEntDep ,
			Per_MarkupCusCom ,
			Per_DscAut ,
			Per_DscAutOrc ,
			Per_Rentab ,
			Per_LucMin ,
			Vlr_BasCalSubTriEntMed ,
			Vlr_Rentab ,
			Vlr_PlaPrcVen ,
			Prc_Tabela ,
			Prc_Venda ,
			Prc_CusLiqPla ,
			Prc_Pmz ,
			Prc_FabAnt ,
			Prc_MaxConAnt ,
			Prc_RefFpb ,
			Prc_RefFpbAnt ,
			Prc_Fabric12 ,
			Prc_MaxCon12 ,
			Prc_Fabric17 ,
			Prc_MaxCon17 ,
			Prc_Fabric175 ,
			Prc_MaxCon175 ,
			Prc_Fabric18 ,
			Prc_MaxCon18 ,
			Prc_Fabric19 ,
			Prc_MaxCon19 ,
			Prc_Fabric20 ,
			Prc_MaxCon20 ,
			Prc_Fabric21 ,
			Prc_MaxCon21 ,
			Prc_Fabric22 ,
			Prc_MaxCon22 ,
			Prc_Minimo ,
			Prc_VenAnt ,
			Prc_CusLiqEnt ,
			Prc_CusLiqEntDep ,
			Prc_CusMed ,
			Prc_CusMedPra ,
			Prc_CusMedDep ,
			Prc_CusMedCom ,
			Prc_EntAnt ,
			Prc_UltEnt ,
			Prc_EntAntDep ,
			Prc_UltEntDep ,
			Prc_Fabric ,
			Prc_MaxCon ,	
			Flag_ImprClassif1 ,
			Flg_PlaFatPrcLiq ,
			Flg_PolComercMax ,
			Flg_PrzComercMax ,
			Flg_Generico ,
			Flg_IncFis ,
			Flg_BlqDsc ,
			Flg_BlqVen ,
			Flg_BlqCmp ,
			Flg_BlqInfVen ,
			Flg_BlqInfPar ,
			Flg_BlqCot ,
			Flg_BlqPrp ,
			Flg_BlqCfv ,
			Flg_Bloqueado ,
			Flg_CusMedComRentab ,
			Flg_RegSbtEsp ,
			Dias_PlaFinanc ,
			Taxa_PlaFinanc ,
			Des_PrdDet ,	
			Des_PrdRef ,
			Edi_Pra ,
			Edi_Dep ,
			Lrg_Emb ,
			Alt_Emb ,
			Prf_Emb ,
			Vol_Emb ,
			Und_EmbCmp ,
			Lrg_EmbCmp ,
			Alt_EmbCmp ,
			Prf_EmbCmp , 
			Pes_EmbCmp )
			select 
				Codigo ,
				Descricao,
				Unidade_Venda ,
				Ref_Fabricante ,
				Localizacao ,
				Ctrl_Preco,
				Ctrl_Venda ,
				Cod_Fabricante ,
				Cod_EAN ,
				Cod_AbcFar ,
				Cod_GrpPrc ,
				pr.Cod_Promocao,
				Cod_PlaRegTri ,
				Cod_PrdExt ,
				Cod_Classif ,
				Cod_CtrUsu ,
				Cod_Estabe ,
				Cod_RefPrati ,
				Cod_OriMer ,
				Cod_ClaTri ,
				Cod_EnqIpi ,
				Validade ,
				Dat_Cadastro ,
				Dat_UltVenda ,
				Dat_PrcFabAnt ,
				Dat_PrcAtual ,
				Dat_UltCompra ,
				Dat_PrcFab ,
				Dat_UltVen ,
				Dat_PrxVctLtl ,
				Dat_PrxVctLot ,
				Qtd_EmbPalete ,
				Qtd_CamPalete ,
				Qtd_Fisico ,
				Qtd_Solici ,
				Qtd_Avaria ,
				Qtd_Transi ,
				Qtd_Reserv ,
				Qtd_Quaren ,
				Qtd_Embalagem ,
				Qtd_SldAntBal ,
				Qtd_SldPosBal ,
				Qtd_PrmFisico ,
				Qtd_PrmDispon ,
				Qtd_PrmSolici ,
				Qtd_EntAnt ,
				Qtd_EstMin ,
				Qtd_EstMinCfg ,
				Qtd_EstMax ,
				Qtd_EstMaxCfg ,
				Qtd_UltEnt ,
				Qtd_EntAntDep ,
				Qtd_UltEntDep ,
				Dat_EntAntDep ,
				Dat_UltEntDep ,
				Qtd_Pulmao,
				Qtd_EstTraMan ,
				Qtd_DiaSupPrd , 
				Qtd_CanCompra ,
				Qtd_PrzMaxFat ,
				Qtd_CngCli ,
				Qtd_MesAleRec ,
				pr.Sta_AbcValFat ,
				pr.Sta_AbcUniVen ,
				Tipo ,
				Tip_Prd ,
				Tip_Rentab ,
				Tip_BlqLuc ,
				Tip_Por344 ,
				Tip_LisPis ,
				Alq_Ipi ,
				pr.Per_ParticFat ,
				Per_PlaRedCreIcm ,
				pr.Per_plarepICm ,
				pr.Per_PlaCreIcm ,
				pr.Per_PlaDebIcm ,
				pr.Per_PlaRebate ,
				pr.Per_PlaAgrega ,
				pr.Per_PlaDesc1 ,
				pr.Per_PlaDesc2 ,
				pr.Per_PlaBonific ,
				pr.Per_PlaIpi ,
				pr.Per_PlaDesFin ,
				pr.Per_PlaCusFre ,
				pr.Per_PlaDesOpe ,
				pr.Per_PlaDesFre ,
				pr.Per_PlaDesCom ,
				pr.Per_PlaDesPis ,
				pr.Per_PlaDesCof ,
				pr.Per_PlaDesIrpj ,
				pr.Per_PlaDesConSoc,
				pr.Per_PlaDesIcms ,
				pr.Per_PlaMarOpe ,
				pr.Per_PlaMarFin ,
				Per_ComVnd ,
				Per_Markup ,
				Per_BonAutOrc ,
				Per_DscBasComNor ,
				Per_ComEnt ,
				Per_DscMaxVis ,
				Per_DscMaxPrz ,
				Per_DscEntAnt ,
				Per_Ipi ,
				pr.Per_PlaMarRes ,
				Per_BonAut ,
				Per_DscUltEnt ,
				Per_DscEntAntDep ,
				Per_DscUltEntDep ,
				Per_MarkupCusCom ,
				Per_DscAut ,
				Per_DscAutOrc ,
				Per_Rentab ,
				Per_LucMin ,
				Vlr_BasCalSubTriEntMed ,
				Vlr_Rentab ,
				pr.Vlr_PlaPrcVen ,
				pr.Prc_Tabela ,
				Prc_Venda ,
				pr.Prc_CusLiqPla ,
				pr.Prc_Pmz ,
				Prc_FabAnt ,
				Prc_MaxConAnt ,
				Prc_RefFpb ,
				Prc_RefFpbAnt ,
				Prc_Fabric12 ,
				Prc_MaxCon12 ,
				Prc_Fabric17 ,
				Prc_MaxCon17 ,
				Prc_Fabric175 ,
				Prc_MaxCon175 ,
				Prc_Fabric18 ,
				Prc_MaxCon18 ,
				Prc_Fabric19 ,
				Prc_MaxCon19 ,
				Prc_Fabric20 ,
				Prc_MaxCon20 ,
				Prc_Fabric21 ,
				Prc_MaxCon21 ,
				Prc_Fabric22 ,
				Prc_MaxCon22 ,
				Prc_Minimo ,
				Prc_VenAnt ,
				Prc_CusLiqEnt ,
				Prc_CusLiqEntDep ,
				Prc_CusMed ,
				Prc_CusMedPra ,
				Prc_CusMedDep ,
				Prc_CusMedCom ,
				Prc_EntAnt ,
				Prc_UltEnt ,
				Prc_EntAntDep ,
				Prc_UltEntDep ,
				Prc_Fabric ,
				Prc_MaxCon ,	
				Flag_ImprClassif1 ,
				pr.Flg_PlaFatPrcLiq ,
				Flg_PolComercMax ,
				Flg_PrzComercMax ,
				Flg_Generico ,
				Flg_IncFis ,
				Flg_BlqDsc ,
				Flg_BlqVen ,
				Flg_BlqCmp ,
				Flg_BlqInfVen ,
				Flg_BlqInfPar ,
				Flg_BlqCot ,
				Flg_BlqPrp ,
				Flg_BlqCfv ,
				Flg_Bloqueado ,
				Flg_CusMedComRentab ,
				Flg_RegSbtEsp ,
				PR.Dias_PlaFinanc ,
				PR.Taxa_PlaFinanc ,
				Des_PrdDet ,	
				Des_PrdRef ,
				PR.Edi_Pra ,
				PR.Edi_Dep ,
				Lrg_Emb ,
				Alt_Emb ,
				Prf_Emb ,
				Vol_Emb ,
				Und_EmbCmp ,
				Lrg_EmbCmp ,
				Alt_EmbCmp ,
				Prf_EmbCmp , 
				Pes_EmbCmp
					from TESTE.DBO.PRODU pr
					inner join TESTE.DBO.PRXES ES ON PR.Codigo = ES.Cod_Produt
				WHERE ES.Cod_Estabe = 1

	COMMIT TRAN

GO