SELECT
	PR.CODIGO,
	SUM(IT.Qtd_PedFat) AS QTD_Compra
	FROM NFEIT IT
		INNER JOIN NFECB CB ON IT.Cod_Estabe = CB.Cod_Estabe AND IT.PROTOCOLO = CB.PROTOCOLO 
		INNER JOIN PRODU PR ON IT.Cod_Produto = PR.Codigo
WHERE 
 IT.Cod_Estabe = 1
 AND Cod_Fabricante = 319
 AND CB.DAT_ENTRADA >= '20230801'
 AND CB.DAT_ENTRADA <= '20230830'
 AND IT.Cod_Cfo in (2102, 2403, 2404) 

GROUP BY
	PR.CODIGO

ORDER BY 1

SELECT 
	PR.CODIGO,
	SUM(IT.Qtd_PedFat) AS QTD_BONI
	FROM NFEIT IT
		INNER JOIN NFECB CB ON IT.Cod_Estabe = CB.Cod_Estabe AND IT.PROTOCOLO = CB.PROTOCOLO 
		INNER JOIN PRODU PR ON IT.Cod_Produto = PR.Codigo
WHERE 
 IT.Cod_Estabe = 1
 AND Cod_Fabricante = 319
 AND CB.DAT_ENTRADA >= '20230101'
 AND CB.DAT_ENTRADA <= '20231231'
 AND IT.Cod_Cfo in (1910, 2910)

GROUP BY
	PR.CODIGO

ORDER BY 1