SELECT 
	FB.Codigo,
	FB.Fantasia,
	PR.Cod_EAN,
	PR.Descricao,
	SUM(IT.Qtd_Produto) AS 'Qtd Vendas',
	format(SUM(IT.Vlr_LiqVenIte), 'c', 'pt-br') AS 'Venda Líquida(R$)'
	FROM PRODU PR
		INNER JOIN FABRI FB ON PR.COD_FABRICANTE = FB.CODIGO
		INNER JOIN PRXES ES ON PR.CODIGO = ES.COD_PRODUT
		INNER JOIN NFSIT IT ON PR.CODIGO = IT.COD_PRODUTO AND ES.COD_ESTABE = IT.COD_ESTABE
		INNER JOIN NFSCB CB ON IT.COD_ESTABE = CB.COD_ESTABE AND IT.SER_NOTA = CB.SER_NOTA AND IT.NUM_NOTA = CB.NUM_NOTA
WHERE ES.COD_ESTABE = 1
	AND FB.CODIGO = 17
	AND CB.DAT_EMISSAO >= '20231001'
	AND CB.DAT_EMISSAO <= '20231031'
group by 
	FB.CODIGO,
	FB.Fantasia,
	PR.COD_EAN,
	PR.DESCRICAO
order by 3