CREATE VIEW OLADAY_FABRICANTE AS

SELECT  
	Bloqueado,
	Fantasia,
	Codigo as Id_Fabricante
FROM PROD_2023.dbo.FABRI FB
		JOIN PROD_2023.dbo.FBXES ES ON FB.Codigo = ES.Cod_Fabric
WHERE ES.COD_ESTABE = 1
