DECLARE 
	@CEAN varchar(14),
	@CEAN1 varchar(14),
	@CEAN2 varchar(14),
	@CPROD1 int,
	@DESC1 varchar(50),
	@CESTA int = 1,
	@CPROD2 int,
	@DESC2 varchar(50),
	@QTDSDL1 BIGINT, 
	@DATMOV1 SMALLDATETIME,
	@QTDSDL2 BIGINT, 
	@DATMOV2 SMALLDATETIME


DECLARE CODEAN CURSOR FOR
	SELECT 
		P1.Cod_EAN
	FROM PROD_2022.dbo.PREAN P1
		INNER JOIN PROD_2023.dbo.PREAN P2 ON P1.Cod_EAN = P2.Cod_EAN AND P1.Cod_Produt <> P2.Cod_Produt
		INNER JOIN PROD_2023.dbo.PRXES ES2 ON  P2.Cod_Produt = ES2.Cod_Produt
	WHERE 
		ES2.Cod_Estabe = 1
		and P1.Cod_EAN > '0'

	OPEN CODEAN

	FETCH NEXT FROM CODEAN INTO @CEAN
	WHILE @@FETCH_STATUS = 0
	BEGIN

		DECLARE PRD22 CURSOR FOR
		SELECT 
			TOP 1
			P1.Codigo,
			P1.Descricao,
			SD1.Qtd_SldAtu,
			MAX(SD1.Dat_Movime),
			PR1.Cod_EAN
			FROM PROD_2022.dbo.PRODU P1
				INNER JOIN PROD_2022.dbo.PREAN PR1 ON P1.Codigo = PR1.Cod_Produt
				INNER JOIN PROD_2022.dbo.PRXES ES1 ON P1.Codigo = ES1.Cod_Produt
				INNER JOIN PROD_2022.dbo.PRSLD SD1 ON ES1.COD_ESTABE = SD1.Cod_Estabe AND ES1.Cod_Produt = SD1.Cod_Produt
		WHERE 
			PR1.Cod_EAN = @CEAN
			AND SD1.Dat_Movime > '20221220'
		GROUP BY
			P1.Codigo,
			P1.Descricao,
			SD1.Qtd_SldAtu,
			PR1.Cod_EAN
		ORDER BY 3 
	

		OPEN PRD22;
		FETCH NEXT FROM PRD22 INTO @CPROD1, @DESC1, @QTDSDL1, @DATMOV1, @CEAN1;
	WHILE @@FETCH_STATUS = 0
		BEGIN 
			DECLARE PRO23 CURSOR FOR
			select 	TOP 1
				P2.Codigo,
				P2.Descricao,
				SD2.Qtd_SldAtu,
				SD2.Dat_Movime,
				PR2.Cod_EAN
				FROM PROD_2023.dbo.PRODU P2
					INNER JOIN PROD_2023.dbo.PREAN PR2 ON P2.Codigo = PR2.Cod_Produt
					INNER JOIN PROD_2023.dbo.PRXES ES2 ON P2.Codigo = ES2.Cod_Produt
					INNER JOIN PROD_2023.dbo.PRSLD SD2 ON ES2.COD_ESTABE = SD2.Cod_Estabe AND ES2.Cod_Produt = SD2.Cod_Produt
			WHERE
				ES2.Cod_Estabe = 1
				AND PR2.Cod_EAN = @CEAN1
				AND SD2.Dat_Movime > '20221230' 
			group by 
				P2.Codigo,
				P2.Descricao,
				SD2.Qtd_SldAtu,
				PR2.Cod_EAN,
				SD2.Dat_Movime

		

			OPEN PRO23;
			FETCH NEXT FROM PRO23 INTO @CPROD2, @DESC2, @QTDSDL2, @DATMOV2, @CEAN2;
					WHILE @@FETCH_STATUS = 0
						BEGIN 
			
						PRINT '|220|' + CAST(@CPROD1 AS NVARCHAR(5)) + '|' + CAST(@DESC1 AS VARCHAR(80)) + '|' + CAST(@QTDSDL1 AS NVARCHAR(20)) + '|' + CAST(@CEAN1 AS NVARCHAR(14)) 				
						PRINT '|221|' + CAST(@CPROD2 AS NVARCHAR(5)) + '|' + CAST(@DESC2 AS VARCHAR(80)) + '|' + CAST(@QTDSDL2 AS NVARCHAR(20)) + '|' + CAST(@CEAN2 AS NVARCHAR(14))

						FETCH NEXT FROM PRO23 INTO @CPROD2, @DESC2, @QTDSDL2, @DATMOV2, @CEAN2;

						END;

		CLOSE PRO23
		DEALLOCATE PRO23
		FETCH NEXT FROM PRD22 INTO @CPROD1, @DESC1, @QTDSDL1, @DATMOV1, @CEAN;
		END;
		
	CLOSE PRD22
	DEALLOCATE PRD22
	FETCH NEXT FROM CODEAN INTO @CEAN
	END;

CLOSE CODEAN
DEALLOCATE CODEAN
