SELECT
  PCCLIENT.CODCLI AS Codigo,
  PCCLIENT.CLIENTE AS Razão_Social,
  PCCLIENT.NUMALVARASANIT AS Alvara_Sanitario,
  PCCLIENT.DTVENCALVARASANIT AS Valido,
  PCCLIENT.NUMCRF AS CRF,
  PCCLIENT.DTVENCCRF AS Valido,
  PCCLIENT.NUMALVARAANVISA AS Anvisa,
  PCCLIENT.DTVENCALVARAANVISA AS Valido,
  PCFILIAL.CODIGO AS CodEstabe,
  PCFILIAL.RAZAOSOCIAL AS RAZAOSOCIAL,
  PCFILIAL.FANTASIA AS FANTASIA,
  PCUSUARI.CODUSUR AS RCA
FROM
  PCCLIENT
  INNER JOIN PCUSUARI ON PCCLIENT.CODUSUR1 = PCUSUARI.CODUSUR
  INNER JOIN PCFILIAL ON PCUSUARI.CODDISTRIB = PCFILIAL.CODIGO
WHERE
      PCUSUARI.CODDISTRIB IN (:Codigo_Estabelecimento)
  AND PCCLIENT.TIPOFJ IN (:Tipo_de_Pessoa)
  AND PCCLIENT.CODUSUR1 IN (:Vendedor)
  AND PCCLIENT.CODATV1 IN (:Ramo_Atividade)
  AND PCCLIENT.ESTENT = (:Por_Estado)
GROUP BY
  PCCLIENT.CODCLI,
  PCCLIENT.CLIENTE,
  PCCLIENT.NUMALVARASANIT,
  PCCLIENT.DTVENCALVARASANIT,
  PCCLIENT.NUMCRF,
  PCCLIENT.DTVENCCRF,
  PCCLIENT.NUMALVARAANVISA,
  PCCLIENT.DTVENCALVARAANVISA,
  PCFILIAL.CODIGO,
  PCFILIAL.RAZAOSOCIAL,
  PCFILIAL.FANTASIA,
  PCUSUARI.CODUSUR,
  PCUSUARI.CODDISTRIB

