select pp.CodProd, 
       pp.Descricao,
       pp.Revenda, 
       pp.Embalagem, 
       pp.Unidade, 
       pp.PesoLiq,
       pp.PesoBruto,
       pp.codfornec,
       pf.Fornecedor,
       pp.modulo,
       pp.rua,
       pp.apto,
       pp.unidademaster,
       pp.corredor,
       pp.larguram3,
       pp.alturam3,
       pp.comprimentom3,
       pp.Lastropal,
       pp.Alturapal,
       pp.QtTotPal,
       pp.LarguraARM,
       pp.ComprimentoARM,
       pp.AlturaARM,
       pp.VolumeARM,
       pp.VolumeREC,
       pp.PesoBrutoMaster,
       pp.PesoLiqMaster 
       from pcprodut pp
            inner join PCFORNEC pf on pp.codfornec = pf.codfornec 
where pp.pesoliq > 0