--#Entendendo Cursor#--

CREATE TABLE LIVROS(
	IDLIVROS INT PRIMARY KEY IDENTITY,
	NOME VARCHAR (30),
	VALOR DECIMAL (10,2)
)

GO

INSERT INTO LIVROS VALUES ('SQL', 100.00)
INSERT INTO LIVROS VALUES ('JAVA', 60.00)
INSERT INTO LIVROS VALUES ('PYTHON', 110.00)
INSERT INTO LIVROS VALUES ('SPARK', 190.00)


SELECT * FROM LIVROS

-- CRIANDO CURSOR

--DECLARANDO CURSOR

DECLARE 
	C_REG CURSOR FOR
	SELECT NOME, VALOR FROM LIVROS

-- DECLARADO VARIÁVEIS

DECLARE
	@NOME VARCHAR(30),
	@VALOR DECIMAL (10,2)

OPEN C_REG

FETCH NEXT FROM C_REG
INTO @NOME, @VALOR

WHILE @@FETCH_STATUS = 0

BEGIN
	 PRINT 'VALOR DO LIVRO ' + @NOME + ' R$' + CAST(@VALOR AS VARCHAR (10))

	 FETCH NEXT FROM C_REG
	 INTO @NOME, @VALOR

END
CLOSE C_REG
DEALLOCATE C_REG
GO


DROP TABLE LIVROS
GO