DECLARE 
	
	@PR INT,
	@DESC VARCHAR(50),
	@CEst INT = 1,
	@ANO INT = 2024,
	@M_ENT INT,
	@QTD_ENT INT,
	@M_SAI INT,
	@QTD_SAI INT

DECLARE PROD CURSOR FOR
	SELECT 
		CODIGO,
		DESCRICAO
	FROM PRODU
	WHERE CODIGO IN (15185, 12562, 21938, 12664, 22625)
OPEN PROD 
FETCH NEXT FROM PROD INTO @PR, @DESC
WHILE @@FETCH_STATUS = 0

	BEGIN
	DECLARE SAI CURSOR FOR 
		SELECT 
			DISTINCT
			QtdVen = Sum(it.Qtd_Produto),
			IsNull(MONTH(cb.Dat_Emissao), 0) AS Mês
		FROM PROD_2023.dbo.NFSCB cb 
			INNER JOIN PROD_2023.dbo.NFSIT it ON ((cb.Cod_Estabe = it.Cod_Estabe) AND 
													(cb.Ser_Nota = it.Ser_Nota) AND 
													(cb.Num_Nota = it.Num_Nota)) 
			INNER JOIN PROD_2023.dbo.PRODU pr on it.Cod_Produto = pr.Codigo 
		WHERE cb.Cod_Estabe = @CEst
			AND It.Cod_Produto = @PR
			AND (cb.Status = 'F' and cb.Tip_Saida in ('V', 'O', 'D')) 
			AND year(cb.Dat_Emissao) = @ANO
		Group by 

			cb.Dat_Emissao
OPEN SAI 
FETCH NEXT FROM SAI INTO @QTD_SAI, @M_SAI
WHILE @@FETCH_STATUS = 0
BEGIN 
	PRINT CAST(@PR AS NVARCHAR(255)) +';'+ CAST(@DESC AS NVARCHAR(255)) +';'+ CAST(@M_SAI AS NVARCHAR(255)) +';'+ CAST(@QTD_SAI AS NVARCHAR(255))
	
	FETCH NEXT FROM SAI INTO @QTD_SAI, @M_SAI
END
CLOSE SAI
DEALLOCATE SAI

	FETCH NEXT FROM PROD INTO @PR, @DESC

END
CLOSE PROD
DEALLOCATE PROD