USE [DW_PROD]
GO

/****** Object:  View [dbo].[DASH_TRIMESTRAL_VXCLIENTES]    Script Date: 27/06/2024 13:31:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[DASH_TRIMESTRAL_VXCLIENTES] AS
SELECT 
	distinct
	CODIGO,
	Razao_Social,
	SUM(QTD_VENDAS) AS QTD_VENDAS,
	SUM(VLR_VENDA) AS VLR_VENDAS,
	SUM(M_VENDAS) as M_VENDAS,
	Mes,
	Ano
FROM [VW_TRIMESTRAL_VXCLIENTES]

group by 
	CODIGO,
	Razao_Social,
	Ano,
	Mes
GO


