USE [DW_PROD]
GO

/****** Object:  View [dbo].[DASH_REG_INADIM]    Script Date: 27/06/2024 13:28:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[DASH_REG_INADIM] AS
      SELECT
		IsNull(VLR_UM, 0) AS 'V_UM',
        VLR_DEZ AS 'V_DEZ',
        VLR_VINT AS 'V_TRINTA',
        VLR_TRINT AS 'V_SESSE',
        VLR_SESS AS 'V_NOVENT',
        VLR_NOV AS 'VLR_CENT_VINT',
        VLR_C_VINT AS 'VLR_CENT_OIT',
        VLR_C_OIT AS 'M_180',
        TOTAL =  (IsNull(VLR_UM, 0) + VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT),
		UM = ((IsNull(VLR_UM, 0) / SUM (VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100),
		DEZ = ((VLR_DEZ / SUM (VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100),
		TRINTA = ((VLR_VINT / SUM (VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100),
		SESSENTA = ((VLR_TRINT / SUM (VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100),
		NOVENTA = ((VLR_SESS / SUM (VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100),
		C_VINTE = ((VLR_NOV / SUM (VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100),
		C_OITENTA = ((VLR_C_VINT / SUM (VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100),
		M_C_OIT = ((VLR_C_OIT / SUM (VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100),
		C_TOTAL = (SUM (IsNull(VLR_UM, 0) + VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT) / SUM (IsNull(VLR_UM, 0) + VLR_DEZ + VLR_VINT + VLR_TRINT + VLR_SESS + VLR_NOV + VLR_C_VINT + VLR_C_OIT))*100
        FROM
			[VW_REG_INADIM]
        GROUP BY
		VLR_UM,
        VLR_DEZ,
        VLR_VINT,
        VLR_TRINT,
        VLR_SESS,
        VLR_NOV,
        VLR_C_VINT,
        VLR_C_OIT
GO


