USE [BD_DW]
GO

/****** Object:  View [dbo].[VW_PCXSU]    Script Date: 13/04/2024 16:41:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_PCXSU] AS
SELECT  PSU.*
FROM PROD_2023.dbo.PCXSU PSU
	INNER JOIN PROD_2023.dbo.PCXES ES ON PSU.Id_PolCom = ES.Id_PolCom 
WHERE 
	ES.Cod_Estabe = 1
GO


