USE [BD_DW]
GO

/****** Object:  View [dbo].[VW_POCOM]    Script Date: 13/04/2024 16:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_POCOM] AS
SELECT PC.*
FROM PROD_2023.dbo.POCOM PC
	INNER JOIN PROD_2023.dbo.PCXES ES ON PC.Id_PolCom = ES.Id_PolCom
WHERE 
	Cod_Estabe = 1
GO


