USE [BD_DW]
GO

/****** Object:  View [dbo].[VW_PCXCP]    Script Date: 13/04/2024 16:31:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_PCXCP] AS
SELECT  PCP.*
FROM PROD_2023.dbo.PCXCP PCP
	INNER JOIN PROD_2023.dbo.PCXES ES ON PCP.Id_PolCom = ES.Id_PolCom
WHERE 
	Cod_Estabe = 1
GO


