USE [DW_PROD]
GO

/****** Object:  View [dbo].[VW_PCXPF]    Script Date: 13/04/2024 16:37:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_PCXPF] AS
SELECT  PPF.*
FROM PROD_2023.dbo.PCXPF PPF
	INNER JOIN PROD_2023.dbo.PCXES ES ON PPF.Id_PolCom = ES.Id_PolCom
WHERE 
	Cod_Estabe = 1
GO


