USE [BD_DW]
GO

/****** Object:  View [dbo].[VW_PCXGC]    Script Date: 13/04/2024 16:35:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_PCXGC] AS
SELECT PCG.*
FROM PROD_2023.dbo.PCXGC PCG
	INNER JOIN PROD_2023.dbo.PCXES ES ON PCG.Id_PolCom = ES.Id_PolCom
WHERE 
	Cod_Estabe = 1
GO


