USE [BD_DW]
GO

/****** Object:  View [dbo].[VW_PCXFB]    Script Date: 13/04/2024 16:33:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_PCXFB] AS
SELECT PCF.*
FROM PROD_2023.dbo.PCXFB PCF
	INNER JOIN PROD_2023.dbo.PCXES ES ON PCF.Id_PolCom = ES.Id_PolCom
WHERE 
	Cod_Estabe = 1
GO


