USE [DW_PROD]
GO

/****** Object:  View [dbo].[DASH_TIMESTRAL_VXVENDEDOR]    Script Date: 11/04/2024 17:14:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[DASH_TIMESTRAL_VXVENDEDOR] AS
SELECT 
	distinct
	CODIGO,
	Nome_Guerra,
	SUM(QTD_VENDAS) AS QTD_VENDAS,
	SUM(VLR_VENDA) AS VLR_VENDAS,
	SUM(M_VENDAS) as M_VENDAS,
	Ano,
	Mes
FROM [VW_TIMESTRAL_VXVENDEDOR]

group by 
	CODIGO,
	Nome_Guerra,
	Ano,
	Mes
GO
