/****** Script do comando SelectTopNRows de SSMS  ******/
INSERT INTO [R_GRCLI] ([Cod_GrpCli]
      ,[Des_GrpCli]
      ,[Qtd_PrzMax]
      ,[Per_Descon]
      ,[Per_DscVis]
      ,[Flg_ComFab]
      ,[Flg_ComPrpDsc]
      ,[Usuario]
      ,[Transacao]
      ,[Per_ComVnd]
      ,[Flg_ExpBomPrc]
      ,[Des_UrlExpBomPrc]
      ,[CodAnt]
      ,[NovoCodigo]
      ,[Per_RntMinPdv]
      ,[Flg_LotUniPrdPdv]
      ,[Versao]
      ,[Cod_EnqIpi])
SELECT [Cod_GrpCli]
      ,[Des_GrpCli]
      ,[Qtd_PrzMax]
      ,[Per_Descon]
      ,[Per_DscVis]
      ,[Flg_ComFab]
      ,[Flg_ComPrpDsc]
      ,[Usuario]
      ,[Transacao]
      ,[Per_ComVnd]
      ,[Flg_ExpBomPrc]
      ,[Des_UrlExpBomPrc]
      ,[CodAnt]
      ,[NovoCodigo]
      ,[Per_RntMinPdv]
      ,[Flg_LotUniPrdPdv]
      ,[Versao]
      ,[Cod_EnqIpi]
 FROM PROD_2023.[dbo].[GRCLI]
 