use BD_DW
GO

BEGIN TRY
	BEGIN TRANSACTION;

	BEGIN
        INSERT INTO BD_DW.dbo.R_PDVIT ([Cod_Pedido],[Cod_Produto],[Cod_Lote],[Cod_Fabricante],[Loc_Fisica],[Qtd_Solicitado],[Qtd_Acerto],[Qtd_Pedido],[Qtd_Bonificacao],[Qtd_Pendente],[Flg_PrcUniDsc],[Per_Desconto],[Prc_Unitario],[Tip_Aux]
                            ,[Ctrl_Tributacao],[Cod_ClaTri],[Alq_Icms],[Vlr_BasIcmsNor],[Vlr_IcmsNor],[Vlr_RepIcms],[Vlr_BasRepIcms],[Vlr_SubsTrib],[Vlr_PrdSubTri],[Vlr_BasSubsTrib],[Vlr_IcmsTri],[Vlr_BasIcmsTri],[Vlr_Isento]
                            ,[Vlr_DscTri],[Vlr_Bruto],[Cod_Promocao],[Desconto],[Flg_BlqInfPar],[Qtd_PrzMax],[Per_Descon],[Per_DscVis],[C_VlrDesconto],[C_PrcUni],[C_PerDscIte],[C_PrcTotal],[C_VlrLiquido],[Prc_Tabela],[Des_Und]
                            ,[Qtd_AprPdv],[Des_UndVen],[Prc_TabBru],[Vlr_Outros],[Flg_Entreg],[Qtd_ImpFat],[Prc_UniImpFat],[Fat_CnvImpFat],[Qtd_Pra],[Qtd_Dep],[Prc_MaxCon],[Prc_Fabric],[Num_SeqDig],[Nom_UsuDesbloq],[Des_UnvImpFat]
                            ,[Des_AprImpFat],[Flg_VctLic],[Per_Rnt],[Prc_BasRnt],[Per_Comissao],[Per_ComTlmkt],[Per_ComTra],[Vlr_Comissao],[Vlr_ComTlmkt],[Val_ComTra],[Cod_ModBasCalIcm],[Cod_ModBasCalIcmSbt],[Per_RedBasCalIcm]
                            ,[Per_RedBasCalIcmSbt],[Alq_IcmSbt],[Vlr_BasTri],[Alq_AgrSbt],[Id_PolCom],[Flg_Verba],[Prc_PolCom],[Per_DscPolCom],[Per_DscVisPolCom],[Vlr_Verba],[Qtd_PrzPolCom],[Des_MsgDesbloq],[Prc_UniLiqPer]
                            ,[Prc_LiqUltEnt],[Cod_MtvRej],[Des_MtvRej],[Per_ComGer],[Vlr_ComGer],[Per_ComSup],[Vlr_ComSup],[Per_ComGerOpe],[Vlr_ComGerOpe],[Per_ComSupOpe],[Vlr_ComSupOpe],[Per_VrbPar],[Vlr_VrbPar],[Per_VrbBon]
                            ,[Vlr_VrbBon],[Prc_UniPde],[Per_DscPde],[Prc_RefFpb],[Cod_CSOSN],[Flg_PolPrm],[Cod_PrjPde],[Num_SeqPdc],[Vlr_BasSbtRes],[Vlr_SbtRes],[Num_IteCot],[Vlr_Bonificacao],[Vlr_DscBonRat],[Prc_CusMinComMarkup]
                            ,[Vlr_BasVerba],[Vlr_VrbVdr],[Per_MarkupCusCom],[Tip_Sai],[CodAnt],[NovoCodigo],[Cod_Estabe],[Per_AcrAlqIntFcp],[Vlr_IcmFcpDes],[Vlr_Despes],[Vlr_BasDespes],[Per_PrvParIcm],[Vlr_IcmParDes],[Vlr_IcmParRem]
                            ,[Alq_IntIcmDes],[Cod_KitPrm],[CST_Pis],[Vlr_BasPis],[Alq_Pis],[Vlr_Pis],[CST_Cofins],[Vlr_BasCofins],[Alq_Cofins],[Vlr_Cofins],[Per_MarBru],[Vlr_VrbPdv],[Vlr_BasCalSubTriEntMed],[Per_RntBru],[Tip_BasRnt]
                            ,[Flg_UsaDebPresum],[Alq_IcmPresum],[Vlr_DscBonDup],[Vlr_BasDscTri],[Per_DscTri],[Alq_IcmDif],[Vlr_IcmsDif],[Qtd_PesVolImpFat],[Des_UnvPesVolImpFat],[Prc_UniPesVolImpFat],[Vlr_IcmsDeson],[Cod_MtvIcmsDeson]
                            ,[Vlr_DscCalSuframa],[Flg_IncFis],[Alq_FcpIcm],[Vlr_FcpIcm],[Alq_FcpSbt],[Vlr_FcpSbt],[Alq_FcpSbtRet],[Vlr_FcpSbtRet],[Per_IcmDiferi],[Vlr_IcmDiferi],[Nom_UsuCor],[Dat_UsuCor],[Cod_MtvCor],[Des_MtvCor]
                            ,[Vlr_VrbOpe],[Vlr_VrbSup],[Per_VrbVdr],[Per_VrbOpe],[Per_VrbSup],[Alq_EfeDas],[Vlr_DscRat],[Prc_PonFin],[Vlr_DspExt],[Vlr_BasIpi],[Vlr_Ipi],[Alq_Ipi],[CST_Ipi],[Cod_EnqIpi],[Cod_OriMer],[Prc_UniSemAcrIcm]
                            ,[Flg_PrcUniAcrIcm],[Prc_UniComAcrIcm],[Per_RepIcms],[Vlr_BasIrf],[Alq_Irf],[Vlr_Irf],[Qtd_GanCot],[Per_LinCot],[Vlr_SbtRetAnt],[Vlr_BasCsl],[Alq_Csl],[Vlr_Csl],[Tip_PolCom])
        SELECT 
                [Cod_Pedido],[Cod_Produto],[Cod_Lote],[Cod_Fabricante],[Loc_Fisica],[Qtd_Solicitado],[Qtd_Acerto],[Qtd_Pedido],[Qtd_Bonificacao],[Qtd_Pendente],[Flg_PrcUniDsc],[Per_Desconto],[Prc_Unitario],[Tip_Aux]
                ,[Ctrl_Tributacao],[Cod_ClaTri],[Alq_Icms],[Vlr_BasIcmsNor],[Vlr_IcmsNor],[Vlr_RepIcms],[Vlr_BasRepIcms],[Vlr_SubsTrib],[Vlr_PrdSubTri],[Vlr_BasSubsTrib],[Vlr_IcmsTri],[Vlr_BasIcmsTri],[Vlr_Isento]
                ,[Vlr_DscTri],[Vlr_Bruto],[Cod_Promocao],[Desconto],[Flg_BlqInfPar],[Qtd_PrzMax],[Per_Descon],[Per_DscVis],[C_VlrDesconto],[C_PrcUni],[C_PerDscIte],[C_PrcTotal],[C_VlrLiquido],[Prc_Tabela],[Des_Und]
                ,[Qtd_AprPdv],[Des_UndVen],[Prc_TabBru],[Vlr_Outros],[Flg_Entreg],[Qtd_ImpFat],[Prc_UniImpFat],[Fat_CnvImpFat],[Qtd_Pra],[Qtd_Dep],[Prc_MaxCon],[Prc_Fabric],[Num_SeqDig],[Nom_UsuDesbloq],[Des_UnvImpFat]
                ,[Des_AprImpFat],[Flg_VctLic],[Per_Rnt],[Prc_BasRnt],[Per_Comissao],[Per_ComTlmkt],[Per_ComTra],[Vlr_Comissao],[Vlr_ComTlmkt],[Val_ComTra],[Cod_ModBasCalIcm],[Cod_ModBasCalIcmSbt],[Per_RedBasCalIcm]
                ,[Per_RedBasCalIcmSbt],[Alq_IcmSbt],[Vlr_BasTri],[Alq_AgrSbt],[Id_PolCom],[Flg_Verba],[Prc_PolCom],[Per_DscPolCom],[Per_DscVisPolCom],[Vlr_Verba],[Qtd_PrzPolCom],[Des_MsgDesbloq],[Prc_UniLiqPer]
                ,[Prc_LiqUltEnt],[Cod_MtvRej],[Des_MtvRej],[Per_ComGer],[Vlr_ComGer],[Per_ComSup],[Vlr_ComSup],[Per_ComGerOpe],[Vlr_ComGerOpe],[Per_ComSupOpe],[Vlr_ComSupOpe],[Per_VrbPar],[Vlr_VrbPar],[Per_VrbBon]
                ,[Vlr_VrbBon],[Prc_UniPde],[Per_DscPde],[Prc_RefFpb],[Cod_CSOSN],[Flg_PolPrm],[Cod_PrjPde],[Num_SeqPdc],[Vlr_BasSbtRes],[Vlr_SbtRes],[Num_IteCot],[Vlr_Bonificacao],[Vlr_DscBonRat],[Prc_CusMinComMarkup]
                ,[Vlr_BasVerba],[Vlr_VrbVdr],[Per_MarkupCusCom],[Tip_Sai],[CodAnt],[NovoCodigo],[Cod_Estabe],[Per_AcrAlqIntFcp],[Vlr_IcmFcpDes],[Vlr_Despes],[Vlr_BasDespes],[Per_PrvParIcm],[Vlr_IcmParDes],[Vlr_IcmParRem]
                ,[Alq_IntIcmDes],[Cod_KitPrm],[CST_Pis],[Vlr_BasPis],[Alq_Pis],[Vlr_Pis],[CST_Cofins],[Vlr_BasCofins],[Alq_Cofins],[Vlr_Cofins],[Per_MarBru],[Vlr_VrbPdv],[Vlr_BasCalSubTriEntMed],[Per_RntBru],[Tip_BasRnt]
                ,[Flg_UsaDebPresum],[Alq_IcmPresum],[Vlr_DscBonDup],[Vlr_BasDscTri],[Per_DscTri],[Alq_IcmDif],[Vlr_IcmsDif],[Qtd_PesVolImpFat],[Des_UnvPesVolImpFat],[Prc_UniPesVolImpFat],[Vlr_IcmsDeson],[Cod_MtvIcmsDeson]
                ,[Vlr_DscCalSuframa],[Flg_IncFis],[Alq_FcpIcm],[Vlr_FcpIcm],[Alq_FcpSbt],[Vlr_FcpSbt],[Alq_FcpSbtRet],[Vlr_FcpSbtRet],[Per_IcmDiferi],[Vlr_IcmDiferi],[Nom_UsuCor],[Dat_UsuCor],[Cod_MtvCor],[Des_MtvCor]
                ,[Vlr_VrbOpe],[Vlr_VrbSup],[Per_VrbVdr],[Per_VrbOpe],[Per_VrbSup],[Alq_EfeDas],[Vlr_DscRat],[Prc_PonFin],[Vlr_DspExt],[Vlr_BasIpi],[Vlr_Ipi],[Alq_Ipi],[CST_Ipi],[Cod_EnqIpi],[Cod_OriMer],[Prc_UniSemAcrIcm]
                ,[Flg_PrcUniAcrIcm],[Prc_UniComAcrIcm],[Per_RepIcms],[Vlr_BasIrf],[Alq_Irf],[Vlr_Irf],[Qtd_GanCot],[Per_LinCot],[Vlr_SbtRetAnt],[Vlr_BasCsl],[Alq_Csl],[Vlr_Csl],[Tip_PolCom]
        FROM [RemoteServerName].[DMD].[dbo].[PDVCB]
        WHERE 
            COD_ESTABE = 1
        AND exists (SELECT Cod_Pedido FROM R_PDVCB)
    END

	BEGIN 
		UPDATE R_IT
        SET R_IT.[Qtd_Solicitado] = IT.[Qtd_Solicitado]			
            ,R_IT.[Qtd_Acerto] = IT.[Qtd_Acerto]
            ,R_IT.[Qtd_Pedido] = IT.[Qtd_Pedido]		
            ,R_IT.[Qtd_Bonificacao] = IT.[Qtd_Bonificacao]		
            ,R_IT.[Qtd_Pendente] = 	IT.[Qtd_Pendente]	
            ,R_IT.[Flg_PrcUniDsc] = IT.[Flg_PrcUniDsc]			
            ,R_IT.[Per_Desconto] = IT.[Per_Desconto]	
            ,R_IT.[Prc_Unitario] = IT.[Prc_Unitario]				
            ,R_IT.[Tip_Aux] = IT.[Tip_Aux]			
            ,R_IT.[Ctrl_Tributacao] = IT.[Ctrl_Tributacao]	
            ,R_IT.[Cod_ClaTri] = IT.[Cod_ClaTri]	
            ,R_IT.[Alq_Icms] = IT.[Alq_Icms]			
            ,R_IT.[Vlr_BasIcmsNor] = IT.[Vlr_BasIcmsNor]			
            ,R_IT.[Vlr_IcmsNor] = IT.[Vlr_IcmsNor]		
            ,R_IT.[Vlr_RepIcms] = IT.[Vlr_RepIcms]			
            ,R_IT.[Vlr_BasRepIcms] = IT.[Vlr_BasRepIcms]			
            ,R_IT.[Vlr_SubsTrib] = IT.[Vlr_SubsTrib]		
            ,R_IT.[Vlr_PrdSubTri] =	IT.[Vlr_PrdSubTri]		
            ,R_IT.[Vlr_BasSubsTrib] = IT.[Vlr_BasSubsTrib]		
            ,R_IT.[Vlr_IcmsTri] = IT.[Vlr_IcmsTri]	
            ,R_IT.[Vlr_BasIcmsTri] = IT.[Vlr_BasIcmsTri]			
            ,R_IT.[Vlr_Isento] = IT.[Vlr_Isento]		
            ,R_IT.[Vlr_DscTri] = IT.[Vlr_DscTri]				
            ,R_IT.[Vlr_Bruto] =	IT.[Vlr_Bruto]		
            ,R_IT.[Cod_Promocao] = IT.[Cod_Promocao]				
            ,R_IT.[Desconto] = IT.[Desconto]			
            ,R_IT.[Flg_BlqInfPar] = IT.[Flg_BlqInfPar]			
            ,R_IT.[Qtd_PrzMax] = IT.[Qtd_PrzMax]			
            ,R_IT.[Per_Descon] = IT.[Per_Descon]				
            ,R_IT.[Per_DscVis] = IT.[Per_DscVis]				
            ,R_IT.[C_VlrDesconto] =	IT.[C_VlrDesconto]	
            ,R_IT.[C_PrcUni] = IT.[C_PrcUni]			
            ,R_IT.[C_PerDscIte] = IT.[C_PerDscIte]				
            ,R_IT.[C_PrcTotal] = IT.[C_PrcTotal]		
            ,R_IT.[C_VlrLiquido] = IT.[C_VlrLiquido]			
            ,R_IT.[Prc_Tabela] = IT.[Prc_Tabela]			
            ,R_IT.[Des_Und] = IT.[Des_Und]			
            ,R_IT.[Qtd_AprPdv] = IT.[Qtd_AprPdv]				
            ,R_IT.[Des_UndVen] = IT.[Des_UndVen]				
            ,R_IT.[Prc_TabBru] = IT.[Prc_TabBru]				
            ,R_IT.[Vlr_Outros] = IT.[Vlr_Outros]				
            ,R_IT.[Flg_Entreg] = IT.[Flg_Entreg]				
            ,R_IT.[Qtd_ImpFat] = IT.[Qtd_ImpFat]				
            ,R_IT.[Prc_UniImpFat] = IT.[Prc_UniImpFat]			
            ,R_IT.[Fat_CnvImpFat] = IT.[Fat_CnvImpFat]			
            ,R_IT.[Qtd_Pra] = IT.[Qtd_Pra]			
            ,R_IT.[Qtd_Dep] = IT.[Qtd_Dep]				
            ,R_IT.[Prc_MaxCon] = IT.[Prc_MaxCon]				
            ,R_IT.[Prc_Fabric] = IT.[Prc_Fabric]				
            ,R_IT.[Num_SeqDig] = IT.[Num_SeqDig]			
            ,R_IT.[Nom_UsuDesbloq] = IT.[Nom_UsuDesbloq]			
            ,R_IT.[Des_UnvImpFat] =	IT.[Des_UnvImpFat]	
            ,R_IT.[Des_AprImpFat] =	IT.[Des_AprImpFat]		
            ,R_IT.[Flg_VctLic] = IT.[Flg_VctLic]			
            ,R_IT.[Per_Rnt] = IT.[Per_Rnt]			
            ,R_IT.[Prc_BasRnt] = IT.[Prc_BasRnt] 				
            ,R_IT.[Per_Comissao] = IT.[Per_Comissao]			
            ,R_IT.[Per_ComTlmkt] = IT.[Per_ComTlmkt]				
            ,R_IT.[Per_ComTra] = IT.[Per_ComTra]			
            ,R_IT.[Vlr_Comissao] = IT.[Vlr_Comissao] 				
            ,R_IT.[Vlr_ComTlmkt] = IT.[Vlr_ComTlmkt]				
            ,R_IT.[Val_ComTra] = IT.[Val_ComTra]			
            ,R_IT.[Cod_ModBasCalIcm] = IT.[Cod_ModBasCalIcm] 		
            ,R_IT.[Cod_ModBasCalIcmSbt] = IT.[Cod_ModBasCalIcmSbt]		
            ,R_IT.[Per_RedBasCalIcm] = IT.[Per_RedBasCalIcm]	
            ,R_IT.[Per_RedBasCalIcmSbt] = IT.[Per_RedBasCalIcmSbt]		
            ,R_IT.[Alq_IcmSbt] = IT.[Alq_IcmSbt]	
            ,R_IT.[Vlr_BasTri] = IT.[Vlr_BasTri]				
            ,R_IT.[Alq_AgrSbt] = IT.[Alq_AgrSbt]				
            ,R_IT.[Id_PolCom] =	IT.[Id_PolCom]		
            ,R_IT.[Flg_Verba] =	IT.[Flg_Verba]			
            ,R_IT.[Prc_PolCom] = IT.[Prc_PolCom]				
            ,R_IT.[Per_DscPolCom] = IT.[Per_DscPolCom]			
            ,R_IT.[Per_DscVisPolCom] = IT.[Per_DscVisPolCom]		
            ,R_IT.[Vlr_Verba] =	IT.[Vlr_Verba]	
            ,R_IT.[Qtd_PrzPolCom] = IT.[Qtd_PrzPolCom]			
            ,R_IT.[Des_MsgDesbloq] = IT.[Des_MsgDesbloq]			
            ,R_IT.[Prc_UniLiqPer] =	IT.[Prc_UniLiqPer]	
            ,R_IT.[Prc_LiqUltEnt] =	IT.[Prc_LiqUltEnt]		
            ,R_IT.[Cod_MtvRej] = IT.[Cod_MtvRej]			
            ,R_IT.[Des_MtvRej] = IT.[Des_MtvRej]				
            ,R_IT.[Per_ComGer] = IT.[Per_ComGer]				
            ,R_IT.[Vlr_ComGer] = IT.[Vlr_ComGer]				
            ,R_IT.[Per_ComSup] = IT.[Per_ComSup]				
            ,R_IT.[Vlr_ComSup] = IT.[Vlr_ComSup]				
            ,R_IT.[Per_ComGerOpe] = IT.[Per_ComGerOpe]			
            ,R_IT.[Vlr_ComGerOpe] =	IT.[Vlr_ComGerOpe] 		
            ,R_IT.[Per_ComSupOpe] =	IT.[Per_ComSupOpe]		
            ,R_IT.[Vlr_ComSupOpe] =	IT.[Vlr_ComSupOpe]		
            ,R_IT.[Per_VrbPar] = IT.[Per_VrbPar]			
            ,R_IT.[Vlr_VrbPar] = IT.[Vlr_VrbPar]				
            ,R_IT.[Per_VrbBon] = IT.[Per_VrbBon]				
            ,R_IT.[Vlr_VrbBon] = IT.[Vlr_VrbBon]				
            ,R_IT.[Prc_UniPde] = IT.[Prc_UniPde]				
            ,R_IT.[Per_DscPde] = IT.[Per_DscPde]			
            ,R_IT.[Prc_RefFpb] = IT.[Prc_RefFpb]				
            ,R_IT.[Cod_CSOSN] =	IT.[Cod_CSOSN]		
            ,R_IT.[Flg_PolPrm] = IT.[Flg_PolPrm]				
            ,R_IT.[Cod_PrjPde] = IT.[Cod_PrjPde]				
            ,R_IT.[Num_SeqPdc] = IT.[Num_SeqPdc]				
            ,R_IT.[Vlr_BasSbtRes] = IT.[Vlr_BasSbtRes] 			
            ,R_IT.[Vlr_SbtRes] = IT.[Vlr_SbtRes]			
            ,R_IT.[Num_IteCot] = IT.[Num_IteCot]
            ,R_IT.[Vlr_Bonificacao] = IT.[Vlr_Bonificacao]			
            ,R_IT.[Vlr_DscBonRat] =	IT.[Vlr_DscBonRat]	
            ,R_IT.[Prc_CusMinComMarkup] = IT.[Prc_CusMinComMarkup]		
            ,R_IT.[Vlr_BasVerba] = IT.[Vlr_BasVerba]	
            ,R_IT.[Vlr_VrbVdr] = IT.[Vlr_VrbVdr]			
            ,R_IT.[Per_MarkupCusCom] = IT.[Per_MarkupCusCom]			
            ,R_IT.[Tip_Sai] = IT.[Tip_Sai]	
            ,R_IT.[CodAnt] = IT.[CodAnt]				
            ,R_IT.[NovoCodigo] = IT.[NovoCodigo]							
            ,R_IT.[Per_AcrAlqIntFcp] = IT.[Per_AcrAlqIntFcp]			
            ,R_IT.[Vlr_IcmFcpDes] = IT.[Vlr_IcmFcpDes]		
            ,R_IT.[Vlr_Despes] = IT.[Vlr_Despes]			
            ,R_IT.[Vlr_BasDespes] = IT.[Vlr_BasDespes]			
            ,R_IT.[Per_PrvParIcm] =	IT.[Per_PrvParIcm]		
            ,R_IT.[Vlr_IcmParDes] =	IT.[Vlr_IcmParDes]		
            ,R_IT.[Vlr_IcmParRem] =	IT.[Vlr_IcmParRem]		
            ,R_IT.[Alq_IntIcmDes] =	IT.[Alq_IntIcmDes]		
            ,R_IT.[Cod_KitPrm] = IT.[Cod_KitPrm]			
            ,R_IT.[CST_Pis] = IT.[CST_Pis]			
            ,R_IT.[Vlr_BasPis] = IT.[Vlr_BasPis]				
            ,R_IT.[Alq_Pis] = IT.[Alq_Pis]			
            ,R_IT.[Vlr_Pis] = IT.[Vlr_Pis]				
            ,R_IT.[CST_Cofins] = IT.[CST_Cofins]				
            ,R_IT.[Vlr_BasCofins] = IT.[Vlr_BasCofins]			
            ,R_IT.[Alq_Cofins] = IT.[Alq_Cofins]			
            ,R_IT.[Vlr_Cofins] = IT.[Vlr_Cofins]				
            ,R_IT.[Per_MarBru] = IT.[Per_MarBru]				
            ,R_IT.[Vlr_VrbPdv] = IT.[Vlr_VrbPdv]				
            ,R_IT.[Vlr_BasCalSubTriEntMed] = IT.[Vlr_BasCalSubTriEntMed]	
            ,R_IT.[Per_RntBru] = IT.[Per_RntBru]
            ,R_IT.[Tip_BasRnt] = IT.[Tip_BasRnt]				
            ,R_IT.[Flg_UsaDebPresum] = IT.[Flg_UsaDebPresum]			
            ,R_IT.[Alq_IcmPresum] =	IT.[Alq_IcmPresum]	
            ,R_IT.[Vlr_DscBonDup] =	IT.[Vlr_DscBonDup]		
            ,R_IT.[Vlr_BasDscTri] =	IT.[Vlr_BasDscTri]		
            ,R_IT.[Per_DscTri] = IT.[Per_DscTri]			
            ,R_IT.[Alq_IcmDif] = IT.[Alq_IcmDif]				
            ,R_IT.[Vlr_IcmsDif] = IT.[Vlr_IcmsDif]				
            ,R_IT.[Qtd_PesVolImpFat] = IT.[Qtd_PesVolImpFat] 		
            ,R_IT.[Des_UnvPesVolImpFat] = IT.[Des_UnvPesVolImpFat]		
            ,R_IT.[Prc_UniPesVolImpFat] = IT.[Prc_UniPesVolImpFat]	
            ,R_IT.[Vlr_IcmsDeson] =	IT.[Vlr_IcmsDeson]
            ,R_IT.[Cod_MtvIcmsDeson] = IT.[Cod_MtvIcmsDeson]		
            ,R_IT.[Vlr_DscCalSuframa] =	IT.[Vlr_DscCalSuframa]	
            ,R_IT.[Flg_IncFis] = IT.[Flg_IncFis]		
            ,R_IT.[Alq_FcpIcm] = IT.[Alq_FcpIcm]				
            ,R_IT.[Vlr_FcpIcm] = IT.[Vlr_FcpIcm]				
            ,R_IT.[Alq_FcpSbt] = IT.[Alq_FcpSbt]				
            ,R_IT.[Vlr_FcpSbt] = IT.[Vlr_FcpSbt]				
            ,R_IT.[Alq_FcpSbtRet] = IT.[Alq_FcpSbtRet]			
            ,R_IT.[Vlr_FcpSbtRet] =	IT.[Vlr_FcpSbtRet]		
            ,R_IT.[Per_IcmDiferi] =	IT.[Per_IcmDiferi]		
            ,R_IT.[Vlr_IcmDiferi] =	IT.[Vlr_IcmDiferi]		
            ,R_IT.[Nom_UsuCor] = IT.[Nom_UsuCor]			
            ,R_IT.[Dat_UsuCor] = IT.[Dat_UsuCor]				
            ,R_IT.[Cod_MtvCor] = IT.[Cod_MtvCor]			
            ,R_IT.[Des_MtvCor] = IT.[Des_MtvCor]				
            ,R_IT.[Vlr_VrbOpe] = IT.[Vlr_VrbOpe]				
            ,R_IT.[Vlr_VrbSup] = IT.[Vlr_VrbSup]				
            ,R_IT.[Per_VrbVdr] = IT.[Per_VrbVdr]				
            ,R_IT.[Per_VrbOpe] = IT.[Per_VrbOpe]				
            ,R_IT.[Per_VrbSup] = IT.[Per_VrbSup]				
            ,R_IT.[Alq_EfeDas] = IT.[Alq_EfeDas]				
            ,R_IT.[Vlr_DscRat] = IT.[Vlr_DscRat]				
            ,R_IT.[Prc_PonFin] = IT.[Prc_PonFin]				
            ,R_IT.[Vlr_DspExt] = IT.[Vlr_DspExt]				
            ,R_IT.[Vlr_BasIpi] = IT.[Vlr_BasIpi]				
            ,R_IT.[Vlr_Ipi] = IT.[Vlr_Ipi] 			
            ,R_IT.[Alq_Ipi] = IT.[Alq_Ipi]				
            ,R_IT.[CST_Ipi] = IT.[CST_Ipi]				
            ,R_IT.[Cod_EnqIpi] = IT.[Cod_EnqIpi]				
            ,R_IT.[Cod_OriMer] = IT.[Cod_OriMer]				
            ,R_IT.[Prc_UniSemAcrIcm] = IT.[Prc_UniSemAcrIcm]		
            ,R_IT.[Flg_PrcUniAcrIcm] = IT.[Flg_PrcUniAcrIcm]		
            ,R_IT.[Prc_UniComAcrIcm] = IT.[Prc_UniComAcrIcm]		
            ,R_IT.[Per_RepIcms] = IT.[Per_RepIcms]		
            ,R_IT.[Vlr_BasIrf] = IT.[Vlr_BasIrf]			
            ,R_IT.[Alq_Irf] = IT.[Alq_Irf]			
            ,R_IT.[Vlr_Irf] = IT.[Vlr_Irf]				
            ,R_IT.[Qtd_GanCot] = IT.[Qtd_GanCot] 				
            ,R_IT.[Per_LinCot] = IT.[Per_LinCot]				
            ,R_IT.[Vlr_SbtRetAnt] = IT.[Vlr_SbtRetAnt] 			
            ,R_IT.[Vlr_BasCsl] = IT.[Vlr_BasCsl]			
            ,R_IT.[Alq_Csl] = IT.[Alq_Csl] 					
            ,R_IT.[Vlr_Csl] = IT.[Vlr_Csl]					
            ,R_IT.[Tip_PolCom] = IT.[Tip_PolCom]
        FROM BD_DW.dbo.R_PDVIT R_IT
			INNER JOIN [RemoteServerName].[DMD].[dbo].[PDVIT] IT 
						ON  R_IT.[Cod_Estabe] = IT.[Cod_Estabe]  
					AND R_IT.[Cod_Pedido] = IT.[Cod_Pedido]
                    AND R_IT.[Cod_Produto] = IT.[Cod_Produto] 
					AND R_IT.[Cod_Lote]  = IT.[Cod_Lote] 	
        WHERE 
            IT.[Cod_Estabe] = 1
        AND (R_IT.[Qtd_Solicitado] <> IT.[Qtd_Solicitado]			
                    OR R_IT.[Qtd_Acerto] <> IT.[Qtd_Acerto]
                    OR R_IT.[Qtd_Pedido] <> IT.[Qtd_Pedido]		
                    OR R_IT.[Qtd_Bonificacao] <> IT.[Qtd_Bonificacao]		
                    OR R_IT.[Qtd_Pendente] <> 	IT.[Qtd_Pendente]	
                    OR R_IT.[Flg_PrcUniDsc] <> IT.[Flg_PrcUniDsc]			
                    OR R_IT.[Per_Desconto] <> IT.[Per_Desconto]	
                    OR R_IT.[Prc_Unitario] <> IT.[Prc_Unitario]				
                    OR R_IT.[Tip_Aux] <> IT.[Tip_Aux]			
                    OR R_IT.[Ctrl_Tributacao] <> IT.[Ctrl_Tributacao]	
                    OR R_IT.[Cod_ClaTri] <> IT.[Cod_ClaTri]	
                    OR R_IT.[Alq_Icms] <> IT.[Alq_Icms]			
                    OR R_IT.[Vlr_BasIcmsNor] <> IT.[Vlr_BasIcmsNor]			
                    OR R_IT.[Vlr_IcmsNor] <> IT.[Vlr_IcmsNor]		
                    OR R_IT.[Vlr_RepIcms] <> IT.[Vlr_RepIcms]			
                    OR R_IT.[Vlr_BasRepIcms] <> IT.[Vlr_BasRepIcms]			
                    OR R_IT.[Vlr_SubsTrib] <> IT.[Vlr_SubsTrib]		
                    OR R_IT.[Vlr_PrdSubTri] <>	IT.[Vlr_PrdSubTri]		
                    OR R_IT.[Vlr_BasSubsTrib] <> IT.[Vlr_BasSubsTrib]		
                    OR R_IT.[Vlr_IcmsTri] <> IT.[Vlr_IcmsTri]	
                    OR R_IT.[Vlr_BasIcmsTri] <> IT.[Vlr_BasIcmsTri]			
                    OR R_IT.[Vlr_Isento] <> IT.[Vlr_Isento]		
                    OR R_IT.[Vlr_DscTri] <> IT.[Vlr_DscTri]				
                    OR R_IT.[Vlr_Bruto] <>	IT.[Vlr_Bruto]		
                    OR R_IT.[Cod_Promocao] <> IT.[Cod_Promocao]				
                    OR R_IT.[Desconto] <> IT.[Desconto]			
                    OR R_IT.[Flg_BlqInfPar] <> IT.[Flg_BlqInfPar]			
                    OR R_IT.[Qtd_PrzMax] <> IT.[Qtd_PrzMax]			
                    OR R_IT.[Per_Descon] <> IT.[Per_Descon]				
                    OR R_IT.[Per_DscVis] <> IT.[Per_DscVis]				
                    OR R_IT.[C_VlrDesconto] <>	IT.[C_VlrDesconto]	
                    OR R_IT.[C_PrcUni] <> IT.[C_PrcUni]			
                    OR R_IT.[C_PerDscIte] <> IT.[C_PerDscIte]				
                    OR R_IT.[C_PrcTotal] <> IT.[C_PrcTotal]		
                    OR R_IT.[C_VlrLiquido] <> IT.[C_VlrLiquido]			
                    OR R_IT.[Prc_Tabela] <> IT.[Prc_Tabela]			
                    OR R_IT.[Des_Und] <> IT.[Des_Und]			
                    OR R_IT.[Qtd_AprPdv] <> IT.[Qtd_AprPdv]				
                    OR R_IT.[Des_UndVen] <> IT.[Des_UndVen]				
                    OR R_IT.[Prc_TabBru] <> IT.[Prc_TabBru]				
                    OR R_IT.[Vlr_Outros] <> IT.[Vlr_Outros]				
                    OR R_IT.[Flg_Entreg] <> IT.[Flg_Entreg]				
                    OR R_IT.[Qtd_ImpFat] <> IT.[Qtd_ImpFat]				
                    OR R_IT.[Prc_UniImpFat] <> IT.[Prc_UniImpFat]			
                    OR R_IT.[Fat_CnvImpFat] <> IT.[Fat_CnvImpFat]			
                    OR R_IT.[Qtd_Pra] <> IT.[Qtd_Pra]			
                    OR R_IT.[Qtd_Dep] <> IT.[Qtd_Dep]				
                    OR R_IT.[Prc_MaxCon] <> IT.[Prc_MaxCon]				
                    OR R_IT.[Prc_Fabric] <> IT.[Prc_Fabric]				
                    OR R_IT.[Num_SeqDig] <> IT.[Num_SeqDig]			
                    OR R_IT.[Nom_UsuDesbloq] <> IT.[Nom_UsuDesbloq]			
                    OR R_IT.[Des_UnvImpFat] <>	IT.[Des_UnvImpFat]	
                    OR R_IT.[Des_AprImpFat] <>	IT.[Des_AprImpFat]		
                    OR R_IT.[Flg_VctLic] <> IT.[Flg_VctLic]			
                    OR R_IT.[Per_Rnt] <> IT.[Per_Rnt]			
                    OR R_IT.[Prc_BasRnt] <> IT.[Prc_BasRnt] 				
                    OR R_IT.[Per_Comissao] <> IT.[Per_Comissao]			
                    OR R_IT.[Per_ComTlmkt] <> IT.[Per_ComTlmkt]				
                    OR R_IT.[Per_ComTra] <> IT.[Per_ComTra]			
                    OR R_IT.[Vlr_Comissao] <> IT.[Vlr_Comissao] 				
                    OR R_IT.[Vlr_ComTlmkt] <> IT.[Vlr_ComTlmkt]				
                    OR R_IT.[Val_ComTra] <> IT.[Val_ComTra]			
                    OR R_IT.[Cod_ModBasCalIcm] <> IT.[Cod_ModBasCalIcm] 		
                    OR R_IT.[Cod_ModBasCalIcmSbt] <> IT.[Cod_ModBasCalIcmSbt]		
                    OR R_IT.[Per_RedBasCalIcm] <> IT.[Per_RedBasCalIcm]	
                    OR R_IT.[Per_RedBasCalIcmSbt] <> IT.[Per_RedBasCalIcmSbt]		
                    OR R_IT.[Alq_IcmSbt] <> IT.[Alq_IcmSbt]	
                    OR R_IT.[Vlr_BasTri] <> IT.[Vlr_BasTri]				
                    OR R_IT.[Alq_AgrSbt] <> IT.[Alq_AgrSbt]				
                    OR R_IT.[Id_PolCom] <>	IT.[Id_PolCom]		
                    OR R_IT.[Flg_Verba] <>	IT.[Flg_Verba]			
                    OR R_IT.[Prc_PolCom] <> IT.[Prc_PolCom]				
                    OR R_IT.[Per_DscPolCom] <> IT.[Per_DscPolCom]			
                    OR R_IT.[Per_DscVisPolCom] <> IT.[Per_DscVisPolCom]		
                    OR R_IT.[Vlr_Verba] <>	IT.[Vlr_Verba]	
                    OR R_IT.[Qtd_PrzPolCom] <> IT.[Qtd_PrzPolCom]			
                    OR R_IT.[Des_MsgDesbloq] <> IT.[Des_MsgDesbloq]			
                    OR R_IT.[Prc_UniLiqPer] <>	IT.[Prc_UniLiqPer]	
                    OR R_IT.[Prc_LiqUltEnt] <>	IT.[Prc_LiqUltEnt]		
                    OR R_IT.[Cod_MtvRej] <> IT.[Cod_MtvRej]			
                    OR R_IT.[Des_MtvRej] <> IT.[Des_MtvRej]				
                    OR R_IT.[Per_ComGer] <> IT.[Per_ComGer]				
                    OR R_IT.[Vlr_ComGer] <> IT.[Vlr_ComGer]				
                    OR R_IT.[Per_ComSup] <> IT.[Per_ComSup]				
                    OR R_IT.[Vlr_ComSup] <> IT.[Vlr_ComSup]				
                    OR R_IT.[Per_ComGerOpe] <> IT.[Per_ComGerOpe]			
                    OR R_IT.[Vlr_ComGerOpe] <>	IT.[Vlr_ComGerOpe] 		
                    OR R_IT.[Per_ComSupOpe] <>	IT.[Per_ComSupOpe]		
                    OR R_IT.[Vlr_ComSupOpe] <>	IT.[Vlr_ComSupOpe]		
                    OR R_IT.[Per_VrbPar] <> IT.[Per_VrbPar]			
                    OR R_IT.[Vlr_VrbPar] <> IT.[Vlr_VrbPar]				
                    OR R_IT.[Per_VrbBon] <> IT.[Per_VrbBon]				
                    OR R_IT.[Vlr_VrbBon] <> IT.[Vlr_VrbBon]				
                    OR R_IT.[Prc_UniPde] <> IT.[Prc_UniPde]				
                    OR R_IT.[Per_DscPde] <> IT.[Per_DscPde]			
                    OR R_IT.[Prc_RefFpb] <> IT.[Prc_RefFpb]				
                    OR R_IT.[Cod_CSOSN] <>	IT.[Cod_CSOSN]		
                    OR R_IT.[Flg_PolPrm] <> IT.[Flg_PolPrm]				
                    OR R_IT.[Cod_PrjPde] <> IT.[Cod_PrjPde]				
                    OR R_IT.[Num_SeqPdc] <> IT.[Num_SeqPdc]				
                    OR R_IT.[Vlr_BasSbtRes] <> IT.[Vlr_BasSbtRes] 			
                    OR R_IT.[Vlr_SbtRes] <> IT.[Vlr_SbtRes]			
                    OR R_IT.[Num_IteCot] <> IT.[Num_IteCot]
                    OR R_IT.[Vlr_Bonificacao] <> IT.[Vlr_Bonificacao]			
                    OR R_IT.[Vlr_DscBonRat] <>	IT.[Vlr_DscBonRat]	
                    OR R_IT.[Prc_CusMinComMarkup] <> IT.[Prc_CusMinComMarkup]		
                    OR R_IT.[Vlr_BasVerba] <> IT.[Vlr_BasVerba]	
                    OR R_IT.[Vlr_VrbVdr] <> IT.[Vlr_VrbVdr]			
                    OR R_IT.[Per_MarkupCusCom] <> IT.[Per_MarkupCusCom]			
                    OR R_IT.[Tip_Sai] <> IT.[Tip_Sai]	
                    OR R_IT.[CodAnt] <> IT.[CodAnt]				
                    OR R_IT.[NovoCodigo] <> IT.[NovoCodigo]							
                    OR R_IT.[Per_AcrAlqIntFcp] <> IT.[Per_AcrAlqIntFcp]			
                    OR R_IT.[Vlr_IcmFcpDes] <> IT.[Vlr_IcmFcpDes]		
                    OR R_IT.[Vlr_Despes] <> IT.[Vlr_Despes]			
                    OR R_IT.[Vlr_BasDespes] <> IT.[Vlr_BasDespes]			
                    OR R_IT.[Per_PrvParIcm] <>	IT.[Per_PrvParIcm]		
                    OR R_IT.[Vlr_IcmParDes] <>	IT.[Vlr_IcmParDes]		
                    OR R_IT.[Vlr_IcmParRem] <>	IT.[Vlr_IcmParRem]		
                    OR R_IT.[Alq_IntIcmDes] <>	IT.[Alq_IntIcmDes]		
                    OR R_IT.[Cod_KitPrm] <> IT.[Cod_KitPrm]			
                    OR R_IT.[CST_Pis] <> IT.[CST_Pis]			
                    OR R_IT.[Vlr_BasPis] <> IT.[Vlr_BasPis]				
                    OR R_IT.[Alq_Pis] <> IT.[Alq_Pis]			
                    OR R_IT.[Vlr_Pis] <> IT.[Vlr_Pis]				
                    OR R_IT.[CST_Cofins] <> IT.[CST_Cofins]				
                    OR R_IT.[Vlr_BasCofins] <> IT.[Vlr_BasCofins]			
                    OR R_IT.[Alq_Cofins] <> IT.[Alq_Cofins]			
                    OR R_IT.[Vlr_Cofins] <> IT.[Vlr_Cofins]				
                    OR R_IT.[Per_MarBru] <> IT.[Per_MarBru]				
                    OR R_IT.[Vlr_VrbPdv] <> IT.[Vlr_VrbPdv]				
                    OR R_IT.[Vlr_BasCalSubTriEntMed] <> IT.[Vlr_BasCalSubTriEntMed]	
                    OR R_IT.[Per_RntBru] <> IT.[Per_RntBru]
                    OR R_IT.[Tip_BasRnt] <> IT.[Tip_BasRnt]				
                    OR R_IT.[Flg_UsaDebPresum] <> IT.[Flg_UsaDebPresum]			
                    OR R_IT.[Alq_IcmPresum] <>	IT.[Alq_IcmPresum]	
                    OR R_IT.[Vlr_DscBonDup] <>	IT.[Vlr_DscBonDup]		
                    OR R_IT.[Vlr_BasDscTri] <>	IT.[Vlr_BasDscTri]		
                    OR R_IT.[Per_DscTri] <> IT.[Per_DscTri]			
                    OR R_IT.[Alq_IcmDif] <> IT.[Alq_IcmDif]				
                    OR R_IT.[Vlr_IcmsDif] <> IT.[Vlr_IcmsDif]				
                    OR R_IT.[Qtd_PesVolImpFat] <> IT.[Qtd_PesVolImpFat] 		
                    OR R_IT.[Des_UnvPesVolImpFat] <> IT.[Des_UnvPesVolImpFat]		
                    OR R_IT.[Prc_UniPesVolImpFat] <> IT.[Prc_UniPesVolImpFat]	
                    OR R_IT.[Vlr_IcmsDeson] <>	IT.[Vlr_IcmsDeson]
                    OR R_IT.[Cod_MtvIcmsDeson] <> IT.[Cod_MtvIcmsDeson]		
                    OR R_IT.[Vlr_DscCalSuframa] <>	IT.[Vlr_DscCalSuframa]	
                    OR R_IT.[Flg_IncFis] <> IT.[Flg_IncFis]		
                    OR R_IT.[Alq_FcpIcm] <> IT.[Alq_FcpIcm]				
                    OR R_IT.[Vlr_FcpIcm] <> IT.[Vlr_FcpIcm]				
                    OR R_IT.[Alq_FcpSbt] <> IT.[Alq_FcpSbt]				
                    OR R_IT.[Vlr_FcpSbt] <> IT.[Vlr_FcpSbt]				
                    OR R_IT.[Alq_FcpSbtRet] <> IT.[Alq_FcpSbtRet]			
                    OR R_IT.[Vlr_FcpSbtRet] <>	IT.[Vlr_FcpSbtRet]		
                    OR R_IT.[Per_IcmDiferi] <>	IT.[Per_IcmDiferi]		
                    OR R_IT.[Vlr_IcmDiferi] <>	IT.[Vlr_IcmDiferi]		
                    OR R_IT.[Nom_UsuCor] <> IT.[Nom_UsuCor]			
                    OR R_IT.[Dat_UsuCor] <> IT.[Dat_UsuCor]				
                    OR R_IT.[Cod_MtvCor] <> IT.[Cod_MtvCor]			
                    OR R_IT.[Des_MtvCor] <> IT.[Des_MtvCor]				
                    OR R_IT.[Vlr_VrbOpe] <> IT.[Vlr_VrbOpe]				
                    OR R_IT.[Vlr_VrbSup] <> IT.[Vlr_VrbSup]				
                    OR R_IT.[Per_VrbVdr] <> IT.[Per_VrbVdr]				
                    OR R_IT.[Per_VrbOpe] <> IT.[Per_VrbOpe]				
                    OR R_IT.[Per_VrbSup] <> IT.[Per_VrbSup]				
                    OR R_IT.[Alq_EfeDas] <> IT.[Alq_EfeDas]				
                    OR R_IT.[Vlr_DscRat] <> IT.[Vlr_DscRat]				
                    OR R_IT.[Prc_PonFin] <> IT.[Prc_PonFin]				
                    OR R_IT.[Vlr_DspExt] <> IT.[Vlr_DspExt]				
                    OR R_IT.[Vlr_BasIpi] <> IT.[Vlr_BasIpi]				
                    OR R_IT.[Vlr_Ipi] <> IT.[Vlr_Ipi] 			
                    OR R_IT.[Alq_Ipi] <> IT.[Alq_Ipi]				
                    OR R_IT.[CST_Ipi] <> IT.[CST_Ipi]				
                    OR R_IT.[Cod_EnqIpi] <> IT.[Cod_EnqIpi]				
                    OR R_IT.[Cod_OriMer] <> IT.[Cod_OriMer]				
                    OR R_IT.[Prc_UniSemAcrIcm] <> IT.[Prc_UniSemAcrIcm]		
                    OR R_IT.[Flg_PrcUniAcrIcm] <> IT.[Flg_PrcUniAcrIcm]		
                    OR R_IT.[Prc_UniComAcrIcm] <> IT.[Prc_UniComAcrIcm]		
                    OR R_IT.[Per_RepIcms] <> IT.[Per_RepIcms]		
                    OR R_IT.[Vlr_BasIrf] <> IT.[Vlr_BasIrf]			
                    OR R_IT.[Alq_Irf] <> IT.[Alq_Irf]
                    OR R_IT.[Vlr_Irf] <> IT.[Vlr_Irf]
                    OR R_IT.[Qtd_GanCot] <> IT.[Qtd_GanCot]
                    OR R_IT.[Per_LinCot] <> IT.[Per_LinCot]
                    OR R_IT.[Vlr_SbtRetAnt] <> IT.[Vlr_SbtRetAnt]
                    OR R_IT.[Vlr_BasCsl] <> IT.[Vlr_BasCsl]
                    OR R_IT.[Alq_Csl] <> IT.[Alq_Csl] 					
                    OR R_IT.[Vlr_Csl] <> IT.[Vlr_Csl]
                    OR R_IT.[Tip_PolCom] <> IT.[Tip_PolCom])
                	END
	COMMIT TRANSACTION;
END TRY
    BEGIN CATCH

        ROLLBACK TRANSACTION;

        DECLARE @ErrorMessage NVARCHAR(4000);
        DECLARE @ErrorSeverity INT;
        DECLARE @ErrorState INT;

        SELECT 
            @ErrorMessage = ERROR_MESSAGE(),
            @ErrorSeverity = ERROR_SEVERITY(),
            @ErrorState = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH;
