
INSERT INTO R_PRLOT ([Cod_Produt]
      ,[Cod_Lote]
      ,[Dat_Vencim]
      ,[Cod_Etique]
      ,[Qtd_Fisico]
      ,[Qtd_Solicitado]
      ,[Qtd_Saldo]
      ,[Qtd_FisPra]
      ,[Qtd_SolPra]
      ,[Qtd_SldPra]
      ,[Qtd_FisDep]
      ,[Qtd_SolDep]
      ,[Qtd_SldDep]
      ,[Dat_Fabric]
      ,[CodAnt]
      ,[NovoCodigo]
      ,[Cod_Estabe]
      ,[Cod_Dep]
      ,[Dat_Entrada]
      ,[Fat_CnvAprEmbPad])
SELECT [Cod_Produt]
      ,[Cod_Lote]
      ,[Dat_Vencim]
      ,[Cod_Etique]
      ,[Qtd_Fisico]
      ,[Qtd_Solicitado]
      ,[Qtd_Saldo]
      ,[Qtd_FisPra]
      ,[Qtd_SolPra]
      ,[Qtd_SldPra]
      ,[Qtd_FisDep]
      ,[Qtd_SolDep]
      ,[Qtd_SldDep]
      ,[Dat_Fabric]
      ,[CodAnt]
      ,[NovoCodigo]
      ,[Cod_Estabe]
      ,[Cod_Dep]
      ,[Dat_Entrada]
      ,[Fat_CnvAprEmbPad]
  FROM PROD_2023.[dbo].[PRLOT]
  WHERE Cod_Estabe=1