/****** Script do comando SelectTopNRows de SSMS  ******/
INSERT INTO [R_RGTRI] ([Cod_RegTri]
      ,[Des_RegTri]
      ,[Ctrl_ImpIcmTotNfs]
      ,[Flg_ConsumFin]
      ,[Msg_Nf]
      ,[Flg_RegEspTrb]
      ,[Flg_DscIcmOrgPub]
      ,[Flg_DscIcmOrgPubAcr]
      ,[CodAnt]
      ,[NovoCodigo]
      ,[Flg_UsaCfoSbtSaiIntGenSim]
      ,[Flg_UsaCrePresum]
      ,[Flg_UsaDebPresum]
      ,[Flg_DatEmiPrdCip]
      ,[Flg_DatAntUltAtuPrdCip]
      ,[Cod_Canal]
      ,[Id_MensagReg]
      ,[Id_MsgReg2]
      ,[Flg_DscSbtOrgPub]
      ,[Flg_SujAntIcm])
SELECT [Cod_RegTri]
      ,[Des_RegTri]
      ,[Ctrl_ImpIcmTotNfs]
      ,[Flg_ConsumFin]
      ,[Msg_Nf]
      ,[Flg_RegEspTrb]
      ,[Flg_DscIcmOrgPub]
      ,[Flg_DscIcmOrgPubAcr]
      ,[CodAnt]
      ,[NovoCodigo]
      ,[Flg_UsaCfoSbtSaiIntGenSim]
      ,[Flg_UsaCrePresum]
      ,[Flg_UsaDebPresum]
      ,[Flg_DatEmiPrdCip]
      ,[Flg_DatAntUltAtuPrdCip]
      ,[Cod_Canal]
      ,[Id_MensagReg]
      ,[Id_MsgReg2]
      ,[Flg_DscSbtOrgPub]
      ,[Flg_SujAntIcm]
  FROM PROD_2023.[dbo].[RGTRI]