/****** Script do comando SelectTopNRows de SSMS  ******/
INSERT INTO [R_RMATV]([Codigo]
      ,[Descricao]
      ,[CodAnt]
      ,[NovoCodigo]
      ,[Flg_RedAlqVenPisCof]
      ,[Flg_BlqCtrLicSauVen]
      ,[Flg_BlqPdvLicAnvVen]
      ,[Flg_BlqPdvLicCrfVen]
      ,[Flg_BlqPdvAlvFunVen]
      ,[Flg_BlqCriLicCot]
      ,[Cod_EnqIpi]
      ,[Flg_BlqPdvLicVen])
SELECT [Codigo]
      ,[Descricao]
      ,[CodAnt]
      ,[NovoCodigo]
      ,[Flg_RedAlqVenPisCof]
      ,[Flg_BlqCtrLicSauVen]
      ,[Flg_BlqPdvLicAnvVen]
      ,[Flg_BlqPdvLicCrfVen]
      ,[Flg_BlqPdvAlvFunVen]
      ,[Flg_BlqCriLicCot]
      ,[Cod_EnqIpi]
      ,[Flg_BlqPdvLicVen]
  FROM PROD_2023.[dbo].RMATV