-- Ultimo Isn_Rotina Atualizado: 776
/*
Select * From ROTIN Order By Wbs_Rotina
Select * From ROTIN Order By Isn_Rotina desc 
*/

SET NOCOUNT ON
GO

Declare @DesRotina varchar(50)

Delete
From ROTIN

-- CADASTROS
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('10','CADASTROS',1,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1001','Contadores',5,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100101','Contadores - Manutenção',6,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1002','Estabelecimentos',628,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100201','Estabelecimentos - Manutenção',629,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100202','Gerar Mix',630,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1005','Produto',2,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100501','Produto - Manutenção',49,0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           Values ('100502', 'Produto - Manutenção - Cadastro', 706, 0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           Values ('100503', 'Produto - Manutenção - WMS/Estoque', 707, 0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           Values ('100504', 'Produto - Manutenção - Preços', 708, 0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           Values ('100505', 'Produto - Manutenção - Fiscal', 709, 0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           values ('100506', 'Produto - Manutenção - Outros Dados', 710, 0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           values ('100507', 'Produto - Manutenção - Hospitalar', 711, 0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           values ('100508', 'Produto - Manutenção - Políticas', 712, 0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           values ('100509', 'Produto - Manutenção - Benefícios', 713, 0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100510','Produto - Hist. de Preços',676,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100511','Produto - Entradas ',677,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100512','Produto - Saídas ',678,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100513','Produto - Pend. Faturamento',679,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100514','Produto - Cópia',680,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100515','Produto - Posição de Produtos',701,0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           values ('100516', 'Produto - Apresentação', 704, 0)
insert into ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           values ('100517', 'Produto - Detalhes', 705, 0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100518','Produto - Pend. Faturamento - Ped. Venda',725,0)		   
		   

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1006','Classificação de Produtos',45,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100601','Classificação de Produtos - Manutenção',51,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1007','Grupos de Preços',3,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100701','Grupos de Preços - Manutenção',4,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1008','Substâncias Básicas',46,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100801','Substâncias Básicas - Manutenção',52,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1009','Classificação Tributária',231,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('100901','Classificação Tributária - Manutenção',232,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1010','Clientes',7,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101001','Clientes - Manutenção',53,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101002','Dados de Controle',102,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101003','Alteração Cadastral',698,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1011','Ocorrências de Clientes',376,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101101','Ocorrências de Clientes - Inclusão',377,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101102','Ocorrências de Clientes - Alteração',378,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101103','Ocorrências de Clientes - Exclusão',379,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1012','Grupos de Clientes',254,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101201','Grupos de Clientes - Manutenção',255,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1013','Ramos de Atividade',40,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101301','Ramos de Atividade - Manutenção',54,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1014','Informações de Crédito',41,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101401','Informações de Crédito - Manutenção',55,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1015','Fornecedores',13,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101501','Fornecedores - Manutenção',56,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1016','Favorecidos',249,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101601','Favorecidos - Manutenção',250,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1017','Fabricantes',163,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101701','Fabricantes - Manutenção',164,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1018','Turno de Atividade',572,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1019','Grupo de Atividade',573,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('101901','Grupo de Atividade - Manutenção',726,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1020','Equipamentos',608,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1021','Gerências',33,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102101','Gerências - Manutenção',57,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1022','Supervisores',465,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102201','Supervisores - Manutenção',466,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1025','Vendedores',32,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102501','Vendedores - Manutenção',58,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102504','Verbas de Vendedores - Manutenção',506,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1026','Origens de Pedidos de Venda',714,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102601','Origens de Pedidos de Venda - Inclusão',715,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102602','Origens de Pedidos de Venda - Alteração',716,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102603','Origens de Pedidos de Venda - Exclusão',717,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1027','Políticas de Comercialização',396,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102701','Políticas de Comercialização - Inclusão',397,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102702','Políticas de Comercialização - Alteração',398,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102703','Políticas de Comercialização - Exclusão',399,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1028','Tipos de Transações',185,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102801','Tipos de Transações - Manutenção',186,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1029','Tabelas de Prazos',311,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('102901','Tabelas de Prazos - Manutenção',312,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1030','Tabelas de Comissões',34,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('103001','Tabelas de Comissões - Manutenção',59,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1031','Profissionais',406,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('103101','Profissionais - Manutenção',407,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1032','Motivos de Vendas Negativas',302,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('103201','Motivos de Vendas Negativas - Manutenção',303,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1035','Transportadoras',36,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('103501','Transportadoras - Manutenção',60,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1040','Funcionarios',37,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('104001','Funcionarios - Manutenção',61,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('104005','Consulta Requisicões',138,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('104010','Relatório Resumo de Requisições',139,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1045','Bancos',38,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('104501','Bancos - Manutenção',62,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1050','Agentes Cobradores',39,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('105001','Agentes Cobradores - Manutenção',63,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1060','Tipos de Cobrança',170,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('106001','Tipos de Cobrança - Manutenção',171,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1064','Países',750,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1065','Estados da Federação',42,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('106501','Estados da Federação - Manutenção',64,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1066','Códigos de Benefícios Fiscais',683,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('106601','Códigos de Benefícios Fiscais - Manutenção',684,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1067','Macro / Micro Regiões',43,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('106701','Macro / Micro Regiões - Manutenção',65,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1068','Cidades / Bairros',44,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('106801','Cidades / Bairros - Manutenção',66,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1069','Rotas',209,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('106901','Rotas - Manutenção',210,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1070','Roteiros de Visitas',404,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107001','Roteiros de Visitas - Manutenção',405,0)		   
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1071','Código da Situação Tributária',603,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107101','Código da Situação Tributária - Manutenção',604,0)	   
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1072','Códigos Fiscais de Operação',47,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107201','Códigos Fiscais de Operação - Manutenção',21,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1073','Códigos de Receitas',595,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107301','Códigos de Receitas - Manutenção',596,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1074','Nomenclatura Comum do Mercosul (NCM)',520,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107401','NCM - Manutenção',521,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1075','Código Especificador da Subst.Tributária (CEST)',568,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107501','CEST - Manutenção',569,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1076','Grupos de Listas Portaria 344',581,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107601','Grupos de Listas Portaria 344 - Manutenção',582,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1077','Livros Registro Portaria 344',579,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107701','Livros Registro Portaria 344 - Manutenção',580,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107702','Livros Registro Portaria 344 - Impressão',469,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1078','AIDF',308,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107801','AIDF - Manutenção',309,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1079','Regime de Tributação',233,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('107901','Regime de Tributação - Manutenção',234,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1080','Tabela de Taxas de Serviços - SUFRAMA',499,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108001','Tabela de Taxas de Serviços - SUFRAMA - Manutenção',500,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1081','Tipos de Movimentação de Estoque',48,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108101','Tipos de Mov. de Estoque - Manutenção',68,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1082','Tipos de Documentos',266,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108201','Tipos de Documentos - Manutenção',267,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1083','Tabela de Impostos - Cupom Fiscal',575,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108301','Tabela de Impostos - Cupom Fiscal - Manutenção',576,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1084','Contas Partidas',277,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108401','Contas Partidas - Manutenção',278,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1085','Histórico de Contas Partidas',284,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108501','Histórico de Contas Partidas -Manutenção',285,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1086','Centro de Custo',348,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108601','Centro de Custo -Manutenção',349,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1087','Plano de Contas Gerencial',350,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108701','Plano de Contas Gerencial -Manutenção',351,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108702','Plano de Contas Gerencial -Reprocessamento',528,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1088','Histórico Gerencial',513,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108801','Histórico Gerencial -Manutenção',514,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1089','Lançamento Padrão',515,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('108901','Lançamento Padrão -Manutenção',516,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1090','D.R.E. Gerencial',517,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('109001','D.R.E. Gerencial -Manutenção',518,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1091','Códigos de Receitas',625,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1092','Plano de Contas - Contábil',222,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('109201','Plano de Contas - Contábil - Manutenção',224,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1093','Localização Contábil',279,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('109301','Localização Contábil - Manutenção',281,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1094','Histórico Contábil',282,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('109401','Histórico Contábil - Manutenção',283,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1095','Cadastros Genéricos',681,0)		   
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('109501','Cadastros Genéricos - Manutenção',682,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1096','Incentivos Fiscais',740,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('109601','Incentivos Fiscais - Manutenção',741,0)		   		   

-- VENDAS / FATURAMENTO
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('15','VENDAS / FATURAMENTO',17,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1501','Pedidos de Venda',18,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150101','Pedidos de Venda - Inclusão',19,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150102','Pedidos de Venda - Alteração',370,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150103','Pedidos de Venda - Exclusão',371,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150104','Visualização de Pedido(Telemarketing) de Terceiros',479,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150105','Visualização de Pedido(Web/Edi/Mob) de Terceiros',649,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150106','Manut. Pedido de Terceiros',140,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150108','Reabertura de Pedidos',182,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150109','Desbloqueio Financeiro',23,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150110','Desbloqueio Rentabilidade',354,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150111','Desbloqueio Documentação',374,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150112','Fechamento de Requisições',69,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150113','Fechamento de Vales',126,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150114','Manut.Comissão por Pedido',292,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150115','Consultar Rentabilidade',373,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150116','Consultar Resumo dos Pedidos',482,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150117','Descrição Diferenciada do Ítem',527,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150118','Pedidos Matriz x Filial',571,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150119','Manutenção de Observação de Pedido de Venda.',693,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150120','Bloqueia Alteração de Vendedor em Ped. Venda',747,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150199','Operações Especiais',24,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1502','Consignação',733,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150201','Consignação - Manutenção',734,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1503','OPME',735,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150301','OPME - Manutenção',736,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1504','Pedidos Eletrônicos',400,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('150401','Pedidos Eletrônicos - Manutenção',401,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1505','Cotações',172,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1507','Pedidos Remotos',184,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1510','Conferência de Pedidos',260,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('151001','Conferência de Pedidos - Inclusão',261,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('151002','Conferência de Pedidos - Bloqueia Alt.quantidade',367,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('151003','Conferência de Pedidos - Alteração',368,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('151004','Conferência de Pedidos - Exclusão',369,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1511','Auditoria de Conferência',737,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1520','Faturamento de Pedidos',70,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152001','Correção de Pedidos',197,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152002','Emissão de Nota Fiscal',198,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152003','Reimpressão de Nota Fiscal',199,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152004','Monitor NFE - Envia',667,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152005','Monitor NFE - DANFE',668,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152006','Monitor NFE - Cancela',669,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152007','Monitor NFE - C. Correção',670,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152008','Monitor NFE - Storage',671,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152009','Monitor NFE - Gerar XML',672,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152010','Monitor NFE - Inutilização',673,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152011','Monitor NFE - Cancelamento Gerencial',697,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152012','Monitor NFE - Valida XML',674,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152013','Monitor NFE - Configura',675,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1521','Faturamento Especial',289,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1522','Romaneio de Notas',219,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152201','Romaneio de Notas - Inclusão',220,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152202','Romaneio de Notas - Alteração',541,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152203','Romaneio de Notas - Exclusão',542,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1523','Despacho de Pedidos',71,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1524','Retorno de Entregas',129,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1525','Emissão de Bloquetes',72,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1528','Objetivo de Vendedores',73,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('152801','Objetivo de Vendedores - Manutenção',74,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1530','Promoções',75,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('153001','Promoções - Inclusão',76,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('153002','Promoções - Alteração',489,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('153003','Promoções - Exclusão',490,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1531','Bonificações',491,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('153101','Bonificações - Inclusão',492,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('153102','Bonificações - Alteração',493,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('153103','Bonificações - Exclusão',494,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1535','Bloqueio de Vendas',77,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('153501','Bloqueio de Vendas - Manutenção',78,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1540','Parcerias de Clientes',236,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('154001','Parcerias de Clientes - Manutenção',237,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1545','Geração de Roteiro de Visitas',304,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1575','Mala Direta',298,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1580','Exportação',259,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1585','Importação',322,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1590','Relatórios',106,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159005','Nível de Serviço - Pedidos de Vendas',262,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159010','Vendas por Fabricante',120,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159011','Vendas por Vendedor',122,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159012','Vendas por Cliente',107,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159013','Vendas por Produto',133,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159030','Rastreamento de Produto',204,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159032','Rentabilidade',299,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159033','Relatório - Fechamento Estoque x Vendas',360,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159035','Acompanhamento de Objetivos de Vendas',189,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159037','Acompanhamento de Parcerias de Clientes',239,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159045','Resultado de Promoções',121,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159050','Rel de Clientes por Estado, Cidade, Bair',108,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159052','Informações de Crédito de Clientes',173,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159053','Licenças de Clientes',313,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159054','Relação de Clientes (Filtro:Lim.Crédito)',193,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159060','Bloco de Pedidos',174,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159070','Relação de N.F. com Comissões',175,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159071','Relação de Notas de Saídas com Impostos',229,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159072','Relação de Ítens da Nota Fiscal',205,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159073','Detalhamento de Política de Comercialização',609,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159074','Relação Detalhada de Saídas de Ítens',290,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159075','Relação de N.F. por Transportadoras',235,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159076','Espelho de Nota de Saída',257,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159077','Relação de Vendedores x Gerênte',323,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159078','Relação de Pedidos de Vendas',329,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159079','Relatório de Positivação de Clientes',503,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159080','Relação de Notas Fiscais (Pedido Eletrônico)',577,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159081','Relação de NF com Comissão por Política',702,0)  -- Relação de NF com Comissão Ativa/Passiva por Política
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159082','Relação de Comissão sobre Rentabilidade',703,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159083','Relação de Pedido/Prod com Ruptura na Conferência',616,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('1591','EMails XML/DANFE e Boletos',689,0)		   
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('159101','Envio/Reenvio de Emails',690,0)		   

-- ESTOQUE
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('20','ESTOQUE',25,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2001','Requisição',641,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200101','Requisição - Manutenção',642,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200102','Requisição - Autorização/Cancela',643,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200103','Requisição - Geração de Cotação',644,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2002','Cotação',645,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200201','Cotação - Manutenção',646,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200202','Cotação - Autorização/Cancela',647,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200203','Cotação - Geração de Pedido de Compra',648,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2003','Central Análise de Compras (Revenda)',663,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2004','Pedidos de Compra',79,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200401','Pedidos de Compra - Manutenção',80,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200402','Geração de Pedidos de Compra',130,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2005','Pré-entrada de Produtos',315,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200501','Pré-entrada de Produtos - Manutenção',316,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2006','Entrada de Produtos',81,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200601','Entrada de Produtos - Inclusão',82,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200602','Entrada de Produtos - Alteração',388,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200603','Entrada de Produtos - Exclusão',389,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200604','Entrada de Produtos - Alteração',128,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200605','Importação de Notas de Entrada XML',504,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200606','Geração de Pedido de Venda pela Nota de Entrada',505,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2007','Planilha de Preços',83,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200701','Planilha de Preços - Manutenção',84,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2008','Alteração de Preço por Produto',85,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200801','Alteração de Preço por Prod.- Manutenção',104,0)		   
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200802','Alteração de Preços Entre Estabelecimentos',723,0)		   
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2009','Acertos de Estoque',86,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('200901','Acertos de Estoque - Manutenção',103,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2010','Avarias',134,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('201001','Avarias - Manutenção',135,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2011','Reservas',136,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('201101','Reservas - Manutenção',137,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2012','Parcerias de Fornecedores',501,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('201201','Parcerias de Fornecedores - Manutenção',502,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2013','Perfil do Estoque',213,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2014','Manutenção do Faceamento',300,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2015','Manutenção de Parâmetros p/Abastecimento',372,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2016','Balanço Picking',131,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('201601','Processa Balanço Picking',132,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2017','Balanço Depósito',538,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('201701','Autoriza Divergências',539,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('201702','Processa Balanço Depósito',540,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2018','Emissão de Etiquetas(lotes)',144,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2019','Geração de Arquivos - I',94,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2020','Geração de Arquivos - II',105,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2021','Geração de Arquivos p/ Clientes',165,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2022','Exportação',200,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2023','Comparativo Estoque OL',610,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2024','Agenda Central Análise de Compras',742,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('202401','Agenda Central Análise de Compras - Manutenção',743,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2090','Relatórios',109,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209001','Extrato de Verba Fornecedor',611,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209002','Gestão de Compras - Requisição de Compras',691,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209003','Gestão de Compras - Cotação de Compras',650,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209004','Sugestão de Compras',110,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209007','Pedidos de Compras',221,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209008','Divergência do Pedido com Nota de Entrada',324,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209009','Produtos Superestocados',166,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209010','Análise do Estoque por Produto (ABC)',207,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209011','Análise do Estoque por Fabricante',201,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209012','Produtos com Empréstimos entre Estoques',325,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209013','Relação das 3 últimas entradas por produto',612,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209014','Posição de Estoque / Preço',227,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209015','Produtos Zerados no Período',738,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209016','Tabelas de Preços',111,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209017','Relação de Promoções',314,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209018','Entradas / Faltas / Alt. Preços',117,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209019','Planilha de Preços',167,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209020','Razão Analítico de Produtos (Extrato)',168,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209021','Razão Sintético de Produtos',206,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209022','Acertos de Estoque',258,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209023','Reservas',305,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209024','Avarias',306,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209028','Produtos por Vencimento',310,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209029','Relação de Produtos por Localização',194,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209030','Espelho de NF de Entradas por Fornecedor',203,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209031','Relação de NF de Entradas por Período',228,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209032','Relação de Ítens de Notas de Entrada',307,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209033','Relatório Demontrativo de Custo Médio',352,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209034','Acompanhamento de Parcerias de Fornecedores',291,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209035','Acompanhamento de Verba (Fornecedores)',613,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209036','Estoque Analítico Fiscal',739,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209070','Balanço',169,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209075','Relatórios WMS',564,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209080','Produtividade de Conferência',563,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209081','Produtividade de Reposição',665,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209082','Margem de Rentabilidade por NF Entrada',614,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209083','Rastreamento de Produtos/Lotes',615,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('209084','Produtividade Recebimento NF Entrada',774,0)

-- CONTAS A RECEBER
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('25','CONTAS A RECEBER',26,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2501','Recebimentos',87,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250101','Recebimentos - Inclusão',88,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250102','Recebimentos - Alteração',331,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250103','Recebimentos - Exclusão',332,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250104','Recebimentos - Descontos',356,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250105','Baixa por Pagamentos - Inclusão',89,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250106','Baixa por Pagamentos - Alteração',339,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250107','Baixa por Pagamentos - Exclusão',340,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250108','Outras Baixas',181,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250109','Recebimentos - Inc/Alt Retroativa',720,0)
           
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2503','Recebimentos por Lote',483,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250301','Recebimentos por Lote - Inclusão',484,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250302','Recebimentos por Lote - Alteração',485,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250303','Recebimentos por Lote - Exclusão',486,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250304','Visualização de Recebimentos(lotes) de Terceiros',487,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250305','Manut. Recebimentos(lotes) de Terceiros',488,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250306','Recebimentos por Lote - Baixa Retroativa',721,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250307','Recebimentos por Lote - Fechamento',748,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2504','Cheques',252,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250401','Cheques - Inclusão',253,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250402','Cheques - Alteração',335,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250403','Cheques - Exclusão',336,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250404','Cheques - Compensação',337,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250405','Cheques - Devolução',338,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2505','Crédito de Clientes',293,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250501','Crédito de Clientes - Manutenção',294,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250502','Baixas de Crédito de Clientes',295,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2506','Ficha Financeira de Clientes',101,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2507','Negociação de Títulos',744,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250701','Negociação de Títulos - Manutenção',745,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250702','Negociação de Títulos - Fechamento',746,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2508','Vales',317,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250801','Vales - Inclusão',318,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250802','Vales - Alteração',392,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250803','Vales - Exclusão',393,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250804','Vales - Alteração de Lançamentos Automáticos',394,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2509','Ocorrências de Cheques',319,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('250901','Ocorrências de Cheques - Manutenção',320,0)
           
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2510','Emissão de Duplicatas',90,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2511','Reimpressão Simples de Duplicatas',142,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2512','Geração de Arquivos p/ Bancos',95,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2513','Recepção de Arquivos de Bancos',96,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2514','Intercâmbio Eletrônico',408,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2515','Geração de Arquivos - Parceiros',326,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2516','Borderôs de Cobrança',264,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('251601','Borderôs de Cobrança - Manutenção',265,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2517','Geração de Arquivos p/ Mala Direta',143,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('2590','Relatórios',112,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259001','Posição de Cobrança Vendedor (Cidade - Cliente) ',546,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259002','Posição de Cobrança Vendedor (Cliente) ',547,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259003','Posição de Cobrança Vendedor (Situação) ',548,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259004','Posição de Cobrança Vendedor (Observação) ',549,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259005','Posição de Cobrança Vendedor (Clientes Relac.)',550,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259006','Títulos por Vendedor - Portador',113,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259007','Resumo de Títulos por Vendedor',114,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259008','Relação de Duplicatas por Ag.Cobrador',148,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259009','Relação de Duplicatas por Emis./Vencim.',188,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259010','Rel. Duplicatas pagas por Emis./Vencim.',208,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259011','Resumo de Títulos em Atraso',357,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259014','Relação de cheques',251,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259016','Distribuição de Títulos por Vencimento',149,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259018','Previsão de Recebimentos por Vendedor',150,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259020','Baixas por Agente Cobrador',151,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259021','Remessa de Títulos',301,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259023','Ficha Financeira de Clientes',147,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259025','Clientes em Atraso por Cidade',125,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259026','Curva ABC de Inadimplência',263,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259027','Curva ABC de Débitos de Clientes',358,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259028','Simulação de Financiamento de Parcelas em Atraso',409,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259029','Relação de Créditos de Clientes',256,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259030','Relação de Recebimentos com Comissões',230,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259031','Relação de Comissão de Transportadoras',328,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259032','Relatório de Pagamentos de Comissões (Vales)',359,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259033','Relação de Recebimentos Diários',410,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259034','Análise de Faturamento por Recebimento',639,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('259035','Auditoria de Recebimentos',578,0)

-- CONTAS A PAGAR
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('30','CONTAS A PAGAR',27,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3001','Pagamentos',91,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('300101','Pagamentos - Inclusão',92,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('300102','Pagamentos - Alteração',333,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('300103','Pagamentos - Exclusão',334,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('300104','Baixa por Pagamento - Inclusão',93,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('300105','Baixa por Pagamento - Alteração',341,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('300106','Baixa por Pagamento - Exclusão',342,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('300107','Pagamentos - Inc/Alt Retroativa',718,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3090','Relatórios',115,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('309006','Contas a Pagar',116,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('309007','Contas a Pagar por Centro de Resultados',617,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('309008','Relação de Contas Pagas por Emissão/Vencimento',618,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('309009','Contas Pagas',214,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('309010','Contas Pagas por Centro de Resultados',619,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('309011','Ficha Financeira - Fornecedor/Favorecido',248,0)

-- FLUXO DE CAIXA
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('35','FLUXO DE CAIXA',28,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3501','Lançamentos',287,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350101','Lançamentos - Manutenção',288,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350102','Lançamentos - Manutenção - Baixa Retroativa',719,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3502','Fechamento de Lançamentos',522,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3504','Transferência Entre Contas',507,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350401','Transferência Entre Contas - Inclusão',508,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350402','Transferência Entre Contas - Alteração',509,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350403','Transferência Entre Contas - Exclusão',510,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3505','Conciliação Bancária',343,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350501','Conciliação Bancária - Cancelamento',344,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3506','Pagamento Eletrônico',605,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350601','Pagamento Eletrônico - Remessa',606,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350602','Pagamento Eletrônico - Retorno',607,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3507','Planejamento Orçamentário',659,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350701','Planejamento Orçamentário - Manutenção',660,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350702','Planejamento Orçamentário - Remanejamento de Verba',661,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('350703','Planejamento Orçamentário - Inc/Ret de Verba',662,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3508','Geração de Arquivos - Fluxo de Caixa',692,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3580','Procedimentos Especiais',280,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('358001','Atualização do Plano de Contas Contábil',225,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('358099','Configurações',276,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('3590','Relatórios',216,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359001','Fluxo de Caixa',217,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359002','Estatística de Recebimentos e Pagamentos',218,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359003','Extrato de Contas Financeiras',273,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359004','Resumo de Movimentação de Contas',274,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359005','Resumo por Histórico de Contas',286,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359006','Posição de Saldo das Contas',275,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359007','Pagamentos por Conta de Classificação',626,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359008','Relatório de Conciliação Bancária',361,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359009','Balanço Patrimonial',511,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359010','Extrato de Contas Gerenciais',512,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359011','D.R.E.',519,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('359012','Movimentação Financeira',627,0)

-- ESCRITA FISCAL
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('40','ESCRITA FISCAL',29,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4001','Notas Fiscais de Venda',97,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('400101','Notas Fiscais de Venda - Inclusão',98,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('400102','Notas Fiscais de Venda - Alteração',390,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('400103','Notas Fiscais de Venda - Exclusão',391,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4002','Notas Fiscais de Compra',99,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('400201','Notas Fiscais de Compra - Manutenção',100,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4003','Gera Título (Tributos)',620,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4004','Mapa de Movimentação de ECF',552,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('400401','Mapa ECF - Inclusão',553,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('400402','Mapa ECF - Alteração',554,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('400403','Mapa ECF - Exclusão',555,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4010','Exportação',152,0)



Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4015','Importação',327,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4020','Processamento',556,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4021','Processamento - Termo de Acordo (CE)',557,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('402101','Termo de Acordo (CE) - Inclusão',597,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('402102','Termo de Acordo (CE) - Alteração',598,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('402103','Termo de Acordo (CE) - Exclusão',599,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4022','Processamento - Ressarcimento ST (SC)',558,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4023','Processamento - Inventário em 30/09/2009',559,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4025','Módulo Fiscal',560,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4090','Relatórios',153,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409002','Relação de N.F. Emitidas p/ Outros Estados',154,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409004','Relação de N.F. Saída por Período',155,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409006','Relação de Vendas por Tipo de Cliente',345,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409008','Relação de Saídas por Cidade',346,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409010','Apuração de ICMS',157,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409011','Apuração de PIS/COFINS',561,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409012','Relação PIS/COFINS Analítico',621,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409013','Diário Auxiliar de Recebimentos',158,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409014','Resumo de Entrada-Saida por Lista',640,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409015','Resumo de Faturamento (PIS)',347,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409016','PIS/COFINS - Regime de Caixa',652,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409017','Relação de N.F. c/ Crédito Fiscal',156,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409018','Pernambuco',622,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409019','Demonstrativo de Tributação Fiscal',196,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409020','Demonstrativo Tributação Entradas (MS) - Planilha',562,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409021','Relação de Avarias c/ Tributos',202,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409022','Registros Fiscais de Entradas',159,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409023','Registros Fiscais de Saídas',160,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409024','Apuração de Partilha de ICMS',574,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409025','Relatório Mensal de Controlados',161,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409026','Relatório de Registro de Controlados - RDC 55/05',623,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409027','Balanço das Aquisições de Controlados',226,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409028','Balanço Periódico de Controlados',195,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409030','Inventário Físico',162,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409032','Resumo de Mapas ECF',530,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409033','Apuração de Estoque Por CMV',624,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409034','Relação de Itens da Nota Fiscal - DIFAL',600,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409035','Relação de Itens da Nota Fiscal - FECOP',699,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409036','Apuração de Estoque Por CMV',601,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409037','Relação PIS/COFINS Analítico',602,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('409038','Relatório NFs de Fretes com NFs Referenciadas',724,0)		   

-- HOSPITALAR
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('45','HOSPITALAR',238,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4501','Propostas',240,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450101','Propostas - Inclusão',241,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450102','Propostas - Alteração',470,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450103','Propostas - Exclusão',471,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4502','Tipos de Propostas',296,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450201','Tipos de Propostas - Inclusão',297,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450202','Tipos de Propostas - Alteração',472,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450203','Tipos de Propostas - Exclusão',473,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450204','Produto Bloqueado para Propostas',773,0)  

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4503','Contratos',474,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450301','Contratos - Inclusão',475,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450302','Contratos - Alteração',476,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450303','Contratos - Exclusão',477,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('450304','Contratos - Geração de Pedidos de Venda',478,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4510','Planilha de Preços',243,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('451001','Planilha de Preços - Manutenção',244,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4515','Alteração de Preços',247,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('4590','Relatórios',245,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('459005','Posição de Preços/Estoque',246,0)

-- WMS
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('50','WMS',411,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5001','Esteiras',495,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500101','Esteiras - Inclusão',496,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500102','Esteiras - Alteração',497,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500103','Esteiras - Exclusão',498,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5002','Depósitos/Zonas',412,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500201','Depósitos/Zonas - Inclusão',413,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500202','Depósitos/Zonas - Alteração',414,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500203','Depósitos/Zonas - Exclusão',415,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5003','Endereços de Depósitos',523,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500301','Endereços de Depósitos - Inclusão',524,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500302','Endereços de Depósitos - Alteração',525,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500303','Endereços de Depósitos - Exclusão',526,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5004','Caixas Padrões',416,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500401','Caixas Padrões - Inclusão',417,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500402','Caixas Padrões - Alteração',418,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('500403','Caixas Padrões - Exclusão',419,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5014','Reabastecimento de Fracionados',364,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5015','Transferência de Lotes',366,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5016','Consulta por Zonas',420,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5017','Rastreamento (Endereços) de Produto/Lote',529,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5018','Rastreamento de Atividades',534,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('501801','Atividades - Manutenção',535,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5019','Transferência de Lotes por Zona',775,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5020','Manutenção de Parâmetros p/Abastecimento',421,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5021','Separação de Pedidos (Fracionados)',363,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('502101','Abastecimento',700,0)		   
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5022','Correção de Pedidos (Fracionados)',422,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5023','Cancelamento de Pedidos (Fracionados)',423,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5024','Embalagem de Volumes',365,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5080','Coletores',590,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('508001','Entrada',591,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('508002','Nota Cega',594,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('508003','Endereçamento',592,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('508004','Expedição',593,0)

-- ECF
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('55','PDV',424,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5501','Estabelecimentos',425,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550101','Estabelecimentos - Inclusão',426,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550102','Estabelecimentos - Alteração',427,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550103','Estabelecimentos - Exclusão',428,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5502','Endereços',429,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550201','Endereços - Inclusão',430,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550202','Endereços - Alteração',431,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550203','Endereços - Exclusão',432,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5503','Tabela de Caixas',433,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550301','Tabela de Caixas - Inclusão',434,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550302','Tabela de Caixas - Alteração',435,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550303','Tabela de Caixas - Exclusão',436,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5504','Operadores de Caixas',437,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550401','Operadores de Caixas - Inclusão',438,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550402','Operadores de Caixas - Alteração',439,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550403','Operadores de Caixas - Exclusão',440,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5505','Entregadores',441,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550501','Entregadores - Inclusão',442,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550502','Entregadores - Alteração',443,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550503','Entregadores - Exclusão',444,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5506','Cartões Magnéticos',445,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550601','Cartões Magnéticos - Inclusão',446,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550602','Cartões Magnéticos - Alteração',447,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550603','Cartões Magnéticos - Exclusão',448,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5507','Formas de Pagamento',449,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550701','Formas de Pagamento - Inclusão',450,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550702','Formas de Pagamento - Alteração',451,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550703','Formas de Pagamento - Exclusão',452,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5508','Politicas de Vendas',453,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550801','Politicas de Vendas - Inclusão',454,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550802','Politicas de Vendas - Alteração',455,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550803','Politicas de Vendas - Exclusão',456,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5509','Percursos Romaneios',685,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550901','Percursos Romaneios - Inclusão',686,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550902','Percursos Romaneios - Alteração',687,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('550903','Percursos Romaneios - Exclusão',688,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5511','Cupons de Vendas',402,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('551101','Devolução de Produtos',776,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5512','Sangria / Suprimento',651,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5513','Lançamentos de Cartões Magnéticos',457,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('551301','Lançamentos de Cartões Magnéticos - Inclusão',458,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('551302','Lançamentos de Cartões Magnéticos - Alteração',459,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('551303','Lançamentos de Cartões Magnéticos - Exclusão',460,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5514','Fechamento de Cartões Magnéticos',461,0)


Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5590','Relatórios ECF',462,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('559001','Relatórios de Vendas ECF',403,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('559002','Relatórios de Lançamentos de Cartões Magnéticos',463,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('559003','Relatórios de Fechamento de Caixa',464,0)


-- TERMINAL
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('56','Terminal',566,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('5610','Fechamento Caixa Geral',567,0)


-- INFORMAÇÕES GERENCIAIS
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('60','INFORMAÇÕES GERENCIAIS',30,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('6001','Relatórios',631,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('600101','Resumo de Vendas por Prazo Médio',632,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('600102','Resumo de Recebimentos por Prazo',633,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('600103','Relação de Notas Fiscais por Período',634,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('600104','Rentabilidade por Cliente',635,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('600105','Rentabilidade por Fabricante',636,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('600106','Rentabilidade por Vendedor',637,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('600107','Resumo Geral da Empresa',638,0)

-- GERADOR DE RELATÓRIOS
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('65','GERADOR DE RELATÓRIOS',353,0)

-- BI - BUSINESS INTELLIGENCE
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('70','BI - BUSINESS INTELLIGENCE',375,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7001','Cubo de Vendas',380,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700101','CMV',383,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700102','Custo Médio',384,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700103','Lucro',385,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700104','Ressarcimento',386,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700105','Substituição Tributária',387,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700106','Preço Liquido Ultima Entrada',653,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7002','Cubo Financeiro',381,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7003','Cubo de Compras',382,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7004','Cubo Cadastro - Produtos',654,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700401','Preço Custo Liquido',655,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700402','Preço Custo Médio',656,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700403','Preço Ultima Compra',657,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('700404','Preço Ultima Entrada',658,0)
insert into dbo.ROTIN (Wbs_Rotina, Des_Rotina, Isn_Rotina, Opc_Default)
           Values ('7005', 'Cubo Cadastro - GERAL',749,0)


-- MOBILE
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('75','ACESSO MOBILE',583,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7501','Módulo OnLine',584,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7502','Módulo de Vendas',585,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7503','Módulo de Compras',586,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7504','Módulo de Estoque',587,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7505','Módulo Financeiro',588,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('7506','Módulo Rentabilidade',589,0)

-- NOTA FISCAL ELETRONICA
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('80','NOTA FISCAL ELETRÔNICA',531,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('8001','Emissão da NF-e',532,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('8002','Impressão da NF-e',533,0)

-- MANUTENÇÃO DO SISTEMA
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('90','MANUTENÇÃO DO SISTEMA',31,0)
           
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9001','Manutenção de Preços e Custos',118,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900101','Alteração de Preços',545,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900102','Preço Última Entrada 1 - Visualização',751,0) --467

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900103','Preço Última Entrada 1 - Alteração',752,0) --543

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900104','Desconto Última Entrada 1 - Visualização',753,0) --467

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900105','Desconto Última Entrada 1 - Alteração',754,0) --543

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900106','Preço Última Entrada 2 - Visualização',755,0) --467

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900107','Preço Última Entrada 2 - Alteração',756,0) --543

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900108','Desconto Última Entrada 2 - Visualização',757,0) --467

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900109','Desconto Última Entrada 2 - Alteração',758,0) --543

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900110','Custo Líquido Entrada 1 - Visualização',759,0) --467

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900111','Custo Líquido Entrada 1 - Alteração',760,0) --543

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900112','Custo Líquido Entrada 2 - Visualização',761,0) --467

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900113','Custo Líquido Entrada 2 - Alteração',762,0) --543

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900114','Custo Médio 1 - Visualização',763,0) --480

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900115','Custo Médio 1 - Alteração',764,0) --544

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900116','Custo Médio 2 - Visualização',765,0) --480

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900117','Custo Médio 2 - Alteração',766,0) --544

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900118','Custo Médio Gerencial - Visualização',767,0) --480

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900119','Custo Médio Gerencial - Alteração',768,0) --544

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900120','Custo Médio COMERCIAL - Visualização',769,0) --480

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900121','Custo Médio COMERCIAL - Alteração',770,0) --544

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900122','Preço Venda Atual - Visualização',771,0) --467

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900123','Preço Venda Atual - Alteração',772,0) --543
/*
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900124','Bloqueio de Visualização de Custos de Entrada',467,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900125','Bloqueio de Visualização de Custos Médios',480,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900126','Bloqueio de Alteração de Custos de Entrada',543,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('900127','Bloqueio de Alteração de Custos Médios',544,0)
*/
           
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9002','Alteração de Comercialização',119,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9003','Alteração de Comissões',127,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9004','Correlação de Códigos de Produtos - Manutenção',355,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9005','Numeração Fiscal (NF, Selo, Formul.)',141,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9006','Manutenção de Tributos em Notas Fechadas',223,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9007','Reprocessamento de Tributos de Entradas',551,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9008','Bloqueia Visualização de Saldos de Contas Partidas',468,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9009','Visualização de Saldos de Contas Partidas',481,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9010','Rotinas Diárias',176,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9011','Rotinas Mensais',177,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9012','Reprocessamento Comissão Vendas',178,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9013','Reprocessamento Acumuladores',722,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9014','Reprocessamento Comissão Duplic.',179,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9015','Fechamento de Comissões',321,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9016','Consulta de Tabela/Campos Obrigatórios',729,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9017','Rotinas Tabela/Campos Obrigatórios',730,0)

Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9030','Opções/Parâmetros Auditoria',728,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('903001','Configurar Tabelas para Auditoria',694,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('903002','Consultar Auditoria das Tabelas',695,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('903003','Alterar Quantidade Dias para Expurgo da Auditoria',696,0)


Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9050','Opções (Parâmetros)',180,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905001','Opções Comerciais',187,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905003','Opções de Faturamento',190,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905005','Opções de Cobrança',191,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905007','Opções Especiais',192,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905009','Opções de Controles',268,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905010','Opções de Comissões',330,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905011','Opções de Impressão',269,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905013','Opções de Arquivos',270,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905015','Opções de Estoque',271,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905017','Opções de Configuração',272,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('905020','Opções da Hospitalar',242,0)
		   
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9051','Opções/Parâmetros Financeiros',362,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9052','Cadastro de Imagens',731,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9053','Parâmetros de E-Mail',732,0)


-- ADMINISTRAÇÃO DO SISTEMA / outros sub-sistemas
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('99','Administração do Sistema',211,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9905','Reorganização/Manutenção Arquivos',212,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9950','Sub-sistema para Depósitos Dedicados',565,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9980','Autorização de divergência entre pedido e n.fiscal',570,0)
Insert Into ROTIN (Wbs_Rotina,Des_Rotina,Isn_Rotina,Opc_Default)
           Values ('9981','Autorização de divergência entre n.fisc. e coletor',727,0)
           
GO           


-- executa rotina (procedimentos iniciais) para registrar novas rotinas x controle de acesssos
Declare @CodEst int = -1
while Exists(Select 1 From ESTAB Where Cod_Estabe > @CodEst)
  begin
   Set @CodEst = (Select top 1 Cod_Estabe From ESTAB Where Cod_Estabe > @CodEst)
   Exec PR_ProIni_AtualizaContrAcesso @CodEst
  end
GO
